### ISSUE TITLE
SetMoveAngles( ) listed as Shared but only works Serverside

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-issues#1181]
Hey - I've been working on a lot of client side stuff like third person cameras and what not. The thing that would complete my third person script is a way to force +forward, +moveleft, +back, and +moveright to walk at specific angles, and "SetMoveAngles( )" seemed to be the function I'm looking for. Unfortunately, it works server side, and I would have to network my variables for proper movement.

Is there any way this can be fixed?

Apologies for the duplicate one I closed in requests - I'm a dolt.

**Comment by IcedCoffeee** [comment]
I too need this for a better functioning third person camera.
It definitely doesn't work in any of the clientside CMoveData hooks, and setting it serverside just creates a buggy mess on high ping servers.
If this could get fixed it'd well appreciated by anyone trying to make a GTA style third person camera.

**Comment by IcedCoffeee** [comment]
After some more testing, it appears to be "trying" to work in the PlayerTick hook, but it's getting completely ignored by the server and doesn't show up in mv:GetMoveAngles() on the server. Maybe the servers prediction of where the player should be is overriding it?

**Comment by MaslovKK** [comment]
still not working in all clientside hooks

**Comment by robotboy655** [comment]
I have looked into it briefly, and from what I can tell, yeah, it appears to "not work", but it **DOES** have an effect as evidenced by prediction errors, and that is the expected behavior.

```
-- If ran clientside only, does have an effect, albeit not the one you want it to.
hook.Add( "SetupMove", "test", function( ply, mv, cmd )
	mv:SetMoveAngles( Angle(0,0,0) )
end)
```

It sets a variable internally (`m_vecViewAngles`), but that variable is not networked to server (The entire structure is not as far as I can tell). On the server, the same variable is initialized from [CUserCmd:SetViewAngles](https://wiki.facepunch.com/gmod/CUserCmd:SetViewAngles)

So it appears what Jvs34 said above back in 2014 still stands. What you want to do is either use `CUserCmd:SetViewAngles` if you only want to do this from clientside, or call `CMoveData:SetMoveAngles` shared.

Alternatively, you can do the math yourself and apply it via [CMoveData:SetSideSpeed](https://wiki.facepunch.com/gmod/CMoveData:SetSideSpeed), [CMoveData:SetForwardSpeed](https://wiki.facepunch.com/gmod/CMoveData:SetForwardSpeed) and [CMoveData:SetUpSpeed](https://wiki.facepunch.com/gmod/CMoveData:SetUpSpeed)
