### ISSUE TITLE
ManipulateBoneScale Unexpected Behavior

### ISSUE THREAD

**Issue by shadowscion** [Facepunch/garrysmod-issues#1249]
This function seems to be clamped in a really awkward and unusable way now. 

Spawn a basic prop, a phx plate works well, then look at it and run this code:

```
Entity(1):GetEyeTrace().Entity:ManipulateBoneScale(0, Vector(50, 1, 1))
```

Then run this code:

```
Entity(1):GetEyeTrace().Entity:ManipulateBoneScale(0, Vector(500, 1, 1))
```

As you can see, the YZ values are being changed, even though they are not being told to, it's like the scale vector is clamped within a maximum magnitude or something.

The renderbounds are also broken.

**Comment by besenyei** [comment]
Could this be fixed anytime soon?
I guess UnderscoreKilburn never got around to asking Garry about that limitation.

**Comment by besenyei** [comment]
Could this be looked into, because manipulating bones of any sort of entity breaks it's bounding box.

[Swep Construction kit](https://steamcommunity.com/sharedfiles/filedetails/?id=109724869)
This addon is entirely based on the concept of attaching and manipulating models to give a complete different appearance.

PAC3 is also affected, however they have their own workaround to this bug. https://github.com/CapsAdmin/pac3/issues/654#issuecomment-399342455

**Comment by Kefta** [comment]
Could this hardcoded limit be removed? It's been 4 years..

**Comment by robotboy655** [comment]
I will raise the limit to 512 and we shall see if that causes any issues.
