### ISSUE TITLE
SNPCs shooting bullets from their feet

### ISSUE THREAD

**Issue by DrVrej** [Facepunch/garrysmod-issues#1275]
**When a SNPC shoots a weapon, the bullet seems to spawn from its feet.
Here is what I mean: https://www.youtube.com/watch?v=DPTx2j8ZVGsz**

This is how the SNPC shoots:

```
self:SetSchedule(SCHED_RANGE_ATTACK1)
```

Or in some other cases I use other types of SCHED_ or TASK_

_Thank you for reading._

**Comment by robotboy655** [comment]
If this still happens, post full minimal code to reproduce this bug. (That will work out of the box) Otherwise there is nothing to be done.

I do not see any problems with normal NPCs shooting over obstacles. I even downloaded this SNPC pack (https://garrysmods.org/download/24153/combine-beta-snpcs) to test this and the NPCs had no trouble shooting over obstacles.
