### ISSUE TITLE
(Sarcastic) Multithread support

### ISSUE THREAD

**Issue by Ameno-Sagiri** [Facepunch/garrysmod-issues#1388]
With all this new technology coming out these days, I was thinking that FIXING the ability to utilize that brand new multi-techno-core and multi-tasking thingamajig that's appearing in the newest of games these days would really benefit people that use Garry's Mod for anything but Motion Blurring screenshots.
![360fx360f](https://cloud.githubusercontent.com/assets/5976053/3786610/ac7911dc-19dd-11e4-98e7-7e4f834b4074.png)

**Comment by UltimateByte** [comment]
http://www.facepunch.com/showthread.php?t=1243028

**Comment by thegrb93** [comment]
Didn't you read what garry said?

A) Crashes
B) Mutexes - Which will destroy any performance gain multithreading will provide.

**Comment by UltimateByte** [comment]
Then remove lua.

No, seriously, not everyone knows what mutex is, pardon my ignorance. Is that really undoable ? No fix possible ? Not possible to keep lua in one thread and the engine multithreaded ?
Cause really, now when you charge gmod since a few years, performance level is just insanely low... User experience is shitty because of that when you try to make interesting things on beautiful maps, there's no other word.

**Comment by notcake** [comment]
What framerate do you get on gm_construct? What about with no addons?

**Comment by UltimateByte** [comment]
More than 150-200 with addons. But what's the point to playing gmod solo with no addons ? I'm talking of games in giant maps with hundred of props and more than 30 players...

**Comment by notcake** [comment]
And what fps do you get typically in that case?

**Comment by UltimateByte** [comment]
15 to 30... Gpu at 20%, cpu at 18%... I even saw a guy with an sli of 770gtx and a 5960x having trouble (must be misconfiguration from him but still) at 8fps on the same map than me. rp_rockford... Even on freespace in build mode, there are hardcore builders on my serv, i can easilly go below 30 fps when my screen displays too many props. And i have a still pretry damn good pc compared to others, that's what makes me even more sad for them...

**Comment by thegrb93** [comment]
>rp
There's the problem

**Comment by UltimateByte** [comment]
I was sure of that answer. That's why i had to say it's also bad when you charge any sandbox game too...

**Comment by thegrb93** [comment]
Doesn't matter. The map is consuming a huge chunk of processing with all of the unoptimized visleaf checking, collision checking, etc. Bsp isn't very good for open worlds.

**Comment by UltimateByte** [comment]
With nothing on rockford and no addons i achieve 115 fps. With players i usually go under 20fps... And 20%gpu, this is the real issue. As i said, if ir was multithread, like capable of using 4 cores, i'd achieve 4 times the framerate...

By the way, one more time : even on flatgrass or gm_construct witj pretty epic builds, like trains designed with s-props with nice materials, online, i go under 30 fps easilly. Still with 1 full core and almost idle gpu. I guess I don't need to argue anymore as the issue is known and recognized. I just had to mention the critical framerate issues it caused. And i don't even talk about stuttering while spawning a new prop, or game freezing at launch while checking subscribed addons (not sure if that last one is multithread related), or loading time, or again freeze at server join when it jas lots of props...  The point is you can't exploit and enjoy all the nice things of gmod with such a poor framerate, gaming experience is just blowed up.

**Comment by thegrb93** [comment]
Are you on linux? That could be another reason why. Try turning of prop spawn effects and physgun halos to get rid of the stuttering. I know someone who had that problem and he uses linux. Doesn't happen on windows though.

**Comment by robotboy655** [comment]
Move your discussion to https://github.com/Facepunch/garrysmod-requests/issues/152
