### ISSUE TITLE
Entity.SetFriction has no effect for players

### ISSUE THREAD

**Issue by disseminate** [Facepunch/garrysmod-issues#1395]
Currently Entity.SetFriction sets the keyvalue "m_flFriction" which is great for props or other entities that rely on this keyvalue. It has no effect on players.

Player friction is set in engine via pEnt->SetFriction( float multiplier ) instead. Adding a IsPlayer() check for this would solve it.

**Comment by Kefta** [comment]
The way func_friction is implemented is actually pretty shitty -- it overrides the previous value instead of using it to calculate the friction at PlayerMove time. It would be nice if a GMod-specific func_friction were made that didn't override the previous value, but that's more of a request.

**Comment by Kefta** [comment]
Get/SetFriction would have to be shared for players and network any updates to the client since player movement is done shared. Other than that, adding friction support to player movement is pretty easy - GetFriction just has to be factored into these lines:

- https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/shared/gamemovement.cpp#L1426
- https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/shared/gamemovement.cpp#L1630
- https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/shared/gamemovement.cpp#L2225
- https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/shared/gamemovement.cpp#L2304

**Comment by Invalid-Vertex** [comment]
I hate to bump such an old issue, but has there been any progress on fixing this?

**Comment by colemclaren** [comment]
This has been an issue for too long. Please fix. I would like to be able to set the friction of players when they are shot by a gun, but it is currently not possible. This would make for a great equipment item in TTT for traitors to slow down people. @svdm

**Comment by robotboy655** [comment]
`SetFriction` now affects player movement, as a multiplier of `sv_friction` convar's value, in range of [0,10].

**Comment by disseminate** [comment]
Thanks I got engaged and bought a house and divorced and moved continents and moved back and did it again but it was worth it
