### ISSUE TITLE
Using ErrorNoHalt in the menu state crashes the game.

### ISSUE THREAD

**Issue by meharryp** [Facepunch/garrysmod-issues#1810]
See title. Using Error also crashes the game.

**Comment by markusmarkusz** [comment]
As a small addition: [RunConsoleCommand](http://wiki.garrysmod.com/page/Global/RunConsoleCommand) also crashes the game.
I attach this because I believe that a new issue is not necessary because the problems are quite similar.

**Comment by robotboy655** [comment]
ErrorNoHalt and Error don't exactly crash, they exit the game in menu state intentionally. No idea why it was made this way, probably for some debugging, and I probably won't change back as it doesn't really affect anything since menu state is off limits to addons.

I could not confirm RunConsoleCommand or require crashing.

**Comment by Kefta** [comment]
Can you just redirect those error calls to a normal menu error? I'm writing a custom menu to allow menu additions and there's no way to throw a function error without exiting the game.

**Comment by robotboy655** [comment]
JOKES it's fixed now.
