### ISSUE TITLE
Crashs

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#1876]
Since the GMod Update my server crashs 20 times a day and It happens if just a player joins the game.
I use the same scripts as before, even I prepared my server for the update.
Changed NWVars etc.
Even If I spawn a TDM Car Prop my Server crashs either.
Had to restrict them. I don't know how a simple prop which works fine in singleplayer can crash a whole server.
Since this Update it seems that every thing is crashing my server, I mean I throw a knife from M9K which has worked perfectly before the update and it crashed JUST my server.
Just getting a specified weapon crashs my server. What did just update?

**Comment by samgillie** [comment]
A few things where broken in the update. They are working on some kind of hotfix but no one has any Idea when it will come..     :(    Wish it would soon though, its getting a tedious.

**Comment by deinemudda32** [comment]
Hm thanks for the reply.
I don't understand however how spawing entitys or even props could crash a server.
I mean in the changelog theres nothing about it, without that the spawning of vehicles is now optimized

**Comment by TheFreeman193** [comment]
The last update was a particularly large one and there are a several bugs being worked on at the moment.
What OS is your server running on? Can you post the crash log so we can see if your crash is similar to some of the others?

**Comment by deinemudda32** [comment]
I am on a linux server.
The crashs are only happening on my Sandbox and DarkRP Server.
My TTT Server runs perfectly.
I optimized every addon for my server and it keeps crashing for different reasons.
Mostly prop spawning. Even Hoverboards, Knifethrowing, TDM Cars Spawning crashs my server.
That never happend before.

**Comment by robotboy655** [comment]
It's definitely a problem with new NWVars, it will be fixed.

**Comment by deinemudda32** [comment]
Its not a problem with NWVars as in TDM Cars, the M9K Knife is no NWVar.
It just crashs randomly on spawning specified addon props or use specified things.
It never happend before and I don't know why it happens now.
But unfortunately only on SBox and DRP.

**Comment by williamdefly** [comment]
I have the same problem on my server spacebuild

**Comment by deinemudda32** [comment]
Since the hotfix of the update my server runs better but the stability issues arent fixed.
It crashs with the message "Segmentation Fault". Since the update.
I don't know how to fix it, I don't get lua errors, clientside errors or other responses from the server.
It just crashs and autorestarts.
Some random props spawns crash it, car spawns crash it.
I don't know how many things my server could actually crash.

It actually was a new issue, cause I thought robot thinks its fixed, but got deleted so I post it here. :§

**Comment by deinemudda32** [comment]
Yea its not fixed. My server either crashs on MASS playerjoin. So mapchange.

**Comment by X-Coder** [comment]
Hi I was running a garrysmod dedicated stargate /spacebuild server since a few years, but I had to shut it down now because it runs totally unstable since the last update. I just did a update some minutes ago, and it still crashes.

I uploaded multiple server dumps. Last one: http://dumps.metastruct.uk.to/dumper.py?dump=srcds_1678491_crash_2015_3_20T20_20_55C0.mdmp. Each of the dump has the same crash reason: EXCEPTION_ACCESS_VIOLATION_READ with the last stack entry pointing to engine.dll. Did something changed in eninge.dll?

Often the server crashes right when someone leave the spawn area, and almost everytime it crashes right when I spawn a dupe using advanced duplicator 2. The dupe contains spacebuild, stargate and wiremod stuff.

If someone is working on this issue, please keep this thread updated, so I know when to turn the server back on.

**Comment by deinemudda32** [comment]
I dont think there will be a fix for this.
