### ISSUE TITLE
Entity:SetHealth doesn't work clientside (for prediction)

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-issues#1965]

**Comment by Jvs34** [comment]
You shouldn't do prediction on SetHealth, it's pointless really.

**Comment by Jvs34** [comment]
If it's something that is affected by the server really often , you should leave it like it is, trying to predict it just gives more troubles than it's worth.

**Comment by Bo98** [comment]
I just assumed it was shared because of prediction (+ cl_showerror threw errors).

**Comment by Jvs34** [comment]
I highly doubt garry did that on purpose, it was probably an oversight when binding it since the function is defined and didn't give out any compile errors but the function itself doesn't do anything.


https://github.com/ValveSoftware/source-sdk-2013/blob/56accfdb9c4abd32ae1dc26b2e4cc87898cf4dc1/mp/src/game/client/c_baseentity.h#L743
