### ISSUE TITLE
Add fov option to "CalcViewModelView"

### ISSUE THREAD

**Issue by iSnipeu** [Facepunch/garrysmod-issues#1991]
Being able to change the FOV for view models in that hook like you can with player FOV in CalcView would be handy.

**Comment by Jvs34** [comment]
I believe the new CalcViewModelView is called too late in-engine to modify the fov so that's just not possible, however CalcView should be able to.

https://github.com/ValveSoftware/source-sdk-2013/blob/56accfdb9c4abd32ae1dc26b2e4cc87898cf4dc1/mp/src/public/view_shared.h#L90

That kind of sucks since it can't be added easily to the viewmodel hook, I know.

**Comment by imp0se** [comment]
From what I remember, there's another place for making suggestions.
This is not a bug, this is a suggestion.

**Comment by iSnipeu** [comment]
oops my bad, I'll remake it over in the requests repo
