### ISSUE TITLE
i cant open it

### ISSUE THREAD

**Issue by efrenmanuel** [Facepunch/garrysmod-issues#2026]
when im starting it, it closes in a few seconds
http://dumps.metastruct.uk.to/dumper.py?dump=hl2_140713_crash_2015_2_14T12_52_13C0.mdmp
(crash report)

**Comment by Acecool** [comment]
A few questions.. Is it closing due to not responding or is is simply closing without warning?

Have you gone through all of the standard steps? Right click Garry's Mod in Library > Properties > Local Files > Verify Integrity of Game Cache -- See if that helps.

If not, go to the last tab, Betas > Choose Dev - Development Branch from the drop-down and try to relaunch ( it should update ). If you had Dev selected, try None.

Make sure your video drivers are up to date. You can force a somewhat "safe-mode" by adding -dxlevel 81 to launch options which will reset your video settings ( and will every launch while you change dxlevel; you can try 81, 95, 98, 110 and there may be others )...

**Comment by efrenmanuel** [comment]
i repaired it. It was a problem with the steamid archive... I supouse it was corrupted

**Comment by efrenmanuel** [comment]
Thanx
