### ISSUE TITLE
Netchannel corruptions

### ISSUE THREAD

**Issue by Xerasin** [Facepunch/garrysmod-issues#2099]
Recently my server has been struct with some strange problems with networking.

Things that have been happening
* Clients will randomly join the server and have entities that have empty entity-tables
* Clients will get disconnected either with no visible disconnect reason or random characters
* Clients will get dropped during join with errors like "server returned version 0, expected 24." in console
* Messages like "failed reading message net_SetConVar" after a failed connection attempt

Things to note
* We do use a lot of NWVars (627)
* I've reinstalled the server twice
* I've checked every lua file to see if I was sending a ton of net messages during spawn (I wasn't [From] (http://facepunch.com/showthread.php?t=1387607))
* I've tried googling around to see if this problem is happening to anyone else (it isn't)
* I've noticed the only pattern I can notice is mostly entities that are not in a folder load fine. Althought there are a couple exceptions.

Console Log of a client:
[Client Log](http://sharex.xeras.in/2015/06/15/14-59-04_214.txt)
[Client Log 2](http://sharex.xeras.in/2015/06/15/15-29-40_215.txt)
[Client Log 3](http://sharex.xeras.in/2015/06/15/15-35-07_217.txt)
[Server Log of George Lucas getting it](http://sharex.xeras.in/2015/06/15/15-51-12_218.txt)
(The error is from a empty entity table)

**Comment by Jitterclick** [comment]
This isn't a bug though, talk to your server provider or something. Facepunch has nothing to do with this.

**Comment by PotcFdk** [comment]
It's worth noting that I've heard people complaining about NWVars in the recent past.
[This](http://facepunch.com/showthread.php?t=1450721&p=47876966&viewfull=1#post47876966) is the only one I can find at this very moment, but there have been more.
@Jitterclick How isn't this a bug? We're seeing corruptions here that shouldn't happen.
@robotboy655, NWVars?

**Comment by Xerasin** [comment]
I counted how many NWVars are used the majority of the time using GetNWVarTable and it comes out to be 634 with 20 players

**Comment by Jitterclick** [comment]
Well Facepunch, to put it simply, are assholes. They don't fix anything, and they make shitty games ok.
They won't fix this, and they won't fix mine. @PotcFdk

**Comment by Jvs34** [comment]
You really want to be banned, don't you.

**Comment by meharryp** [comment]
@Jitterclick They're going to be assholes if you're going to be an asshole to them #2100

**Comment by Acecool** [comment]
My networking addon replaces NW vars with my data flags ( which are only sent on change, rather than continuously or on request -- if the client doesn't have it, a default is provided unless you specifically want the client to request the flag which must be done by a developer ). It also restricts any net-messages from being sent to players that are still connecting ( to prevent overflows from net-messages; voice or other channels may still be an issue ).

My networking addon is far from complete and still needs the registry to be implemented ( which overrides the current message system so the message is sent and received in the most optimized method rather than using the default [ allowing "unlimited" data ] method ) so it may not be the best choice until I update it. I've been busy getting ready to release my framework among other things, but it may be worth a try... There should be concommands that come with the net addon ( they are in the game mode base and I can post them if you want to try them ) which shows you the data that is accessible by the client; another note, my data system uses its own table indexed by the entindex so even if the entity doesn't exist on the client [ never encountered in pvs means the entity is NULL ], the data can still be accessed and stored )...

**Comment by xaviergmail** [comment]
I think this is a massive bottleneck and I am willing to help out and test the new implementation as soon as it hits the dev branch.
