### ISSUE TITLE
Can't teleport SWEPS using trigger_teleport or other triggers

### ISSUE THREAD

**Issue by 1WHISKY** [Facepunch/garrysmod-issues#2224]
You can't teleport SWEPS using trigger_teleport even with the spawn flags "Physics Objects" or "Pushables". I tried making a SENT teleporting the SWEP when touching it but it doesnt work for SWEPS, however props or players work fine.
Also trigger_multiple or other triggers can't be triggered by SWEPS

Garry's mod version: 2015.08.12

**Comment by robotboy655** [comment]
Does it work on HL2 weapons?
Have you tried the "Everything (not including physics debris)" flag?

**Comment by 1WHISKY** [comment]
No, doesnt work with HL2 weapons also doesnt work with the "Everything (not including physics debris)" flag

**Comment by ZehM4tt** [comment]
You could just make your own point_teleport entity with lua, heres some example:
http://codepad.org/3hA7ZdqB

**Comment by robotboy655** [comment]
Looked into this issue, its because of the fact that triggers can't collide with triggers, and weapons technically are considered triggers, meaning that they don't use vphysics to detect if a player is trying to pick one up, they use trigger bounds for this.

You can make a weapon intractable with triggers by calling ```wep:SetSolidFlags( 0 )``` on one. The problem is that they can't be picked up then.
