### ISSUE TITLE
DTextEntry:OnValueChange() is never called!

### ISSUE THREAD

**Issue by EstevanTH** [Facepunch/garrysmod-issues#2267]
Hi Rubat,

I just figured out that [DTextEntry:OnValueChange()](http://wiki.garrysmod.com/page/DTextEntry/OnValueChange) is never called.
This is a callback, probably called by [DTextEntry:OnChange()](http://wiki.garrysmod.com/page/DTextEntry/OnChange) or whatever when the content is changed.

```lua
KeyEntry.OnValueChange = function( self, strValue )
	LocalPlayer():ChatPrint( "KeyEntry.OnValueChange" ) -- debug
end
KeyEntry.OnChange = function( self )
	LocalPlayer():ChatPrint( "KeyEntry.OnChange" ) -- debug
end
```

On its side, [DTextEntry:OnChange()](http://wiki.garrysmod.com/page/DTextEntry/OnChange) works fine.

By the way, are you still working on the whole Derma engine or is it finished?

Momo.

**Comment by robotboy655** [comment]
```DTextEntry:OnValueChange``` only works:
1) Every time you type when ```DTextEntry:GetUpdateOnType()``` returns true ( Which it doesn't by default ) from  ```DTextEntry:OnTextChanged``` 
2) When you press Enter
3) when you call DTextEntry:SetValue()

```DTextEntry:OnChange``` only works:
1) Whenever ```DTextEntry:OnTextChanged``` is called

It's sort of retarded that there are both, OnChange and OnValueChange, that's why I hate Derma, it needs a lot of consistency changes, but if we are to make them, a lot of addons will break.

I have just tested it, and it does indeed work.
```
if CLIENT then
print("da")
	local frame = vgui.Create("DFrame")
	frame:SetSize( 500, 500 )
	frame:Center()
	frame:MakePopup()

	local t = frame:Add("DTextEntry")
	t:Dock( TOP )
	t.OnValueChange = function(str) print("da", str) end

end
```

**Comment by EstevanTH** [comment]
Thanks I'm going to modify the Wiki with your information! :smiley:

**Comment by robotboy655** [comment]
You do know you could've just looked up all of this information yourself, since all Derma elements are open source?

**Comment by EstevanTH** [comment]
Yeah sure, but I tried to save time. :blush:
