### ISSUE TITLE
Unable to interact with Jeep or Jalopy

### ISSUE THREAD

**Issue by kibmcz** [Facepunch/garrysmod-issues#2334]
Not 100% sure when this broke but i ran game after the latest update and I found the Jeep and Jalopy are no longer intractable as they spawn as a ghosted model (I am able to walk through them).

Game console shows "Vehicle () unable to properly initialize due to script error in ()!" after spawning them.

I tested on both local session and on my server with same result.

**Comment by robotboy655** [comment]
It is one of your addons. This is not a place to get help. Get help @ https://facepunch.com/forums/16.
You can also try validating your game.

**Comment by X-Coder** [comment]
I have the same issue on my dedicated linux server, happened after last update. Validating didn't help. Happens on jeep and every addon that using prop_vehicle_jeep as base. If you remove such a broken vehicle with undo and respawn it, the server instantly crashes with segmentation fault message.

Now I  have to test my 100 addons to see which one, if any, is causing it. Saying it is caused by addon is the easy answer. Did the update break anything the addon requires?

Whatever addons do wrong, it shouldn't cause a server to crash with a segmentaion fault message.

Don't know if its related, but I can also see the following errors in serverside console.
error:  libcurl.so: cannot open shared object file: No such file or directory
Vehicle () unable to properly initialize due to script error in ()!
httpclient.cpp (3698) : Assertion Failed: Failed writing http cache file to disk

**Comment by X-Coder** [comment]
For me, unsubscribing all the carter pack stargate addons from the servers workshop collection fixed it. Now the question remains, what could cause this segmentation fault?

**Comment by kibmcz** [comment]
Yep was same addon (only i had git version) for me... sadly the developers have disbanded and released the project to the community so no idea on the bug ever being fixed :(

**Comment by Kefta** [comment]
Where's the git for it?

**Comment by X-Coder** [comment]
Stargate-Git: https://github.com/RafaelDeJongh/cap
In workshop the addon is split in multiple parts, I tried just to remove vehicle pack 1 and 2 disable the all-addon-installed-check in lua/stargate/shared/capcheck.lua, line 53. Didn't help, so something else in the addon is causing it.

**Comment by X-Coder** [comment]
Can someone with access to garrysmod / engine sources can tell me what lua function needs to be called to trigger the "Vehicle () unable to properly initialize due to script error in ()!" error?

**Comment by X-Coder** [comment]
Traced it down to this entity meta table manipulation stuff: https://github.com/RafaelDeJongh/cap/blob/master/lua/stargate/server/entity.lua#L200, after commenting out the whole part, the problem is gone.

Anyone has an idea which part of the update could cause this thing to break? And how to fix it?

**Comment by robotboy655** [comment]
Try the Dev branch and see if it works there.

**Comment by X-Coder** [comment]
Thank you, dev branch did the trick. You know what fixed it?

**Comment by robotboy655** [comment]
Problem solved, no need to discuss this any further, expect an update.
