### ISSUE TITLE
Changing maps ingame breaks all models on new map until gmod is restarted

### ISSUE THREAD

**Issue by andrewmh2013** [Facepunch/garrysmod-issues#242]
1) Launch garry's mod and load any map
2) While ingame, change maps via console: "map cs_office"
3) All of the models that naturally appear on the new map will be invisible. Each model will throw a console error about an incorrect checksum. The models will be permanently invisible when spawned as props in any map or gamemode loaded afterwards. Static props leave a shadow on the environment. All physics collisions still seem to work.

![cs_office0003](https://f.cloud.github.com/assets/4635283/758912/fd3d27ea-e764-11e2-876a-fa3ead041fa9.jpg)

The corruptions are only fixed by quitting and restarting garry's mod. I have ended up with a variant on this bug where the props appear but physgunning one immediately crashes garry's mod to the desktop with no error notice. I haven't been able to reproduce that variant yet.

**Comment by dhantasmic** [comment]
Sorry to bring back such an old issue, but I still seem to be experiencing this or at least something similar to this.  I am able to consistently recreate it on two maps, although it happens on plenty more maps for me.  I have all games unmounted from my gmod, so that is totally unrelated.  Just from some slight research and testing, I feel like this issue is related to the models that are packed into the .bsp itself, and each map using a slightly different version of that model.  This would explain why the checksum errors appear in console because it is expecting one version of the model but is instead being given a totally different version?  Is there any way to have models fully reload on a map change instead of it relying on the models that were provided in the last map?

Here is the checksum errors for the models in the screenshot below:
```
Error Vertex File for 'props_wasteland/controlroom_desk001b.mdl' checksum -491203652 should be -52634989
Error Vertex File for 'props_wasteland/controlroom_desk001a.mdl' checksum 180873774 should be 381611185
```

The invisible tables that are failing to load in:
![image](https://cloud.githubusercontent.com/assets/2136915/15660743/4f171d42-26ae-11e6-946f-4d13ca39e891.png)

No games mounted:
![image](https://cloud.githubusercontent.com/assets/2136915/15660753/6c555d88-26ae-11e6-8834-c4e97f7717e8.png)

A simple game restart fixes all the issues, however it is still annoying to have all your players restart their games every time the map changes:
![image](https://cloud.githubusercontent.com/assets/2136915/15660784/b20e6310-26ae-11e6-8e07-3427b36fba6d.png)

This happens on a much larger scale in certain maps, sometimes with 30-40 models being completely invisible, however I just used this simple example to get my point across.  I can provide workshop links to the maps I used for this testing if you guys need it, but hopefully I provided enough information for this to get fixed if possible.

Thanks!
