### ISSUE TITLE
OSX crash

### ISSUE THREAD

**Issue by deinemudda32** [Facepunch/garrysmod-issues#2444]
local Material = Material("material")

Is crashing osx games.

**Comment by Bo98** [comment]
Gotta be more specific. It's used extensively in GMod and addons:

eg. https://github.com/garrynewman/garrysmod/search?utf8=%E2%9C%93&q=Material

and I'm still able to launch a listen server fine.

**Comment by Bo98** [comment]
You might just be seeing another eventual trigger of the OS X crash that's been unfixed for years. The memory seems to get into a corrupted state or something that anything really causes a crash as can be seen by the varying stack traces in the crash logs. Graphics-related allocations tend to take more memory which could explain why its what's most commonly seen crashing the game (#888, #2206) - and why high graphics settings crash more than low. Though there's little I can say for definite on what is the cause since I'm not a developer.

The Awesomium link often mentioned seems to be because it prints `Terminating process due to a potential for future heap corruption` whenever a malloc error occurs - but a malloc error is a bug on its own and would probably crash anyway.

If you find a way to reproduce it 100% of the time that would be great though it really isn't hard to force a crash right now anyway (eg. join a server with a fuck load of garbage addons and entities loaded, after having to download 1TB of crap).

If you think this is a different bug then post a crash log so I can compare it to others reported.
