### ISSUE TITLE
Entity:GetKeyValues()

### ISSUE THREAD

**Issue by kem008** [Facepunch/garrysmod-issues#2520]
Entity:GetKeyValues() not return targetname of the entity as the key.

I tested on all entites and I see 0 targetname for them.

I have tried on that way also

```
local test = ents.FindByClass("filter_activator_name")
for k, v in pairs(test) do 
PrintTable(v:GetKeyValues())
print(v:GetKeyValues()["targetname"])
end
```

Never returned any value for the targatname and it says nil in console.

**Comment by zerfgog** [comment]
Targetname must be a string. Invalid issue.

**Comment by kem008** [comment]
sorry
wrong paste I am using as string.

**Comment by robotboy655** [comment]
Duplicate, already reported.

**Comment by kem008** [comment]
I see no duplicate please post an url link what post I have duplicated.

**Comment by robotboy655** [comment]
https://github.com/Facepunch/garrysmod-requests/issues/39

**Comment by kem008** [comment]
it should be an issue not a request.

**Comment by robotboy655** [comment]
targetname is not a real key value, you have Entity.GetName to get it.

As for the rest of the keyvalues, I improved the handling of ```ints, chars and shorts``` ( so that they show their real values instead of 0 ), and added handling for ```booleans, color32, and vectors``` ( so that they appear and show their real values ).

Also any unhandled type will now appear with <UNHANDLED> just like GetSaveTable has.
