### ISSUE TITLE
Sandbox: Changing resoultion breaks context menu bar

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#2587]
http://puu.sh/oBbrs/876f76b3ff.jpg

I don' think anyone can work with this Error, but however if you want it:

[ERROR] lua/vgui/dmenubar.lua:74: attempt to call method 'Open' (a nil value)
  1. DoClick - lua/vgui/dmenubar.lua:74
   2. unknown - lua/vgui/dlabel.lua:218

**Comment by robotboy655** [comment]
Cannot confirm.

![image](https://cloud.githubusercontent.com/assets/3299036/14937908/81045be2-0f1d-11e6-861a-2beb8087917a.png)

I tried new game >opening context menu & spawn menu > change resolution to smaller one > nothing broke
I tried new game > opening change resolution to bigger one > context menu & spawn menu >  nothing broke

I suppose it could be one of your addons or otherwise, this is not enough info to reproduce it.

**Comment by mcNuggets1** [comment]
Maybe because I changed to window mode.

**Comment by robotboy655** [comment]
I tested in -window -noborder, and that shouldn't have any effect on Lua anyway.

Unless you provide step-by-step way to reporoduce it 100% of the time with no addons, I am not looking into it because it works flawlessly for me and probably anyone else since this is the first time I saw such report.
