### ISSUE TITLE
Make SteamID64 return 0 with singleplayer games for consistency with SteamID

### ISSUE THREAD

**Issue by ottworks** [Facepunch/garrysmod-issues#2614]
```
] lua_run print(Entity(1):SteamID64())
> print(Entity(1):SteamID64())...

] lua_run print(type(Entity(1):SteamID64()))
> print(type(Entity(1):SteamID64()))...
no value
] lua_run print(Entity(1):SteamID())
> print(Entity(1):SteamID())...
STEAM_0:0:0
```

**Comment by Kefta** [comment]
Should do this with AccountID too

**Comment by bigdogmat** [comment]
^

Also I feel like this would be more of a request than an issue. Also could potentially break older implementations. Wouldn't be an issue to change it for AccountID though

**Comment by robotboy655** [comment]
Problem with AccountID is that it doesn't return unique values for bots.

**Comment by neico** [comment]
As far as I know there aren't unique SteamID's for bots at all so of course doesn't AccountID have unique value's either. (At some point the source sdk base code contained STEAM_ID_BOT for bots which is the same thing as STEAM_ID_LAN, a non-unique value)

You could however define a special case for bots: `STEAM_BOT:0:<bot number>` and AccountID:
-1001 = first bot
-1002 = second bot
...

(using -1 doesn't work because that value stands for invalid steamid)

the same could be applied to `STEAM_LAN:0:*` (account id starting with -2001)

To make it really unique though I'd use the Nickname converted into an int. (or just use UniqueID to append it to those)

but I'd probably hide that feature behind a boolean argument to the functions to avoid parsing errors with older code (bReturnUniqueSteamID = false)

But to the actual issue:

As described [here](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/public/steam/steamclientpublic.h#L645), AccountID defaults to 0 when not uniuqe.

However SteamID64 is a bit more complicated:

As seen [here](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/public/steam/steamclientpublic.h#L624), SteamID64 will be either 0 (Invalid), 4503599627370496 (User) or 45035996273704960 (AnonUser) depending on the account type (assuming that AccountID stays 0 and Universe is 0 as well, games such as L4D use 1 for Universe so you'd need to add 72057594037927936 to the values above for that case as I'm not sure which gmod uses)

**Comment by robotboy655** [comment]
Great idea, let's have unsigned int function return negative values.

SteamID64 does return unique values for bots, and SteamID() returns a unique value ( one ) for bots.
The problem with AccountID is that if I make it return 0 for bots AND in singleplayer, there will be unexpected behavior in addons that do not expect this behavior.

**Comment by willox** [comment]
Could use the SteamID given by ISteamGameServer::CreateUnauthenticatedUserConnection?

**Comment by robotboy655** [comment]
SteamID functions return the correct value in singleplayer for the player serverside (It was already correct on client)

**Comment by FlorianLeChat** [comment]
I don't know if this is really a issue, but under a multi-run environment, all copies of the game encounter the original problem.

```
] lua_run_cl print("Original game:", Entity(1), Entity(1):SteamID64(), Entity(1):SteamID(), Entity(1):AccountID())
Original game:	Player [1][Florian #]	76561198053479101	STEAM_0:1:46606686	93213373

] lua_run_cl print("Copied game:", Entity(2), Entity(2):SteamID64(), Entity(2):SteamID(), Entity(2):AccountID())
Copied game:	Player [2][(1)Florian #]	nil	NULL

] version
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 18:09:33 Jun  2 2021 (8243) (4000)
GMod version 2021.06.03, branch: prerelease, multicore: 0
Windows 32bit
```

Is that voluntary or not?

**Comment by robotboy655** [comment]
They are not authenticated with Steam, so it would make sense for them to not have a SteamID. I don't really see a better solution. Them having the original SteamID would just complicate or break code that uses SteamIDs.
