### ISSUE TITLE
Vehicle:SetVehicleParams modifies speeds when not told to (incorrect falling back to Vehicle:GetVehicleParams() values)

### ISSUE THREAD

**Issue by Bo98** [Facepunch/garrysmod-issues#2625]
This is likely caused by `Vehicle:GetVehicleParams()` returning hammer units. Sounds like the `Vehicle:SetVehicleParams(...)` function takes from `Vehicle:GetVehicleParams()` without converting hammer units to miles per hour.

To reproduce:

``` lua
-- where veh = Vehicle entity
print(veh:GetVehicleParams().engine.maxSpeed)
veh:SetVehicleParams({})
print(veh:GetVehicleParams().engine.maxSpeed)
```

**Comment by robotboy655** [comment]
It's a problem with the engine functions really.

**Comment by robotboy655** [comment]
Ok I can fix this particular case and doing something like `data.engine.maxSpeed = nil` before `veh:SetVehicleParams` to no longer alter the speed, but I am not sure what to do about `veh:SetVehicleParams( veh:GetVehicleParams() )` since changing that would most definitely break existing addons using this.

**Comment by robotboy655** [comment]
SetVehicleParams now takes same unit as GetVehicleParams returns.
