### ISSUE TITLE
Garrys Mod sound glitches really bad when using Steam Os or Linux based pc. *Multiple Computers tested*

### ISSUE THREAD

**Issue by ComputerTech16** [Facepunch/garrysmod-issues#2630]
I just wanted to bring this up because the few people that use Steam Os play Gmod

**Comment by robotboy655** [comment]
Thanks for this very detailed report on the problem.

**Comment by ComputerTech16** [comment]
your welcome buddy

**Comment by 2E0PGS** [comment]
Yeah I have noticed the ASLA plugin glitching out. It seems to happen to me after I open either Audacity or RocketLeauge. I haven't narrowed it down to which of those two cause it. Gmod will running slower and all videos in Cinema mode will glitch audio really badly. I dont know why HL2_Linux aka Gmod is using ASLA plugin instead of Pulse. I shall do more testing to try narrow it down.

**Comment by 2E0PGS** [comment]
Seems to be if I start Gmod just after fresh boot it works fine, if I close and re open Gmod a second time the audio is double speed on Cinema mode via HTML5 and the game runs a bit slower, finally if I close and re open Gmod a third time the audio is uninteligble and game runs half speed. 

I shall post more info as I find it.

**Comment by 2E0PGS** [comment]
Yeah this issue seems to be unrelated to any other programs, simply re opening Gmod a second time causes this. I suspect its ASLA or Pulseaudio related. What is odd is that Gmod seems to hook directly into ASLA instead of going via Pulse from what I can see under Ubuntu Sound.

Running steam via terminal I saw several outputs of `ERROR:alsa_output.cc(684)] Failed querying delay: Input/output error`. 

Gmod should go via Pulse that may solve the problem.

I will try using a USB soundcard just to see if this issue persists with that.

**Comment by 2E0PGS** [comment]
Ok I found the reason Gmod and it's "ASLA plug-in [hl2_linux] was glitching. 
It was because my IOMMU / IO was not working fully.
I added some lines to my /etc/default/grub to fix my USB3 not working and this also fixed the problems I had with the audio in Gmod.

I added these following lines like so:
Edit Grub config:
sudo nano /etc/default/grub
Edit the line:
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"
Add "amd_iommu=on iommu=pt" to the end of it, line now looks like this:
GRUB_CMDLINE_LINUX_DEFAULT="quiet splash amd_iommu=on iommu=pt"
Update grub:
sudo update-grub

in the BIOS I have OMMU=Enabled, USB and USB3 controllers are enabled, EHCI handoff disabled and XHCI handoff enabled. 

I have this thread to thank for that: https://ubuntuforums.org/showthread.php?t=2188370&page=2
Also it did take a while of fine tuning and troubleshooting on my end to narrow this stuff down.

**Comment by 2E0PGS** [comment]
It seems alt-tabbing can still cause this audio delay to get messed up and cause the audio to play too fast.
Steam output is this:
```
[0314/210114:ERROR:alsa_output.cc(684)] Failed querying delay: Input/output error
[0314/210125:ERROR:alsa_output.cc(684)] Failed querying delay: Input/output error
[0314/210136:ERROR:alsa_output.cc(684)] Failed querying delay: Input/output error
[0314/210146:ERROR:alsa_output.cc(684)] Failed querying delay: Input/output error
[0314/210207:ERROR:alsa_output.cc(684)] Failed querying delay: Input/output error
```
As you can see there are more and its creating alot every few seconds in console output.

So while its alot more stable after I fixed my IOMMU issue there is still a chance it will mess up from alt-tabbing. 

I would then have to leave the Cinema room in Gmod and re enter it since the game mode this effects is Gmod Cinema.

So this seems to be some kinda playback delay sync issue.

edit: I just fixed this by using Unity Window Spread a few times to change window back and forth between Gmod and other programs. That is just a work around if it happens... not ideal. I wonder if possibly changing something in the pulseaudio config will fix this but I have checked my bitrate is matching of that of my soundcard.

**Comment by 2E0PGS** [comment]
Moving this to a new issue that I will open.
