### ISSUE TITLE
render.PushFilterMag/render.PushFilterMag need to use the render queue

### ISSUE THREAD

**Issue by willox** [Facepunch/garrysmod-issues#2633]

**Comment by roboderpy** [comment]
Is it related to weird texture filtering? Just, when i do 
```
render.PushFilterMag(TEXFILTER.POINT)
render.PushFilterMin(TEXFILTER.POINT)
--Rendering something
render.PopFilterMag()
render.PopFilterMin()
```

After that, every texture on map being filtered by "point" filter, but when *something* gets into FoV, rendering backs to normal.

![2016-06-13_19-40_c-users-roboderpy-documents-g](https://cloud.githubusercontent.com/assets/6339511/16007637/f1ef6110-319d-11e6-9713-d96f2b66094a.jpg)
![20160613194017_1](https://cloud.githubusercontent.com/assets/6339511/16007660/126e65ee-319e-11e6-8c27-417a531e0153.jpg)
![20160613194016_1](https://cloud.githubusercontent.com/assets/6339511/16007659/126d150e-319e-11e6-8d1b-5d2202309894.jpg)

And yes, i am little bitch, because drawing Lua entities in PostDraw hook. I made that because some of clients get this error when i push and pop filters in Draw hook
![ss 2016-06-09 at 03 31 10](https://cloud.githubusercontent.com/assets/6339511/16007681/331b4898-319e-11e6-9299-c16df0a2ea25.jpg)

**Comment by willox** [comment]
@roboderpy I don't think it was related, but can you test if your issue is fixed on the dev branch now? (now = an hour or so after this comment)

**Comment by roboderpy** [comment]
Will try to do so

**Comment by robotboy655** [comment]
Additionally, if you are getting that error, your code does not call render.PopFilterMag for every render.PushFilterMag - A bug on your side that you must fix.

**Comment by roboderpy** [comment]
It *does* pop
![2016-06-09_12-39_c-users-roboderpy-documents-g](https://cloud.githubusercontent.com/assets/6339511/20658548/5da5972a-b570-11e6-9bfb-cc205c3d5d2c.jpg)
This screenshot is soooooooo old, but that how filters was pushed when this error happened

**Comment by robotboy655** [comment]
A Lua error in between pushing and popping would cause same problem. I don't see any obvious problems that would cause that tho.

**Comment by roboderpy** [comment]
Now it seems to be working correctly. Thanks!
![20161128155540_1](https://cloud.githubusercontent.com/assets/6339511/20661812/3a9f2f12-b583-11e6-811a-70d1a748a8ef.jpg)
