### ISSUE TITLE
Model can't spawn

### ISSUE THREAD

**Issue by Cthutq295** [Facepunch/garrysmod-issues#2639]
I can't spawn this models from css. I think its bug
![20160527212448_1](https://cloud.githubusercontent.com/assets/10911451/15617587/e436f6e8-2449-11e6-8bfa-728867a2c436.jpg)

**Comment by robotboy655** [comment]
You can blame this commit for this:
https://github.com/garrynewman/garrysmod/commit/08d83abf4b31637fa2785bf4d4fc116d3884efc5 by @PotcFdk 

Anyway, fixed for next update:
https://github.com/garrynewman/garrysmod/commit/9abd01e5ca27efe5abe33384a7b13d9e326b7540

**Comment by PotcFdk** [comment]
@robotboy655 I don't see how my commit is to be blamed:
The ct_gsg9 model, for example, has this path: `models//player/ct_gsg9.mdl` (note the `//`).  
If you allow `//` to appear, you basically render the entire `Clean up the path from attempted blacklist bypasses` part useless, because you just introduced a new way to bypass blacklists: replacing `/` with any number of `/` such as `//`, `///` et cetera.

Are you sure, that's what you want to do?

**Comment by robotboy655** [comment]
The hook that polls whether a model can get spawned gets the cleaned up version.

**Comment by robotboy655** [comment]
I do agree that the spawnlist is at fault here as well, but changing it will have no effect on every single player who plays GMod atm, only the new installs will get updated default spawnlists.
