### ISSUE TITLE
ENT.Type not 'anim' when not set yourself

### ISSUE THREAD

**Issue by fruitwasp** [Facepunch/garrysmod-issues#2745]
### Details

The `ENT.Type` isn't auto-set on `anim`, as [described on the wiki](http://wiki.garrysmod.com/page/Structures/ENT), which causes the entity not to be created when you don't set it yourself.
### Steps to reproduce

Create an entity without setting `ENT.Type` to any type.
### Extra information

The base of the entity is the auto-set `base_entity`, the default base.

**Comment by robotboy655** [comment]
I am actually not sure if not defining Base and Type should be allowed, simply because we probably want developers to explicitly tell the engine what type of entity it is.

The Base and Type keys never had defaults in the code, and those 2 being unset will make the game silently refuse to load the entity, which I do want to replace with a message.
