### ISSUE TITLE
Loading screen protect

### ISSUE THREAD

**Issue by bossobeboss** [Facepunch/garrysmod-issues#2810]
How i can protect my loading screen? I need work on gmod browser and forbidden error for others

**Comment by bmwalters** [comment]
You could serve a PHP page that checks the browser user-agent string, and if it doesn't match Awesomium's you can abort. The string may be shared with the Chrome browser, though. Another idea is checking if the IP address of the client matches someone who is connected to your server, but that requires a fair amount of effort.

Really it's no use because any with basic HTML+CSS knowledge could easily recreate a GMod loading screen without looking at the code.

**Comment by robotboy655** [comment]
This is not a place to get help or ask questions.
