### ISSUE TITLE
Map lighting is off

### ISSUE THREAD

**Issue by ZehM4tt** [Facepunch/garrysmod-issues#2851]
### Details
Compared to the Half-Life 2 branch the lighting seems to be too dark.

### Comparison
Half-Life 2: http://images.akamai.steamusercontent.com/ugc/438364144679856404/2D9C377AFE2210E66626BB088D5280D4B2F0D93D/

Garrys Mod: http://images.akamai.steamusercontent.com/ugc/438364144679853209/4C73AB2B48CD2B7F04CD15EC04F2B1FDC9F3F556/

**Comment by robotboy655** [comment]
literally unplayable garry pls fix

**Comment by ZehM4tt** [comment]
So we are not supposed to report bugs that are actual bugs just because it doesn't affect the gameplay directly?
Glorious Logic!

**Comment by Kefta** [comment]
I took it as witty, not really caustic or sarcastic. Otherwise, he would have closed this report.

**Comment by ZehM4tt** [comment]
If thats the case then I'm sorry. However this is not exactly something one would say under normal circumstances

**Comment by thegrb93** [comment]
He's sarcastically mocking ppl that report nitpicks so yea it is childish. I don't know if the character shading pipeline in hl2 and garrysmod are the same; it might be simpler in gmod for performance. Can you do another comparison with some props in the scene so that we can see if it affects props too? You're sure all graphics settings are identical?

**Comment by ZehM4tt** [comment]
For test purposes I used the HL2 cfg to make sure all the settings are at least identical so no thats not a configuration issue.

**Comment by robotboy655** [comment]
r_radiosity 4

No idea why it was changed to 3 by default in gmod.
