### ISSUE TITLE
ACT_DRIVE_POD returns nil

### ISSUE THREAD

**Issue by shadow7483147** [Facepunch/garrysmod-issues#2894]
### Details
Found this bug looking thru the code for Armored Combat Framework
The ACT enums seems to be limited on the wiki at 2027, although the decimal value for ACT_DRIVE_POD is 2072, with the sequence number being 386.

Trying to use ACT_DRIVE_POD makes HandleAnimation request a nil value where it expects a number. Adding "or 2072" seems to be a quick workaround to it.

[ERROR] gamemodes/base/gamemode/animations.lua:148: bad argument #1 to 'HandleAnimation' (number expected, got nil)
  1. HandleAnimation - [C]:-1
   2. HandlePlayerDriving - gamemodes/base/gamemode/animations.lua:148
    3. unknown - gamemodes/base/gamemode/animations.lua:297

### Steps to reproduce
Assign "ACT_DRIVE_POD" to a scripted vehicle to be used by HandleAnimation and get inside the vehicle
( HandleAnimation = player:SelectWeightedSequence( ACT_DRIVE_POD ) )

**Comment by robotboy655** [comment]
http://wiki.garrysmod.com/page/Enums/ACT

ACT_DRIVE_POD doesn't exist.

**Comment by shadow7483147** [comment]
Shouldn't it though? As far as I can tell, it's there, but not working properly.

] lua_run print(player.GetBySteamID("STEAM_0:0:0"):LookupSequence("drive_pd"))
> print(player.GetBySteamID("STEAM_0:0:0"):LookupSequence("drive_pd"))...
386	0.1
] lua_run print(player.GetBySteamID("STEAM_0:0:0"):GetSequenceActivityName(386))
> print(player.GetBySteamID("STEAM_0:0:0"):GetSequenceActivityName(386))...
ACT_DRIVE_POD

Likewise, using player.LookupSequence("drive_pd") in place of SelectWeightedSequence seems to work, while using the actual ACT enum (undefined?) doesn't work as intended.

**Comment by Kefta** [comment]
You don't need to use SelectWeightedSequence with a seq string since you already have the sequence you want to play. With activities, there can be transition sequences that would require that function to be ran. As for ACT_DRIVE_POD, it exists nowhere in the engine. I believe GetSequenceActivityName calls upon the model for the activity name which may have some activities that are incorrect or left in by accident -- I know the CS:S grenades have a few enums that don't exist at all, for example. Unfortunately, I don't believe there's a way to fix this without recompiling.

**Comment by shadow7483147** [comment]
Gotcha, thanks.
