### ISSUE TITLE
Too many directories are being watched for auto-refresh (whitelist them)

### ISSUE THREAD

**Issue by willox** [Facepunch/garrysmod-issues#2932]

**Comment by Bo98** [comment]
This was an issue we faced when we tried to use kqueue/kevent for the OS X change monitor (to avoid Bootil requiring an OS framework). It would hit the file descriptor limit since kqueue/kevent keeps files open unfortunately. FSEvents doesn't have this limitation but required linking CoreServices.

The downloads folder in particular can be a bit of a killer.

**Comment by Jake3231** [comment]
Hmm..  Is it difficult to implement CoreServices and FSEvents.

**Comment by Bo98** [comment]
Oh, at the moment OS X/macOS does not even have any form of change monitoring and whether FSEvents is implemented or not does not impact on the number directories watched. That is GMod's fault and affects all platforms.

What I meant is that in an attempt to add change monitoring for OS X a while back, we found that FSEvents was the only way to do so because GMod is _already_ attempting to watch all directories (which currently does nothing on OS X). Even if this was fixed, FSEvents is still the best solution for change monitoring on OS X. My comment was really a "yes, I have noticed this and it really should be fixed".

On the side note about implementation, no it isn't difficult to code (I've already done it).

**Comment by Jake3231** [comment]
Okay. If it can be implemented, then could Gmod's current change checking be disabled, and the more optimized FSEvents implementation be put in place?

**Comment by Bo98** [comment]
There is currently no change monitoring whatsoever in GMod for macOS. So it would be adding change monitoring rather than replacing the implementation. There were some experiments done before with kevent/kqueue etc. but those are no longer in the game, so there's nothing to disable anymore. Change monitoring is currently only implemented for Windows and Linux. What I meant by "GMod already attempting" was that the code that starts change monitoring is run on all platforms, but because there is no macOS implementation, it does nothing. When we experimented with kqueue/kevent, it was as simple as adding the implementation to get it working. Through this, we discovered the shortcomings of how GMod handles things as it is telling the implementation to watch all directories in the garrysmod folder.

Will change monitoring ever be added for macOS? I have no idea as all I got was silence after the initial discussions - afaik there's still a (small) memory leak in Bootil's FindFiles function which affects all platforms which I discovered at the same time. But this is getting off-topic from the issue now.

**Comment by UAVXP** [comment]
I have one question: we run 3 GMod servers on one machine, and one of them (depends on when the first launch was) refuses to Lua autorefreshing. Is this issue responsible on this strange behavior?
All of those servers are at different and independent directories.

**Comment by uRandomAlex** [comment]
@UAVXP What gamemode your strange behaiving server is using?

**Comment by UAVXP** [comment]
@uRandomAlex Sandbox, DarkRP and Fretta
For example, if the first started servers was Sandbox and Fretta, then DarkRP's autorefresh will not work. Even if we have disabled some of first servers and restart them - DarkRP autorefresh will not work

**Comment by uRandomAlex** [comment]
@UAVXP DarkRP has built in "simplerr" library which simplifies error messages but conflicts with auto-refresh. You can't just disable or remove it because of FPTje :/

**Comment by Bo98** [comment]
You can disable it, but only on a per file basis.

By default, this only affects addons with the same directory structure as the DarkRPModification addon.

**Comment by UAVXP** [comment]
@uRandomAlex @Bo98 I know about Simplerr, and I have properly disabled it already via core DarkRP files. The thing isn't in Simplerr, I can tell for sure.

**Comment by uRandomAlex** [comment]
@UAVXP Have you heard "DarkRP Corefiles" song? Here ya go: http://corefiles.darkrp.eu/

**Comment by UAVXP** [comment]
@uRandomAlex Don't care. Better if Falco will fix his "shit" called Simplerr and implement disabling this "cool modern feature". Anyway, this is off-topic, so... The problem with autorefreshing is still here.

**Comment by Kefta** [comment]
@urandomalex the song was cute the first ten times I heard it, but now, it only makes me want to edit corefiles.

**Comment by uRandomAlex** [comment]
@UAVXP He made a decision between making life of server owners easy or leaving everything as it is without hurting developers.

**Comment by UAVXP** [comment]
@uRandomAlex This feature don't make my life easier since it brokes autorefresh, and also must be configurable, I think.

**Comment by robotboy655** [comment]
We are now only watching `lua` and `materials` folders.
