### ISSUE TITLE
GM:PhysgunPickup() not being called correctly for all entities I.E Players.

### ISSUE THREAD

**Issue by darkislight** [Facepunch/garrysmod-issues#3006]
### Details
the GM:PhysgunPickup() function only gets called on certain types of entites. Im unaware this is intentional so i thought i would alert you to it. For example if a you physgun a player the function is not called. However on a prop it is.

### Steps to reproduce
Create a GM:PhysgunPickup() subroutine that prints a debug message and then try picking up different entity classes with the phygun.

**Comment by robotboy655** [comment]
![image](https://cloud.githubusercontent.com/assets/3299036/21654363/ddabf648-d2bd-11e6-9185-fb27bacaa979.png)

One of the hooks in your game is "capturing the player class", i.e. a hook.Add( "PhysgunPickup", "", ... ) returns a value, blocking the event from going through to GM:PhysgunPickup. Hooks are called before their GM:*, this is by design.
