### ISSUE TITLE
RunString error : Add more information

### ISSUE THREAD

**Issue by Sachha** [Facepunch/garrysmod-issues#3011]
Hi,

When a RunString fail, it doesn't print which script is in cause (workshop or folder)

It's just a message like this one : 
[ERROR] RunString:21: ')' expected near 's' 1. unknown - RunString:0

I sugggest to add from where this RunString was run in the error message if it possible.

Thanks

**Comment by biorisk2** [comment]
I have noticed this before, I believe runstring is too strong to be used at all, you can runstring code from a URL, meaning at any moment you can backdoor an addon, or server, or worse, all servers.

I agree more debugging messages should be given from runstrings

**Comment by bigdogmat** [comment]
> I have noticed this before, I believe runstring is too strong to be used at all, you can runstring code from a URL, meaning at any moment you can backdoor an addon, or server, or worse, all servers.

This issue and what you're describing have nothing to do with each other. This issue is about what happens when `RunString` attempts to execute code that produces an error.

Also, `RunString` isn't any _stronger_ than having plain Lua code in the file, it just allows a person to change what code might be executed as well as attempt to hide that code. Figuring out what code is being executed may be a bit harder, although still very easy as it'd just be detouring `RunString`.

**Comment by markusmarkusz** [comment]
Maybe someone should add a stack trace (if this is possible) if an error occurs or at least, as the creator of this "issue" already suggested, the information where RunString was executed.
Sometimes it would be really useful.

**Comment by Kefta** [comment]
Would be solved by https://github.com/Facepunch/garrysmod-requests/issues/1093

**Comment by robotboy655** [comment]
Should display full stack trace now, let me know if it causes any problems.
