### ISSUE TITLE
RPG Missile slowing down while moving through water

### ISSUE THREAD

**Issue by panica23** [Facepunch/garrysmod-issues#3063]
RPG Missile slowing down while moving through water
[YouTube](https://youtu.be/Vxtj10Q43-0)

**Comment by Kefta** [comment]
This is intentional. The crossbow bolt and frag grenade does this as well.

**Comment by thegrb93** [comment]
It should accelerate up upon reentering the atmosphere, but who cares and why fix something that kind of funny and cool.

**Comment by Kefta** [comment]
@thegrb93 It should also eventually run out of fuel for propulsion, but I suppose this isn't supposed to be the most realistic interpretation. It seems Valve copied the water-slowing effect from all of their explosive entities since the CS:S grenades have the same property, as well, but obviously, those wouldn't re-enter the atmosphere since they are only affected by gravity, which can explain why they never bothered to change the RPG's acceleration.

**Comment by robotboy655** [comment]
not a problem
