### ISSUE TITLE
Linked workshop collections fail to mount

### ISSUE THREAD

**Issue by AbsentLight** [Facepunch/garrysmod-issues#3115]
The issue I am encountering is identical to the one which was resolved (/marked closed) in [Nov 2016 #646](https://github.com/Facepunch/garrysmod-issues/issues/646)

A collection is made which has one or more collections of normal GMOD addons as its contents. This parent collection is then set to load using the GMOD dedicated server command line parameter '+host_workshop_collection'.

`./srcds_run -game garrysmod +map gm_construct +maxplayers 16 +gamemode terrortown  +host_workshop_collection 898910142 -authkey [Valid Auth Key]`

## Server Console Log

[Pastebin Link](https://pastebin.com/sSyWWcBE) to the relevant section of the DS console output

## Steps to reproduce

- Create a Workshop Collection and add one or more valid addons
- Create a second Workshop Collection and add the first collection to it.
- Launch a GMOD dedicated server (Stable Release) with the parent collection set to be loaded
- Addons are not mounted from linked collections - Error messages in server log

**Comment by robotboy655** [comment]
Already fixed in the Dev branch.

**Comment by AbsentLight** [comment]
Thank you - the update date is helpful

**Comment by Chrisly3ear** [comment]
It's April 17, my server got the update, but linked collections still won't mount. Was the fix for this included in the latest update or is it still in the pipeline?

**Comment by AbsentLight** [comment]
I have updated my server to stable branch and workshop collection linking
appears to work for a depth of one (A collection of collections of addons).
I haven't tested greater depths.

Also, are you subbed to dupes, saves, or demos? Those break addon downloads.

**Comment by Chrisly3ear** [comment]
It is also working for me. I was under the impression my server was up to date, but it wasn't. Restarted and everything works fine now.
Only thing you need is a LUA script that registers all addons as download by the client. 

I found the attached script in the facepunch forums. Just put it in lua/autorun/server/auto_add_addons.lua and it should work.
[auto_add_addons.txt](https://github.com/Facepunch/garrysmod-issues/files/926754/auto_add_addons.txt)

Chris

P.S.: I deleted my comment because it's working, but you seem to have replied to the email ;-)
