### ISSUE TITLE
physgun_beam is created and shortly removed in holster

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3125]
Testing:
- Take out physgun
```
lua_run hook.Add("OnEntityCreated","",function(e)print(e)timer.Simple(0.1,function()print(e)end)end)
```
- Switch to a different weapon

Output:
```
Entity [123][physgun_beam]
[NULL Entity]
```

**Comment by robotboy655** [comment]
It feels like that because OnEntityCreated is pretty bad, it is called when the Lua table for an entity is created, not when the actual entity is created.

Here's an example:
![image](https://user-images.githubusercontent.com/3299036/51253823-1d66fe80-19a8-11e9-818a-c572612d5790.png)

As you can see OnEntityCreated for env_sprite(trail) on server is called only after those entities are referenced in Lua and not a moment too soon.

Similar issue: https://github.com/Facepunch/garrysmod-issues/issues/1371
