### ISSUE TITLE
SWEP/SENT table isn't implemented by OnEntityCreated

### ISSUE THREAD

**Issue by Kefta** [Facepunch/garrysmod-issues#3127]
Less of a bug and more of a design oversight.

Testing:
```
hook.Add("OnEntityCreated", "TestEntityTableImpl", function(pEntity)
	print(pEntity, "created")
	PrintTable(pEntity:GetTable())

	timer.Simple(0.1, function()
		print(pEntity,"post-created")
		PrintTable(pEntity:GetTable())
	end)
end)
```
- Spawn a SWEP or SENT

**Comment by Kefta** [comment]
Related to https://github.com/Facepunch/garrysmod-issues/issues/1899

**Comment by CornerPin** [comment]
Still happens on the client side.

**Comment by dhkatz** [comment]
Can confirm, this still happens to clients.

Adding a 0 second timer works but seems hacky.

**Comment by LeQuackers** [comment]
When do entities setup lua stuff? Is it in ```C_BaseEntity::Spawn```?

**Comment by LeQuackers** [comment]
After some tests it looks like the lua stuff is setup/called way after ```C_BaseEntity::PreDataUpdate``` (the next frame after ```GM:NetworkEntityCreated```?) given that the entity's model is already set on the client. Initializing the lua in [```CBaseEntityList::OnAddEntity```](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/shared/entitylist_base.cpp#L265) looks like it might work because it's called before network data updates.

Also, where are ```GM:OnEntityCreated``` and ```GM:NetworkEntityCreated``` called? I don't think it's in ```CBaseEntityList::OnAddEntity``` because ```Entity:GetCreationTime``` returns non zero; which suggests they're being called after [```C_BaseEntity::Init```](https://github.com/ValveSoftware/source-sdk-2013/blob/master/mp/src/game/client/c_baseentity.cpp#L1089-L1095).

```
hook.Add("NotifyShouldTransmit", "test", function(ent, transmit)
	print("NotifyShouldTransmit", ent, ent:GetModel(), ent.SetupDataTables, CurTime())
end)

hook.Add("OnEntityCreated", "test", function(ent)
	print("OnEntityCreated", ent, ent:GetModel(), ent.SetupDataTables, CurTime())
end)

hook.Add("NetworkEntityCreated", "test", function(ent)
	print("NetworkEntityCreated", ent, ent:GetModel(), ent.SetupDataTables, CurTime())
end)

if SERVER then
	concommand.Add("github_test", function(ply, cmd, args)
		local model = "models/combine_turrets/floor_turret.mdl"
		
		local ent = ents.Create("github_test")
		ent:SetModel(model)
		ent:Spawn()
	end)
end

local ENT = {}

ENT.Type = "anim"

function ENT:SetupDataTables()
	print("SetupDataTables", self, self:GetModel(), self.SetupDataTables, CurTime())
end

function ENT:Initialize()
	print("Initialize", self, self:GetModel(), self.SetupDataTables, CurTime())
end

scripted_ents.Register(ENT, "github_test")
```
![image](https://user-images.githubusercontent.com/16133099/114911689-3f50c500-9ded-11eb-8fcc-7d9dfb097ca4.png)

**Comment by robotboy655** [comment]
> Initializing the lua in CBaseEntityList::OnAddEntity looks like it might work because it's called before network data updates.

And how do you expect the Lua to initialize without knowing what class to initialize?

Anyway, this should be fixed on Dev beta.

**Comment by LeQuackers** [comment]
Fuck. At the time it looked like it would work because the c++ class is initialized by then, but I forgot that the lua class is a network variable.

**Comment by robotboy655** [comment]
Had to rollback the fix for this, as this just causes more problems that it fixes.
