### ISSUE TITLE
Game gets stuck when certian addons are enabled 

### ISSUE THREAD

**Issue by jbuug** [Facepunch/garrysmod-issues#3141]
![crash](https://cloud.githubusercontent.com/assets/12882548/25094358/a3dcc49a-234b-11e7-812f-bd3b4ca7c033.PNG)
this has started happening recently. game gets stuck at Initializing Game Data CPU Usage fluctuate, disk usage drops, and starts to become a ram hog

Only Happens On Certain Maps

**Comment by willox** [comment]
Is this causing the game to completely freeze so that you can't press the cancel button? If that's the case I should be able to figure out what is happening from a dump if you're willing to send one my way.

Follow "Method 1: Use Task Manage" in the guide linked at the bottom of this post to create one. 

You can send the dump file to willox@facepunchstudios.com. There may be some data you wouldn't want to upload publicly inside.

https://support.microsoft.com/en-gb/help/931673/how-to-create-a-user-mode-process-dump-file-in-windows-vista-and-in-windows-7.

**Comment by jbuug** [comment]
here is the thing it dosent even make a crash log it just sits here

**Comment by jbuug** [comment]
sending it to you now

**Comment by jbuug** [comment]
Just sent the file now if you have any trouble contact me back

**Comment by jbuug** [comment]
issue caused by addon

**Comment by jbuug** [comment]
thank you willox for helping me out you get a pepe approval
