### ISSUE TITLE
Entity:FireBullets doesn't work server side.

### ISSUE THREAD

**Issue by Sithly** [Facepunch/garrysmod-issues#3152]
Can't get it to run server side. Wiki says it's shared.

I had this working originally:
https://pastebin.com/VZjCh0U7

It only works if I change "SERVER and IsFirstTimePredicted()" to "CLIENT and IsFirstTimePredicted()".
I tested with different tracers as well.

Perhaps something has been changed, if so please update wiki.

**Comment by Kefta** [comment]
Just tested on a plain weapon with nothing but your code in single-player and it worked fine, but your code is improperly predicted. FireBullets works fine server-side only, but you won't see the explosion or impact effects due to SuppressHostEvents automatically being applied to Primary/SecondaryAttack in multi-player. You should be calling FireBullets shared to make it appear correctly on both the local player and for others. Also, read this page on how to use IsFirstTimePredicted correctly: https://wiki.garrysmod.com/page/Prediction

Here's the revised code: https://pastebin.com/ey5qewtb

In the future, please use https://facepunch.com/forumdisplay.php?f=65 for issues with your code.
