### ISSUE TITLE
NextBot leaking debug.getregistry entries

### ISSUE THREAD

**Issue by Python1320** [Facepunch/garrysmod-issues#3222]
Run the code below on server. Spawn Garry's example nextbot. It starts printing that there are registry allocations when the NPCs run around. Never deallocations.
```lua
local r=debug.getregistry()
local prev=#r
timer.Create("a",1,0,function()
	local a=#r
	local d=a-prev 
	if d~=0 then
		print(d)
		if d>0 then
			for i=prev,a do
				print(">",r[i])
			end
		end
	end
	prev=a
end)
```
@SpiralP has possibly narrowed it down to somewhere near the function ```path:Compute( )```. It's not the function itself, most likely, as the garbage does not increase during that function call, but right after it. As we are observing only continously increasing count of registry entries it could literally be anything, but nextbots seem to trigger it.

Example output:

```lua
38
>	0
>	3559
>	3566
>	3565
>	3563
>	0
>	0
-- repeating zeroes ---
>	0
>	3596
>	0
>	3352
>	3597
>	0
´´´

**Comment by neico** [comment]
those aren't registry entries per se, numeric keys in the registry are part of lua's reference system, which are only used from application code that invokes the C API

when a reference is deleted the entry isn't deleted, instead the amount of references at the time of deletion is stored there instead (and _R[0] always has the index of the next free reference slot)

Example:
```lua
0 = 5
1 = thread
2 = global
3 = userdata
4 = registry
5 = 6
6 = 7
```

so you are right with one point, those zero's shouldn't be there, unless gmod changed the reference system to always fall back to the zero counter (the thing is that lua replaces the zero entry with the value of the entry it's going to place a new reference at, so that zero points to the next free slot again)

**Comment by robotboy655** [comment]
Should be fixed on Dev.
