### ISSUE TITLE
npc:RemoveMemory() / npc:ClearEnemyMemory() in OnEntityCreated freezes/crashes server

### ISSUE THREAD

**Issue by yupi2** [Facepunch/garrysmod-issues#3391]
### Details
NPCs (at least Combine) when having their memory removed freeze or crash the server.
Tested on DarkRP srcds, Sandbox singleplayer, and Sandbox srcds.

### Steps to reproduce
In `lua/autorun/server/break.lua`
```
hook.Add("OnEntityCreated", "thing", function(ent)
	if ent:IsNPC() and ent:GetClass() == "npc_combine_s" then
		ent:RemoveMemory()
	end
end)
```
then spawn a Combine.

`npc:ClearEnemyMemory()` also seemed to crash if you put that in the hook instead.

**Comment by robotboy655** [comment]
As far as I can tell, RemoveMemory is a mistake and shouldn't exist, it's only in-engine usage is as a deconstructor for the memory, hence why it crashes no matter what. It will be removed from the game.

I cannot confirm ClearEnemyMemory crashing the game, and this is what you are supposed to used instead of RemoveMemory as far as I can tell.
