### ISSUE TITLE
surface.Draw* functions casting arguements to int

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#3433]
surface.* functions no longer allow subpixel rendering. render.* functions work though.

Sample code:
```
lua_run_cl hook.Add("HUDPaint","A",function() surface.SetDrawColor(255, 0, 0, 255) surface.DrawRect(50+math.sin(CurTime()), 50, 50, 50)  surface.SetDrawColor(0, 0, 255, 255) surface.DrawRect(100+math.sin(CurTime()), 50, 50, 50) end)
```

**Comment by robotboy655** [comment]
This was always the case, there's no such thing as half a pixel.

**Comment by robotboy655** [comment]
Which is why I always recommend to ceil or floor any non static value that is fed to width/height or position of vgui/huds.

**Comment by thegrb93** [comment]
There IS such a thing as half pixel in directx. I'm reluctant to believe that this is old behavior because I would have noticed it before. Now I have to migrate the 'surface' library of starfall to 'render' since it doesn't work anymore.

**Comment by thegrb93** [comment]
Not to mention the surface draw functions work in 3D context with transformed coordinates which tells me this is a completely unneeded restriction casting/restriction.

**Comment by thegrb93** [comment]
If it is completely impossible to fix, then I'll use a 3D context with render.* functions, but it seems like just another workaround to have to deal with.

**Comment by robotboy655** [comment]
The only changes to surface library since 2014 were made to fonts. Nothing else was changed in it for 4 years.

https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/sp/src/public/vgui/ISurface.h#L142
If you look here, you will notice all the functions take ints, not floats.

DrawFilledRect is surface.DrawRect, DrawOutlinedRect is surface.DrawOutlinedRect

**Comment by thegrb93** [comment]
Okay, then I'll at least document it on the wiki
