### ISSUE TITLE
Ladder gravity issue

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3461]
### Details
When using a ladder your gravity gets reset.
There is no hook or function to prevent this.

### Steps to reproduce
Use a ladder after getting set a different gravity than 1

**Comment by robotboy655** [comment]
Assuming http://wiki.garrysmod.com/page/Entity/SetGravity?

**Comment by Kefta** [comment]
It's due to [this](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/shared/gamemovement.cpp#L2897) and it affects all ladders. I've looked through the rest of the movement code and it is unneeded since all movement-related calls to GetGravity treat the value as 1 when it is set to 0 ([example](https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/shared/gamemovement.cpp#L3055-L3058)).

**Comment by robotboy655** [comment]
Solved

**Comment by mcNuggets1** [comment]
Thanks for fixing it! <3333
