### ISSUE TITLE
resource.AddFile does not validate server-side resources when adding files with sv_downloadurl

### ISSUE THREAD

**Issue by travis575757** [Facepunch/garrysmod-issues#3587]
### Details

In the server.cfg when using sv_downloadurl to retrieve resources from a remote http server resource.AddFile requires that files in the http server are also present in the gameserver (I'm not sure if this is intended behaviour).  Along with this the files on the server do not have to match the ones on the http server.  For example, I could have an image on the http server in materials/image.png and a emtpy text file called materials/image.png in the game server directory.  With sv_downloadurl set the image on the http server will be downloaded, regardless of the fact that it is a different file than the one present on the game server.

If this is intended behavior, the wikipedia seems to lack mention of this. 

### Steps to reproduce
Tell us how to reproduce the problem, step by step

1. Set up a http server for your gmod server and set the sv_downloadurl. make sure sv_allowdownload is set to 0.
2. Take an image, put it on the server in yoursite.com/fastdldirectory/materials/img.png.
3. Take an arbitrary file, name it img.png and put it in materials/img.png in your game directory.
4. in your game server add a lua file with resource.AddFile("materials/img.png") in your lua/autorun/server/thescript.lua
5. join the server, your client will download the image on the http server.

Please refer to the following forum post for further information: https://forum.facepunch.com/f/gmodhelp/btjtu/Does-sv-downloadurl-require-resource-AddFile/1/#postcvtyis.

**Comment by robotboy655** [comment]
I guess you could call this intentional. 

There is no mechanism set in place to test if the files on the FastDL server are actually the same as in the game folder due to the FastDL server being a completely separate entity.

Do you really want your game server download up to 8000 files every time you start it? And wait for the downloads to finish before adding the file to the download list making everyone who joins in between that time period fail to download the files you want them to download? This would be especially stupid for map files.

**Comment by meepen** [comment]
You don't really have to download them completely, you can HEAD request the
URL to see if it exists

**Comment by robotboy655** [comment]
The issue was about validating if the files are the same, not if they simply exist or not.

**Comment by thegrb93** [comment]
resource.AddFile verifies whether it should add the file or not based on the existence of the file on the server.
