### ISSUE TITLE
particle system problems

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-issues#3607]
hey, say is there a way that we can do anything about this error?

"Attemped to precache unknown particle system XYZ" it happens with standard hl2 stuff but also with modded (addon) stuff as example you can sub the TFA base and lets say the csgo weapons the thing is the weapons etc work everything is perfect but your dev console is getting spammed with this error.

now if everything works fine can we hide this error in the next update or is it a real bug? i mean if it is normal why does the dev console show it?

**Comment by robotboy655** [comment]
This happens due to calling ```PrecacheParticleSystem``` on the server. This makes the servers tell the clients to precache the particle effect via networking, but when loading into singleplayer (probably multiplayer too), Lua on client at that point hasn't started yet, meaning the .pcf file is not loaded yet via ```game.AddParicles``` so the game client cannot find the particle and throws that error.

This can be completely solved by mod developers by just **not** calling ```PrecacheParticleSystem``` on the server, in my tests this doesn't create any problems.

To explain a bit more, ```PrecacheParticleSystem``` precaches/loads all the materials and whatnot necessary to for the particle, ```game.AddParticles``` loads the .pcf file and stores it in memory. PrecacheParticleSystem is more expensive which is why it is only done for particles that are absolutely needed on level load (for example you don't want to precache all particle materials for all maps, if the map you are on doesn't even have any particle effects on its own)

Removing the warning is not an option because that will hide real problems when the mod developer misspells the particle name, etc., when the particle actually doesn't exist.

**Comment by Dimantio** [comment]
I've tried your method, couldn't get my particle to work until I called it server side as well.
