### ISSUE TITLE
Gravity gun networking issues

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3630]
### Details
The gravity gun is able to pick up gmod_buttons clientside (serverside they aren't picked up) if they aren't freezed, even tho they are weld to the world.
Also if you switch from the gravity gun to a different weapon (with a serverside method) while having something picked up, the entity will float in the air.

### Steps to reproduce
Spawn a button.
Use gravity gun on it.

**Comment by robotboy655** [comment]
The button IS being picked up on the server, it's just that the weld overcomes the gravity gun.

You can test this yourself with a `bot` + `bot_mimic 1`. Weld 3 or more barrels in a sequence like so: (World <-> Barrel <-> Barrel <-> Barrel) if you try to pickup the barrel which has the "furthest away weld from world", i.e. the rightmost barrel on the diagram, the bot will be able to easily manipulate the barrel, or any buttons on it.

The issue you are experiencing is just clientside prediction not predicting the weld, because it doesn't know about it since constraints are serverside only. Not something that I am interested in looking into in all honesty.

`SetActiveWeapon()` with gravgun holding a prop should be fixed, other functions already handle this properly by not switching like expected.
