### ISSUE TITLE
Crash on game.CleanUpMap()

### ISSUE THREAD

**Issue by Dimentio** [Facepunch/garrysmod-issues#3637]
### Details
I guessing the game is trying to remove particles that no longer exist when the map is reset. It's only affecting the client and not all the clients. On a server with 32 players for example only 12 might crash on that particular reset. It's kind of rare.

Here's the crashdump: https://puush.qcgames.org/kKe9.mdmp

### Steps to reproduce
Not exactly sure. It's happening on game.CleanUpMap(). You need particles in the map. I'm using particles from [this addon](https://steamcommunity.com/sharedfiles/filedetails/?id=784597026)

**Comment by Dimantio** [comment]
I've done more test since, trying to reproduce it on my test server which shares the same addons and everything and I couldn't get any results. But from my test I believe the particles are most likely not related to the issue anymore and I can't exactly figure what it might be. The crash on one of my servers suddenly stopped and then suddenly one of my other server started having it so I am very lost and starting to suspect it might be an exploit or something. I can't grasp my mind on why it's not affecting everyone and why it's only happening a short while after game.CleanUpMap(). I checked the crashdumps of the players who got the crash and they are all the same.

**Comment by robotboy655** [comment]
The crash is related to particles, C_FireSprite specifically from the dump you provided, which I think is used by the `_firesmoke` entity.

**Comment by Dimantio** [comment]
Could Entity:Ignite() cause this?

**Comment by Dimantio** [comment]
The crash happened on the latest gmod update but the crash dump looks different:
https://puush.qcgames.org/wY2C.mdmp

**Comment by robotboy655** [comment]
It could be caused by anything that spawns _firesmoke entity (the crash is caused when the entity is removed), this includes any mods that spawn env_fire, entityflame or _firesmoke or those entities being on the map, Entity.Ignite also might cause this.

How often does this crash happen for you? You might wanna try adding those 3 entities into game.CleanUpMap's exceptions and seeing if the crashes are reduced/gone, but a way to reproduce this will be most helpful in actually fixing this.

**Comment by Dimantio** [comment]
The crash is random which is why i've been struggling so hard to reproduce it.

I've tried adding _firesmoke to the filters but that didn't help, then I made it so env_fire and _firesmoke are deleted on creation in OnEntityCreated that also didn't do it somehow. I checked on the client to be sure and yeah they don't see/receive them anymore...

I also noticed that in some cases the crash happen a few minutes/seconds after game.CleanUpMap altho rarer. It's been plaguing my server for awhile and tend to crash half the clients on it. I've been trying to find a correlation but to no avail. 

I feel like it's caused by a player because the crashes seems to follow a player's routine. I often sometimes have one in the morning, 2 in the after-noon or none at all for a whole day then very next day we might get 0 in the morning and 3 in the after-noon. Also two of my other servers are crash-free and they are exact copies, one of them was having the issue but stopped randomly ever since 14th October.

My latest changes was to add loggings to many events in the server in an attempt to find a correlation that might help to reproduce the crash.

**Comment by Sophie-bear** [comment]
Not sure if it helps at all, but here's a relevant crash dump.

https://drive.google.com/file/d/1bcgG815SJTAQeSV-aFXWmscBrGVUMSlC/view?usp=sharing
[dace6d8a-8f71-4677-b793-e962b940ff4d.txt](https://github.com/Facepunch/garrysmod-issues/files/4943248/dace6d8a-8f71-4677-b793-e962b940ff4d.txt)

**Comment by Dimantio** [comment]
This year yet again I encounter this issues with entities that use particles, here are two crashdump with x64 bit gmod. Happen to game.CleanUpMap()
[crashdumps.zip](https://github.com/Facepunch/garrysmod-issues/files/5315136/crashdumps.zip)

**Comment by WinterPhoenix** [comment]
Please read above. A quick fix is this:
```lua
game.CleanUpMap(false, {"env_fire", "entityflame", "_firesmoke"})
```

Read the [Documentation on `game.CleanUpMap`](https://wiki.facepunch.com/gmod/game.CleanUpMap) for more info

**Comment by Dimantio** [comment]
I've tried that and still gotten it, I've got this in maps without any fire entities as well I think it's something else related with particles.

**Comment by robotboy655** [comment]
I haven't heard of this crash in a long while, so I am assuming it is solved. If it isn't, let me know and provide crash dumps.
