### ISSUE TITLE
Entity:TakeDamageInfo invalid erroring

### ISSUE THREAD

**Issue by eLeCtrOssSnake** [Facepunch/garrysmod-issues#3661]
### Details
If you will use TakeDamageInfo inside a ENT:Touch( Entity entity ) and try to kill player for example with this thing it will throw an error when player is dead. Check for valid or alive doesn't work, even timers  too. So that happends only with Damage function what uses CTakeDamageInfo:
- http://wiki.garrysmod.com/page/Entity/TakeDamageInfo
- http://wiki.garrysmod.com/page/Entity/TakePhysicsDamage

For example killing player with ENT:Touch() and Entity:TakeDamage() is ok but i can't do those cool damage effects.

Thats what console says with my example:
[ERROR] gamemodes/base/gamemode/player.lua:205: Tried to use a NULL entity!
  1. GetClass - [C]:-1
   2. unknown - gamemodes/base/gamemode/player.lua:205
    3. TakeDamageInfo - [C]:-1
     4. unknown - lua/entities/ent_github_issue.lua:35

Warning! A net message is already started! Discarding...

Example entity - https://pastebin.com/tx4wCy1f

### Steps to reproduce
I don't have gmod source code))) so i can't exactly point how to fix. CTakeDamageInfo processing seems to be not good.

**Comment by bigdogmat** [comment]
https://github.com/Facepunch/garrysmod/blob/394ae745df8f8f353ea33c8780f012fc000f4f56/garrysmod/gamemodes/base/gamemode/player.lua#L205 is where the error is coming from. It's because the attacker is null. I'm assuming you need to assign an attacker on the `DamageInfo`.

Also, `DamageInfo` is a global instance, settings those values only once isn't enough.

**Comment by eLeCtrOssSnake** [comment]
Oh thanks, that works. Like its not pointing me right. So okay closing
