### ISSUE TITLE
64-bit CUtlLinkedList Overflow

### ISSUE THREAD

**Issue by Raox2** [Facepunch/garrysmod-issues#3666]
### Details
Possibly related to particles. There was a similar crash that occurred a significant while ago when particles/emitters weren't getting cleaned up. I can't be sure on this, but it is definitely related to 64 bit because this only happened to the subset of 64 bit players on the server.

https://i.imgur.com/AOboQ0h.png

There's no crash log for this.

### Steps to reproduce
Possibly create a lot of particles/entities/effects at once. That's the situation it occurs - apart from that, no reliable way to do it. I'll investigate further.

**Comment by Raox2** [comment]
Got a crash dump for you from a player: @willox 

https://dl.dropboxusercontent.com/s/e3lj3g2a1g8sgyr/4f22be00-08a6-4c9d-8748-87a824d9b2ad.dmp

**Comment by willox** [comment]
This seems to be projected textures trying to create too many shadow decals. It could just be that you had a lot of stuff going on, or a failure in the code to clean up the shadow decals. Have you noticed this same issue recently?

**Comment by Raox2** [comment]
I don't know. There have been some crashes recently on the server by particular clients, but since this issue is kinda old, I no longer know if it would be related. I've been asking them to send you crash dumps, I'd check if you've received any recent ones that are similar. If not, maybe close it for now.

**Comment by besenyei** [comment]
It might be caused by the bonemerged classes in the zombiesurvival gamemode, I've noticed sometimes their shadows break out of their bounds, stretch out or become giant.

Too many bonemerged classes in use likely increases the chance of an overflow crash.

Despite the fact the gamemode disables these shadows with shadow_control, the issue still happens.

I don't think this issue is exclusively a x86-64 branch issue, as there is a chance it can happen on all of them.

**Comment by willox** [comment]
This was changed to emit a warning rather than crash (the same as the non-beta branches) a long time ago now. It's not the best solution, but it's how the non-beta branches have been doing it for years.
