### ISSUE TITLE
HTTP requests on private networks

### ISSUE THREAD

**Issue by h3xcat** [Facepunch/garrysmod-issues#3684]
### Details
This vulnerability was somewhat known within the GMod community for quite some time, I just wanted to bring more awareness.

Allowing clientside code to access private networks could possibly allow an attacker to gain access to clients' network devices, such as routers and modems. Furthermore, these devices frequently contain default password, and have outdated firmware.

The issue is especially relevant with existing addons such as: mediaplayers, custom sprays, starfall, and pac; where any user on a server could make http requests on any other users.

I'd suggest blocking requests for following subnets: `10.0.0.0/8`, `172.16.0.0/12`, and `192.168.0.0/16`. Other libraries and functions should also be taken into account.

[Somewhat relevant effects of different attack, the vulnerabilities section specifically](https://medium.com/@brannondorsey/attacking-private-networks-from-the-internet-with-dns-rebinding-ea7098a2d325#9ec8)

[Avoid Consumer Routers](https://routersecurity.org/othersgripeonrouters.php)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/2304691/50048264-39f7da00-007c-11e9-9d00-a91ba2506ea9.png)
![image](https://user-images.githubusercontent.com/2304691/50074934-4ec69180-0192-11e9-9526-2759f74d73ea.png)
![image](https://user-images.githubusercontent.com/2304691/50075099-ceecf700-0192-11e9-8379-c2319ced9991.png)

**Comment by thegrb93** [comment]
What if I'm hosting a server on my network and want garrysmod to be able to access it?

**Comment by edgarasf123** [comment]
I can't really think of any reasons why you'd want to connect to HTTP server on a private network. For developing an addon, you could just host it on a local computer. Otherwise, you could port forward the HTTP server, and use your public IP address.

**Comment by edgarasf123** [comment]
I don't believe **any** web page could do it, definitely not public ones, usually browsers come with [CSP](https://en.wikipedia.org/wiki/Content_Security_Policy) which prevents such attacks.

**Comment by neico** [comment]
eays solution: make a convar to toggle it off for those few advanced users so everyone wins (it's up to debate if you add the archive flag to it)

Also you can proxy stuff around by using the loopback interface to selectively whitelist a service

**Comment by Bo98** [comment]
Also, it could just be limited clientside if necessary.

**Comment by Velkon** [comment]
This is a great example of the dangers with saying "what if".

Trying to use this as an actual exploit to attack people is simply impractical and nearly impossible.

**Comment by edgarasf123** [comment]
Oh really? You don't think I could write worm of some kind?

**Comment by Velkon** [comment]
Yes, you couldn't.

**Comment by thegrb93** [comment]
I honestly don't. Not with a http request alone.

**Comment by edgarasf123** [comment]
1.  I could determine list of common routers and modems used by ISP and consumers in general, and see what their default passwords are and vulnerabilities. For instance the second image of the modem doesn't even require authentication, since it trust local network.
2.  Next, run a script that would brute force various IPs' check what firmware running, and run specific script for that firmware. It could make request to my server, and I see if I get many requests for some unknown router, I then could dynamically update the database to account for it.
3. Next, when I gotten access to the router, I could change DNS queries to my server. This could potentially allow for me to monitor client's traffic, nfoservers still use FTP for instance. Otherwise, I could just find a list of commonly requested pages from GMod to various web apps, and just inject Lua. Now I have access to clients' Lua state within all servers using an addon that also has HTML with :AllowCSLua(). Jukebox for instance is really popular one.
4. I bet few of the clients is going to be superadmin of some other server. The process repeats once the code is executed on that server for all other clients. Go to Step 2.

This could be happening as we speaking right now, if the attacker is smart, he wont be making it obvious.

There is also the workshop, just have a damn popular workshop addon, or multiple of them, and just inject the exploit code.

That's just one case, there's probably shit ton of others. I might aswell just avoid doing it everything through Lua and allow remote access to the routers... And then manage them remotely, this kind of shit is what allowed Mirai virus to get spread...

**Comment by thegrb93** [comment]
That'd be one really shit router. Again though, any other app can do that too.

**Comment by edgarasf123** [comment]
I'm yet to see an app that could do that. And most people have a shitty routers, in general most consumer routers don't consider security seriously. Just because you might have fancy one, doesn't mean everyone else has such. Again, rare cases, by few users.

**Comment by Velkon** [comment]
I reported this 3 years ago.

It's also 2019 now, routers don't have default passwords anymore. They're all random.

**Comment by edgarasf123** [comment]
False sense of security going on here. Did you even looked into the linked reference I posted, on first thread? The vulnerabilities are found in monthly bases, even 2018. 

Not sure where the argument "2018" is coming from. Seems like an excuse to be ignorant.

If you weren't aware, companies are struggling with IoT security, especially in 2018. There's a reason why governments and companies dumping money onto various cyber sec programs at this very moment.

**Comment by Velkon** [comment]
Yes mine was based around getting the mac address of the router and using Google's API to get the exact irl address of the client. Something more probable than hoping that a router is vulnerable because you have a complete list of every vulnerability that exists on every router ever made

**Comment by thegrb93** [comment]
I don't think it's equivalent to that, but it is more like disallowing something because a vulnerability patched years ago is still affecting some people.

**Comment by Bo98** [comment]
> This is the equivalent of getting mad at someone for using pairs instead of ipairs where it would be faster

Seriously?? This is absolutely not equivalent to that.

Even if an attack only affected one person, that is one person too many.

**Comment by Bo98** [comment]
> because a vulnerability patched years ago is still affecting some people.

I'd like to introduce you to the world of IoT.

**Comment by edgarasf123** [comment]
I was typing on my phone, I meant the link on my other post. There is it is https://routersecurity.org/othersgripeonrouters.php .

**Comment by edgarasf123** [comment]
**Here's some recent research on the topic:**
https://www.theamericanconsumer.org/wp-content/uploads/2018/09/FINAL-Wi-Fi-Router-Vulnerabilities.pdf
https://nakedsecurity.sophos.com/2017/03/21/people-who-think-theyre-tech-savvy-18-more-likely-to-be-hit-by-id-theft/

> It's also 2019 now, routers don't have default passwords anymore. They're all random.

False, I only found Netgear routers with random passwords, and they definitely don't dominate the market. Just google top sellers and you'll find that most of the routers will have some common default password set.

If you got a router from ISP, they might provide you with already configured router. Not all ISP provide routers. Its also common for a single ISP to dominate an area so it might seem that "everyone" now has random passwords, when in-fact its just the area.

> The exploit only works in theory

The chances are I could infect relatively large amount of users, just by looking at the research, I never claimed the worm would infect 100% users. The worm wouldn't rely on some "cosmic rays", its just chances of users having vulnerable router, and they're high.  And I haven't even considered implementing IoT in the attack, which would definitely increase the chances further. 

If you wan't more practical examples of exploits, just search by router brand name in exploit database. For instance, looked up for NETGEAR brand and found a [NETGEAR R7000 exploit ](https://www.exploit-db.com/exploits/41598) that allows executing shell commands without login, all you need is HTTP access the router to perform the attack. 

There's countless of other exploits for different brands and models, most of which can be executed through HTTP.

> Update your shitty router
I'm not concerned about my network security, more concerned about everyone else's.

Even then, I have hard time believing you'd keep up with updates yourself. Perhaps when you need to change some settings within the router, you might randomly click "check for updates" button. I'm in cyber-sec field and hardly done this myself, and my other peers. Do you think non-technical people would be any different?

And even then, people don't usually go for top-end routers. And once they set it up, they tend to forget its even there. Frequently I seen people leave their routers dust for up to 5 years.

I bought a new router few months ago, for about $200, I still wouldn't trust the access panel to be accessible from internet, even with a custom password set.

**Comment by neico** [comment]
I live in Germany and I use a Fritz!Box from AVM, which doesn't even work until you initially set a secure password, so it's not even providing a random or default password to begin with.

Meanwhile the router that originally came from the ISP had a default password of `admin01` or so,  
and may have a interface for updates, but last time I checked it doesn't have a single update to date. (Not to mention that it can be hardly called a router, at best it's a glorified modem)

So I can totally get behind this and say:  
routers may or may not be secure from the outside (pretty sure that ISP one would've been subject to this mass hack attempts against routers a while back),  
but they definitely aren't secure from the inside by default,  
unless you invest time and money in proper ones which actually allow you to manage your LAN and provide at least decent security. (And let's be honest, how many people do that, or even have the required knowledge?)

One would expect that after all these exploits and hack attempts towards routers lately that the industry would finally take IT security seriously, at both ends.

**Comment by robotboy655** [comment]
Just an FYI, there are plans to address this, including disallowing JS <-> Lua access for most pages (allowing it only for ```SetHTML``` and based on headers from server, similarly to ```Access-Control-Allow-Origin```) and potentially removing ```HTTP``` function from clients altogether.

**Comment by edgarasf123** [comment]
Is there a reason why private subnets only wouldn't be blocked?

**Comment by Mijyuoon** [comment]
> […] and potentially removing HTTP function from clients altogether.

This is such dumb idea, there are many legitimate use cases for it and I'd imagine there's quite a few addons that rely on being able to make HTTP requests from clients.

**Comment by Earu** [comment]
Yes there are, and some big names out there absolutely rely on them for example Mediaplayer & pac3. If you remove the HTTP methods from the client state you can be sure that you WILL disappoint thousands of players.

**Comment by roboderpy** [comment]
Removing HTTP() means:
* Breakage of **most** advanced addons (which use http json bundles instead of regular lua files which you can't modify easily)
* Complete breakage of some most popular gmodstore addons (lulmao great)
* Removal of addons which load anything using http(s) (VLL2 for example)

Removing JS <-> Lua means:
* Complete breakage of almost all advanced HTML addons
* (for me) Inability to create HTML based chat.

**Comment by thegrb93** [comment]
Oh well, guess we'll be using 3rd party modules when it happens.

**Comment by end360** [comment]
Removing JS from router pages wouldn't be enough because some of the exploits can be done through just the GET/POST params.

**Comment by ajloveslily14** [comment]
Oh god

**Comment by adosikas** [comment]
IMO the router/NAS/LAN attacks aren't even the biggest problem here.

Clientside HTTP means that servers you join (or a rogue admins with lua access) can make your computer request any arbitrary site in the background (including JS-Cryptominers, IP-loggers, Jailbait or just huge/many files to clog your connection/DDOS the host).

This is issues becomes much more dangerous with certain addons allowing *normal* players to do this to any/all players. @thegrb93 's Starfall used to have this problem in the default config for years (and you can still trick people to toggle a checkbox that effectively enables a full http proxy through that players connection) and I think PAC3 and several of the "streaming/mediaplayer" addons allow all players to make all other players request completely arbitrary locations.

**Comment by edgarasf123** [comment]
Implementation wise, `HTTP()` shouldn't be difficult to patch. Just resolve the domain before making an actual request and check if its in private or not. 

Now with stuff like chromium/awesomium specifically, it might be harder to implement such protection. One way I could possibly see this implemented is creating a localhost proxy server on the system, and configuring chromium to go through that proxy. The proxy would check request packets and block the ones made to private networks.

Note: I haven't used chromium framework within my projects, but I'd believe it would support web-proxies as any other browser does.

**Comment by adosikas** [comment]
301 Redirects are definitely followed, which also means you can bypass most "sanitizers" by just pointing to a url-shortener with whatever host, ip, port or GET-parameters you want.

**Comment by edgarasf123** [comment]
There are issues by having a proxy on game server.

- **Bandwidth:** It would eat up the bandwidth of the server when people are streaming youtube videos at 1080p60.
- **Firewalls:** Server owners would have to open the ports manually. That is, after spending hours of research why http is not working for their clients.
- **Latency:** Since everything is routed through the game server, this can have significant impact on request latency, based on the locations. Basically `latency(client<->game_server)+latency(game_server<->web_server)` instead of just `latency(client<->web_server)`
- **Shared servers:** Which instance would own the proxy service on shared box? This could potentially get resolved by randomizing port numbers. But then you have an issue with firewalls.
- **Potential denial of service:** Its not unusual for webservices to temporarily block IP addresses based on number of queries from a single IP. Since all the clients requests are routed through a single server, a web service is more likely to block the server from making any further requests.

I could go on and on... But this should be a plenty of reasons why not to host the proxy server-side.

**Comment by h3xcat** [comment]
```lua
http.Fetch("https://h3x.cat/redirect/http/192%2E168%2E100%2E1/", function(...) print("ok",...) end)
```
![image](https://user-images.githubusercontent.com/2304691/101739790-e0fd8980-3a7c-11eb-96a6-00c9aaf6d536.png)

**Comment by ajloveslily14** [comment]
Can't wait for the next \*cough* virus

**Comment by Velkon** [comment]
This is a waste of time

**Comment by ajloveslily14** [comment]
Keep saying that until you join a server and suddenly your router is apart of a botnet
