### ISSUE TITLE
Very long loading times and out of memory crashes since last update.

### ISSUE THREAD

**Issue by wannaseeanalien** [Facepunch/garrysmod-issues#3701]
OS: Windows 10 (tested on 7 and ubuntu linux, same results)

Ever since the last big patch, the one with "Changed Lua file hashing algorithm to improve security" 

Loading times have more than doubled and the "out of memory" crash is much, much more common. And this is on windows.. 

Whether I have 0 addons or just a few, the results are the same. Servers that I used to join in a minute or two now take much, much longer.. I have never even had out of memory crashes on windows up until this patch, can we please get this change reverted? its been nothing but trouble. 

Don't tell me you are going to use 64 bit as a solution to a problem you guys created.

**Comment by Alex2259** [comment]
I've witnessed this, it causes timeouts on my server that has a modest amount of addons. In my experience, this can be reproduced by joining a server you haven't joined before, but it may be random as I have seen it happen otherwise. Usually, it happens when a new player is joining as opposed to a regular player. 

The timeout usually follows the player crashing right as the console reports them being given their spawn items (physgun, gravgun, etc.) When I managed to re-produce it twice, I was stuck on "sending client info." One of my users reported an outright crash when he ran into what we believe was this issue.

**Comment by mcNuggets1** [comment]
Isn't it only on first load?

**Comment by robotboy655** [comment]
Could you switch to the Dev branch and see where you get stuck on the Dev branch?

https://wiki.garrysmod.com/page/Dev_Branch

**Comment by robotboy655** [comment]
You are just redownloading the Lua file cache. It is a one time process unless you are constantly clearing the cache on your client (cache/lua/) or the server adds a lot of new files very often. There's nothing here to "fix", it is not broken, and was not changed.
