### ISSUE TITLE
Default Crosshair blocks env_sun traces

### ISSUE THREAD

**Issue by Stiffy360** [Facepunch/garrysmod-issues#3705]
For some random reason if one pixel of the default crosshair is over the env_sun sprite in the sky, it causes it to stop rendering.

**Comment by Kefta** [comment]
This is the offending code: https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/client/glow_overlay.cpp#L189

Glows have a central pixel that light is emitted from, so if it's covered, the glow is obstructed. Overlays are drawn before the crosshair in RenderView, but I don't think a pixel visibility test there is right since multiple passes will pick up blocking pixels from the HUD.

**Comment by robotboy655** [comment]
Well I can tell you one thing, it doesn't seem like its the crosshair has anything to do with this, completely ripping out the crosshair from the code doesn't solve the problem, and other HUD elements do not cause the same issues.

**Comment by robotboy655** [comment]
Should be fixed in Dev.

**Comment by Kefta** [comment]
What was the issue?

**Comment by CyberOne25** [comment]
How did you fix it? What did you change (in code perhaps)?

**Comment by robotboy655** [comment]
It was something to do with farZ being set to MAX_TRACE_LENGTH

**Comment by CyberOne25** [comment]
Yup.
