### ISSUE TITLE
File:ReadFloat() causes instant crash.

### ISSUE THREAD

**Issue by Nak2** [Facepunch/garrysmod-issues#3737]
### Details
Currently working on a .BSP parser.
Got it working on all maps, until I stumbled upon dod_anzio.

The mapfile contains a float that causes a crash and I suspect its the lua environment giving up.
Somehow it only crashes if you try to catch the float as a variable.
### Steps to reproduce
Running this function will cause your client to crash.
```
-- This will kill your client
function DodDeath()
	local f = file.Open("maps/dod_anzio.bsp","rb","GAME")
	f:Seek(17240990)
	local l = f:ReadFloat()
	f:Close()
	return l
end
```
However, if we don't catch the variable. It doesn't crash.
```
-- This won't kill your client
function DodSurvive()
	local f = file.Open("maps/dod_anzio.bsp","rb","GAME")
	f:Seek(17240990)
	f:ReadFloat()
	f:Close()
end
```
I'm not sure if I read the 4 bytes correct, but what I gathered is `0xDEFFFFFF`.

Running live version.

**Comment by Kefta** [comment]
The actual value is ``0xFFFFFFDE`` since the file being read in little-endian format. This can be confirmed by reading the value with ``ReadULong`` which returns ``4294967262``. ``0xFFFFFFDE`` for IEEE-754 floats usually encodes for a ``-nan`` float value which is probably causing the crash here -- I'd imagine the same issue would exist with ``inf`` values as well.

**Comment by Nak2** [comment]
Looks like the same problem as https://github.com/Facepunch/garrysmod-issues/issues/3538 .
I still find it odd that an entity's y-position is a -nan in an official DoD map.

**Comment by robotboy655** [comment]
Again, does it work on the x64 branch?
