### ISSUE TITLE
Weapons not loading after update

### ISSUE THREAD

**Issue by Kapppa** [Facepunch/garrysmod-issues#3761]
### Details
When turning on server on, the game does not load SWEPs so no weapons are usable.

Gamemode : Excl Jailbreak
OS: Windows/Linux (Tested on both)
Latest update.

### Steps to reproduce
Turn server on. SWEPS don't load.

**Comment by robotboy655** [comment]
Link to gamemode? Does it work in Sandbox? Any console messages? Have you actually tested if the weapon files are there, if they are registered? Anything at all useful you can give me? 

I have tested Windows SRCDS and the default weapons load file.

**Comment by Kapppa** [comment]
It is something to do with PlayerCanPickupWeapon. Did this get changed is the Feb 2019 update? Cause the behaviour seems to have changed. Code that worked before this update no longer does.

```
local pmeta = FindMetaTable("Player");
function pmeta:CanPickupWeapon(entity)
	if #self:GetWeapons() > 0 then
		for k,v in pairs(self:GetWeapons()) do
			if v.Slot == entity.Slot or v:GetClass() == entity:GetClass() then
				return false
			end
		end
	end

	return true
end

JB.Gamemode.PlayerCanPickupWeapon = function( gm, ply, entity )
	if not ply:Alive() then return false end

	if entity:GetClass() == "weapon_physgun" then
		return ply:IsSuperAdmin()
	end

	if not ply:CanPickupWeapon(entity) then return false end

	return true
end
```

This func fires. However if add a check to enable picking up with E. It will break the hook.

```
	if entity.IsDropped and (not entity.BeingPickedUp or entity.BeingPickedUp ~= ply) then
		return false;
	end
```

It also breaks ent:Give when the code is added. Guessing that Give cannot bypass this check anymore?

https://github.com/kurt-stolle/jailbreak - Gamemode

**Comment by robotboy655** [comment]
Nothing about those have changed, try undoing this change and see if it fixes it:
https://github.com/Facepunch/garrysmod/commit/3f57b81369b63ede11386edd054d2f2dfa792bde

**Comment by Kapppa** [comment]
Yeah reverting the file to the previous ones fixes the problems.

**Comment by Kapppa** [comment]
If I pickup the weapon as an Entity it will give it to me. However using ply:Give it will not give it to me.

**Comment by Kefta** [comment]
Even if you press E on the weapon?

**Comment by FRIZBOU** [comment]
I confirm that there is this problem since the update.

**Comment by FRIZBOU** [comment]
If we press E on the weapon, this one will disappear just as if it has been picked up, but it won't be in the inventory.

**Comment by FRIZBOU** [comment]
It's not comming from the HUD weapon selection ot from the pickup function, because even weapons that normally are given from the pointshop have this issue. For exemple I have knifes in my pointshop and when I buy them they won't show up in my inventory.

**Comment by robotboy655** [comment]
I don't understand what the actual issue is. The weapons do load even for you, so this issue is already wrong.

I just tested the gamemode on a Windows SRCDS (local) and the weapons do spawn properly and can be picked up properly, unless you already have a weapon in that slot.

What is the actual problem here?

**Comment by RainingTerror7** [comment]
With the Jailbreak gamemode linked above on a fresh Windows server none of the weapons work for me, the weapons that you are supposed to spawn with in your slots are not there and pressing E on any wall weapon results in it disappearing but not being added into any of your slots.

When the update hit most of the public JB servers I joined also had this exact issue.


![](https://i.imgur.com/F8Ybpgt.jpg)

**Comment by robotboy655** [comment]
I can see that after some uptime none of the weapons have physics so they cannot be picked up by the player. The weapons "disappearing" is the gamemodes doing, not the GMod's.

Something is destroying physics objects on all of the weapons.

I don't understand why it was stated that "weapons do not load" when they clearly do.

**Comment by RainingTerror7** [comment]
My screenshot was from roughly 1 minute uptime, it does seem to be just this game mode but it did work perfectly prior to the GMod update.

When using pointshop and equipping a SWEP it is not given to you, and when using the ULX give command no SWEPS are put into any of your slots either, tried with the base jailbreak weapons and custom ones from the workshop

**Comment by FRIZBOU** [comment]
In addition, default weapons from the loadout also don't appear. For exemple a guard spawns with sweps (classes - guard):

local randomGuardSidearms = {"weapon_jb_usp","weapon_jb_fiveseven"};
local randomGuardPrimary = {"weapon_jb_sawedoff","weapon_jb_aug","weapon_jb_galil","weapon_jb_mac10","weapon_jb_mp5navy","weapon_jb_p90","weapon_jb_sg552","weapon_jb_ump"};
function PLAYER:Loadout()
	self.Player:Give("csgo_default_t");

	self.Player:Give( table.Random( randomGuardSidearms ) )
	self.Player:Give( table.Random( randomGuardPrimary ) );
	self.Player:GiveAmmo( 255, "Pistol", true )
	self.Player:GiveAmmo( 512, "SMG1", true )
end

But since the update not only pickable weapons have a probleme but also those from loadouts. As RainingTerror7 said, trying to give yourself a weapon with giveweapon in ulx or trying to buy a weapon in the pointshop seems to present the same issue.

**Comment by robotboy655** [comment]
Ok I figured it out. The problem is here:
https://github.com/kurt-stolle/jailbreak/blob/82422e6adabc82719f4d53f29a65ce6af807f5d3/gamemode/core/sv_entity.lua#L37-L38

This piece of code used to not work and now it does, which is the entire problem. It was indeed caused by the fix to the Lua tables getting reset.

Removing those 2 lines should fix it, but you should make sure it all works properly.

**Comment by FRIZBOU** [comment]
Thank you very much ! All is working perfectly !
