### ISSUE TITLE
point_viewcontrol, env_zoom is blacklisted from game.CleanUpMap

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3774]
### Details
Using point_viewcontrol and then game.CleanUpMap() will leave the old point_viewcontrol in the map which brings some side effects:
1. Implemented your own point_viewcontrol, theres no way to reset other than hacky tricks.
2. Using the native point_viewcontrol will corrupt the players view given that its always local coordinates and point_viewcontrol itsself is moving, so you end up having the last used state on cleanup.

### Steps to reproduce
Well, not a lot of maps use this but I'm not sure why this is filtered to begin with.

**Comment by robotboy655** [comment]
env_zoom is not filtered, point_viewcontrol is filtered in every single other Source game which is why it is also filtered in GMod.

What exactly is the problem with point_viewcontrol? Can you give steps to "corrupt  players view"? I have been messing with these entities on d2_coast_03 and besides no multiplayer support, there isn't anything thats "corrupting players view".

I also have updated these entities just now with better MP support, let me know if there are any problems or if its better for the issues you are having.

**Comment by ZehMatt** [comment]
I've already implemented my own point_viewcontrol. The issue is prominent at ep1_citadel_00 if you were to run game.CleanUpMap after the whole scene you will find that the point_viewcontrol starts from the last position. Right now I'm manually removing it in PreCleanUpMap

**Comment by ZehMatt** [comment]
Demo: https://share.epic-domain.com/2019-02-27_17-48-48f77adab10720ff727.webm

**Comment by robotboy655** [comment]
Removed point_viewcontrol from the filter

**Comment by ZehMatt** [comment]
Thanks
