### ISSUE TITLE
Player:CanUseFlashlight() only works serverside despite being marked as shared on wiki.

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [Facepunch/garrysmod-issues#3796]
### Details
https://github.com/Facepunch/garrysmod/blob/bf7057d8f273ffb20bdb075bf20467213a6f5e4d/garrysmod/lua/includes/extensions/player.lua#L225

When this function is called from server the updated value is not sent to client.
![](https://yurie.thigh-high.club/vbep62nf.png)

### Steps to reproduce
1. Load on any map
2. Change the AllowFlashlight value by calling `Player:AllowFlashlight(true)` from server
3. Try getting `Player:CanUseFlashlight()` clientside, it will always return false.

**Comment by Kefta** [comment]
The function shouldn't exist on the client at all since ``PlayerSwitchFlashlight`` is serverside only, but either way, those functions are implemented in Lua so you can perform the networking yourself if necessary. I don't really see a benefit to syncing the value since the client doesn't have to know if the flashlight is usable in default implementation.

**Comment by roboderpy** [comment]
Actually, it looks like `PlayerSwitchFlashlight` should be predicted.

**Comment by Kefta** [comment]
Impulse commands (or really any concommands) aren't predicted, this would require some major reformatting to the command system.
