### ISSUE TITLE
m_bThrownByPlayer is never true.

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#3802]
### Details
This is supposed to be set to true when the player throws/drops it via pickup or the gravity gun, however on all my testing this variable was updated.

### Steps to reproduce
Poll the variable and throw the object around, will never be true.

**Comment by neico** [comment]
Since you're talking about an C++ class variable,  
which isn't used anywhere in the lua code,  
I assume you're asking this from external tools such as sourcemod scripting? (which isn't officially supported by gmod)

Because In-Lua there's gamemode hooks for pickup and punting, which do work correctly.

**Comment by ZehMatt** [comment]
You can access most fields by GetInternalVariable/GetSaveTable, bug remains a bug if I can access it externally or internally doesn't matter.

**Comment by robotboy655** [comment]
It does work, only for +use throwing.

https://github.com/Enhanced-Source-Project/Enhanced-Source/blob/master/src/game/server/props.cpp#L2997-L3016

GravityGun uses a different variable called m_bFirstCollisionAfterLaunch 

```
hook.Add("Think", "Bug", function()
	if ( SERVER ) then
		local ent = Entity(110)
		print( ent, ent:GetInternalVariable("m_bThrownByPlayer") )
	end
end )
```
