### ISSUE TITLE
Garrys mod as an update, but its not an update

### ISSUE THREAD

**Issue by thatonegamer202** [Facepunch/garrysmod-issues#3810]
It says "updating Garrys Mod.   0 bytes / 0 bytes" and it is pretty annoying. Please find a way to fix this. it is either Steam or Garrys Mod.

All I did was reinstall Steam because it broke then after reinstalling Garrys Mod it said "updating Garrys Mod.   0 bytes / 0 bytes" and it won't go away. I have found ways to stop it for a while, I repeat For A While. you can uninstall appworkshop_4000.acf in the workshop folder (located in "C:\Users\User\Downloads\steam\steamapps\workshop") and unisntall and reinstall it.
If you can't fix this, then I will deal with it

**Comment by neico** [comment]
It's the way steam operates, if you're not using steam beta you might want to try that, because they recently fixed 0 byte update cases,
0 byte updates basically means that something in the game's metadata changed, this can be simply a new build on one of the beta branches.

See steamdb.info on details for inner workings.

**Comment by robotboy655** [comment]
This isn't a problem with Garry's Mod, but with Steam, and there's nothing we can do about it.

You will have to contact Steam Support for any help with the Steam software and services.

**Comment by thatonegamer202** [comment]
Thank you.
It was very annoying and I am installing the beta update right now
Thank you and bye
