### ISSUE TITLE
Reloading of materials break every single material created using CreateMaterial

### ISSUE THREAD

**Issue by DBotThePony** [Facepunch/garrysmod-issues#3811]
This bug exist a very long time and i can't believe nobody reported it.

(Example code will demonstrate breakage of`UnlitGeneric`, but in general, any material can break, e.g. `VertexLitGeneric` will turn completely black after `mat_reloadallmaterials` for example)
## To reproduce:
1. `sv_cheats 1` in console

2. Load next code:
```lua

local rt = GetRenderTarget('rt-issue-report', 2048, 2048, false)

local rtmat = CreateMaterial('rt-issue-report-mat', 'UnlitGeneric', {
	['$basetexture'] = 'models/debug/debugwhite',
	['$translucent'] = '1',
	['$halflambert'] = '1',
	['$color'] = '1 1 1',
	['$color2'] = '1 1 1',
	['$alpha'] = '1',
	['$additive'] = '0',
})

rtmat:SetTexture('$basetexture', rt)

hook.Add('HUDPaint', 'rt-issue-report', function()
	render.PushRenderTarget(rt)
	render.Clear(0, 0, 0, 0, true, true)
	render.OverrideAlphaWriteEnable(true, true)
	
	cam.Start2D()
	
	surface.SetDrawColor(255, 170, 50)
	surface.DrawLine(0, 0, ScrW(), ScrH())
	
	cam.End2D()
	
	render.OverrideAlphaWriteEnable(false)
	
	render.PopRenderTarget()
	
	surface.SetDrawColor(255, 255, 255)
	surface.SetMaterial(rtmat)
	surface.DrawTexturedRect(0, 0, 2048, 2048)
end)
```

3. Execute `mat_reloadallmaterials` in console

-----------
Before:
![hl2_15-47-25-7c38975](https://user-images.githubusercontent.com/6339511/56090475-fc705580-5e91-11e9-8b41-7e424c503e24.png)
After:
![hl2_15-48-41-d2782c4](https://user-images.githubusercontent.com/6339511/56090483-2295f580-5e92-11e9-9129-193d038b1d9d.png)
-----------

Reloading code with `CreateMaterial` after materials reload fix the issue (sometimes), like materials created with `CreateMaterial` never existed

*this bug exist for way too long, 8 years long at least*

**Comment by neico** [comment]
The same can be observed on other mods when you use the SourceShader Editor for example.
Procedural created materials simply aren't cached internally as they have no file it could read them from (and they could have changed since it was created), making this intended behavior.

What it needs is a hook in which they are created, which is called both somewhere at initialization and when the material cache is flushed.

A possible workaround is keeping the material reference around and inside a think hook check if it's still valid, if it isn't, re-create it. (or do the check just before you're executing those render commands in HUDPaint)

**Comment by robotboy655** [comment]
What happens is this:
* The MATERIAL loses it's reference to the given texture. The intent by the material system here is to reload it by name, but the name is not set. This can be easily worked around by using texture names as per wiki example:
```
local rt = GetRenderTarget('rt-issue-report2', 2048, 2048, false)

local rtmat = CreateMaterial('rt-issue-report-mat2', 'UnlitGeneric', {
	['$basetexture'] = rt:GetName(),
    ...
} )

...
```
* The render target will be reset to black as well, but since it is being re-rendered in HUDPaint in this example it is not noticeable. Render targets are meant to re-render every frame they are visible so yeah.

Dynamic textures internally have a "texture regenerator" that is supposed to be used in cases like this. This is what .PNG stuff uses which is why they do not break.

Both of these "issues" are intentional behavior.
For "render-once" textures you'd want this: https://github.com/Facepunch/garrysmod-requests/issues/605

**Comment by DBotThePony** [comment]
Can we at least get `InvalidateMaterialCache` hook? So we definitely know the case when it is time to recompute rendertarget textures and creatematerial materials
