### ISSUE TITLE
Water effects are not refreshed when you go out of the water

### ISSUE THREAD

**Issue by dvdvideo1234** [Facepunch/garrysmod-issues#3818]
### Details
Water effects do not seem to be updated when the player goes out of the water slowly.
The airboat must exit the water without a splash.

### Steps to reproduce
1. Create a custom contraption with a bunch of props.
2. Weld an airboat seat to the main prop
3. Place the contraption in the water
4. Enter the seat
5. Use the contraption to go out of the water

### Video
[![](http://img.youtube.com/vi/gxBl0x_oz_s/1.jpg)](http://www.youtube.com/watch?v=gxBl0x_oz_s "") [![](http://img.youtube.com/vi/gxBl0x_oz_s/2.jpg)](http://www.youtube.com/watch?v=gxBl0x_oz_s "") [![](http://img.youtube.com/vi/gxBl0x_oz_s/3.jpg)](http://www.youtube.com/watch?v=gxBl0x_oz_s "")

**Comment by robotboy655** [comment]
Duplicate of https://github.com/Facepunch/garrysmod-issues/issues/3733

As I mentioned in that ticket, I cannot reproduce the actual water overlay texture persisting, maybe that's a part of your addons? Can you test with -noaddons -noworkshop? 

Otherwise, WaterLevel() not updating in vehicles have been fixed in the Dev branch and in the next update.

**Comment by dvdvideo1234** [comment]
Let me try this evening.

**Comment by dvdvideo1234** [comment]
Hello, without all the addons appears to be fixed. This most likely an addon related problem. Tested with the same contraption, but had to use `winch` instead of engine/wheels as the engine addon was not present.

![image](https://user-images.githubusercontent.com/9112662/57199231-71144c80-6f85-11e9-927c-9fad6765c060.png)
