### ISSUE TITLE
npc_tripmine, npc_satchel and npc_grenade_frag don't have owner

### ISSUE THREAD

**Issue by GitSparTV** [Facepunch/garrysmod-issues#3862]
According to public Source Engine SDK these entities have owner assignation, but in Garry's Mod the owner can't be taken. 
<br><br>
__npc_tripmine__
```cpp
pMine->m_hOwner = GetOwner();
```
[Go to Source](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/shared/hl2mp/weapon_slam.cpp#L378)
<br><br>
__npc_satchel__
```cpp
pSatchel->SetThrower( GetOwner() );
```
[Go to Source
](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/shared/hl2mp/weapon_slam.cpp#L487)
<br><br>
__npc_grenade_frag__
```cpp
pGrenade->SetThrower( ToBaseCombatCharacter( pOwner ) );
```
[Go to Source](https://github.com/ValveSoftware/source-sdk-2013/blob/0d8dceea4310fde5706b3ce1c70609d72a38efdf/mp/src/game/server/hl2/grenade_frag.cpp#L426)
<br><br>
An attempt to call GetOwner() returns `[NULL Entity]`.

You may ask why this is a problem?

Well, let me introduce you a SLAM-Tree:
![hl2_2019-05-21_17-56-10](https://user-images.githubusercontent.com/5685050/58136959-c5cbee80-7c38-11e9-9813-76c90c85f9db.png)
![hl2_2019-05-22_03-08-32](https://user-images.githubusercontent.com/5685050/58138461-ea2ac980-7c3e-11e9-9cfe-7c7b0251b667.png)

No owner -- no ban from admin.

**Comment by robotboy655** [comment]
SetThrower/m_hOwner is not the same as SetOwner() or GetOwner() in Lua.

There is a reason those entities do not set the owner, because doing so will prevent the S.L.A.M. entities from being damaged by the player (i.e. shooting them will not blow them up) and the tripmine will ignore the player walking through its laser.

You can get the Thrower of a grenade/satchel charge using ```ent:GetInternalVariable("m_hThrower")``` and the owner of the tripmine using ```ent:GetInternalVariable("m_hOwner")```
