### ISSUE TITLE
Autoexec.cfg not working on chromium branch

### ISSUE THREAD

**Issue by Machinegamer101** [Facepunch/garrysmod-issues#3879]
### Details
So, the autoexec.cfg file does not execute all the commands or does not even work in the chromium branch of Garry's Mod. i dont know why but it does not.
Also i found some commands that stopped working after switching to the chromium branch
hud_draw_active_reticle 1
Some commands that arent executing on autoexec.cfg (at least the ones i could notice weren't executing) are
rate "128000"
cl_cmdrate "64"
cl_updaterate "64"
### Steps to reproduce
Tell us how to reproduce the problem, step by step
You put the commands you want into 
So, you put the commands you need into autoexec.cfg, start gmod and the commands dont even execute.

**Comment by robotboy655** [comment]
It most definitely works. You can verify it yourself by using the "echo" command like so:
```
echo Autoexec Executed
cl_cmdrate
cl_cmdrate 64
cl_cmdrate
```
You will see these messages in your console on game startup:
`
Autoexec Executed 
"cl_cmdrate" = "30" min. 10.000000 max. 100.000000 (This is the previous default value)
 archive
 - Max number of command packets sent to server per second
"cl_cmdrate" = "48" ( def. "30" ) min. 10.000000 max. 100.000000 (This is the new set value, which is set again to 30 by something else in the game engine)
 archive
 - Max number of command packets sent to server per second
`
So all of the commands are being successfully ran.

I can confirm `cl_cmdrate` `cl_updaterate` and `rate` are being overwritten by something else.

hud_draw_active_reticle is also being set (You can verify by entering `hud_draw_active_reticle` without a number into your console), but it doesn't do anything since there's no auto aim in GMod.
