### ISSUE TITLE
Tiny bug with weapon_fists

### ISSUE THREAD

**Issue by wasplay** [Facepunch/garrysmod-issues#3942]
Debris of breakable props won't show up when broke with weapon_fists in an empty "base" based gamemode

**Comment by robotboy655** [comment]
Cannot confirm, sounds more like a problem with your configuration (prop_active_gib_limit)

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/63176882-6e7ac600-c04f-11e9-9cc2-75f3b484b790.png)

**Comment by Kefta** [comment]
I can reproduce it. Using weapon_fists in local multiplayer sandbox will spawn no gibs for breakable props, yet they do with the crowbar.

**Comment by wasplay** [comment]
Looks like the gibs appear on single-player mode but not on a server

**Comment by Jvs34** [comment]
I remember having this issue with my weapons back in the day, it's due to prediction.
Breaking stuff sends a message like "tell client to spawn gibs" but since it's done during prediction, the client ignores it as it's "supposed" to do that on it's own, obviously not a problem in singleplayer since prediction is off.

The call to [TakeDamageInfo](https://github.com/Facepunch/garrysmod/blob/2bc5fee85516124c98b658b450e3d6b8a9d5cfea/garrysmod/lua/weapons/weapon_fists.lua#L135) needs to be encased in a `SuppressHostEvents( NULL )` and `SuppressHostEvents( self.Owner )` to let the messages through.

**Comment by wasplay** [comment]
> I remember having [this issue with my weapons](https://github.com/Jvs34/gmod_personal_dump/blob/c209b38d3fe67d6820ba7c9c1629c68f81a8f0d5/remoteluascripts/lau/weapon_melonpoof.lua#L362-L368) back in the day, it's due to prediction.
> Breaking stuff sends a message like "tell client to spawn gibs" but since it's done during prediction, the client ignores it as it's "supposed" to do that on it's own, obviously not a problem in singleplayer since prediction is off.
> 
> The call to [TakeDamageInfo](https://github.com/Facepunch/garrysmod/blob/2bc5fee85516124c98b658b450e3d6b8a9d5cfea/garrysmod/lua/weapons/weapon_fists.lua#L135) needs to be encased in a `SuppressHostEvents( NULL )` and `SuppressHostEvents( self.Owner )` to let the messages through.

Thanks, it works
