### ISSUE TITLE
Spelling error in chat

### ISSUE THREAD

**Issue by mcNuggets1** [Facepunch/garrysmod-issues#3981]
### Details
https://i.imgur.com/0LDiPkH.png
Shouldn't it be "Copy"?

### Steps to reproduce
Rightclick in chat.

**Comment by Visual-Vincent** [comment]
That's what's called a [_mnemonic_](https://en.wikipedia.org/wiki/Mnemonics_(keyboard)). The ampersand (`&`) is used to indicate that the next character can be pressed in combination with `ALT` in order to execute the command without using the mouse (`ALT + O` in this case).

You are however right that there is a problem. The ampersand shouldn't be rendered, but it should cause the `o` to be underlined to indicate that it can be pressed to execute the command.

**Comment by robotboy655** [comment]
Dunno when it was fixed, but it appears to be fixed now.

![image](https://github.com/user-attachments/assets/0107c2ff-287a-4efe-82b4-af948cb08376)
