### ISSUE TITLE
Rendering icons causes game crash [x86-64 2019.09.14]

### ISSUE THREAD

**Issue by Jaidendude** [Facepunch/garrysmod-issues#4007]
### Details
Appears to be a crash related to rendering icons for the first time (Bottom right hand notification)

Happens on the  [x86-64 2019.09.14] build, NOT on 32-bit.

DL Link to .dmp file https://drive.google.com/file/d/1Z-44g57uCfrAitnvSHIMrQsicrNVpeG1/view?usp=sharing

### Steps to reproduce
Start up any single player game, or multiplayer game where you have not rendered icons for the first time

Navigate to a menu where you render an icon for the first time

Game hard crashes with only minimal freezing beforehand.

**Comment by willox** [comment]
I don't really know what to make of this. Some of the data in the loaded d3d9.dll (`C:\Windows\System32\d3d9.dll`) seems to be invalid. It has the same version number as the file on my own computer, but they do not match.

I'd jump to the conclusion that the file on your pc was corrupted, but there was an issue not long ago where Microsoft shipped a d3d9.dll build with a similar issue (https://www.reddit.com/r/GrandTheftAutoV/comments/ciqiw8/gta_5_will_not_launch_after_kb4505903_windows/)

This one is in a different place though... but it might be caused by a recent Windows update you installed.

**Comment by Jaidendude** [comment]
Thank you muchly. Closing MSI Afterburner (and therefore RivaTuner) stops the problem from appearing. Very strange.
