### ISSUE TITLE
Not solid func_button changes position

### ISSUE THREAD

**Issue by pBinarySoul** [Facepunch/garrysmod-issues#4009]
### Details
func_button with spawnflag "Not Solid" changes position. I've created 2 buttons with this flag and it changed positions in different directions. First button is higher than must be, and second is below than must be.

### Steps to reproduce
Create func_button with "Not Solid" spawnflag and try to press on it.

**Comment by robotboy655** [comment]
I cannot reproduce this. And it doesn't make sense.

Do you have a .vmf I can try? You can send to my email in the readme of this repo.
Otherwise I will assume your settings on the entity are just "wrong" i.e. the move direction is not the same for both entities.
There's also a "don't move" spawnflag and I don't know why would ever not use it.

**Comment by pBinarySoul** [comment]
> I cannot reproduce this. And it doesn't make sense.
> 
> Do you have a .vmf I can try? You can send to my email in the readme of this repo.
> Otherwise I will assume your settings on the entity are just "wrong" i.e. the move direction is not the same for both entities.
> There's also a "don't move" spawnflag and I don't know why would ever not use it.

[Here it is](https://mega.nz/#!IeInTSbK!UOiduuQ-dR6-p_gzZFzmLn_mSLVugog0Aopg5-xWSmk).
Try to open the door by typing pin code 5649 on the keypad. These buttons will play two sounds.

**Comment by robotboy655** [comment]
Ok, so the problem for you is that only ever the button on the number 3 is pressable because of how the use code works. Since the buttons are non solid, it searches for the nearest entity to use because the trace cannot physically hit any of your buttons. There ain't anything stupid going on such as buttons changing positions.

The non solid keyvalue was only added for compatibility with CS:GO map. You don't need to use it here.

You can debug your map I/O using `developer 2` in your console.
