### ISSUE TITLE
Garry's Mod (and other source games) crashes immediately upon starting up.

### ISSUE THREAD

**Issue by Ligmatism** [Facepunch/garrysmod-issues#4078]
### Details
I don't remember exactly when this started happening, but for whatever reason, a number of source games I own have stopped working in an unusual way. Upon starting one of them up, it will do one of 3 things;
1. Show the game window, maybe show the loading screen for a split-second, and promptly close.
2. Show the game window, show a completely white screen, and promptly close.
3. Play the first half-second of the Valve Logo theme, and promptly close.
Garry's Mod, Team Fortress 2, and Counter-Strike: Global Offensive have had this problem for months now, and so far, nothing I have done has resolved the problem for any of them. I went through every solution on the common startup issues list (for a windows 7 64-bit system), and sadly, none have provided fruitful results. I have a sinking feeling there's something blatantly obvious I am overlooking, but help/guidance is appreciated nonetheless.

I am going to email a Garry's Mod crash log (.mdmp file) to robotboy655@facepunchstudios.com, corresponding to my issue.

### Steps to reproduce
The problem occurs regardless of what I do, but it started happening around the time I upgraded to a new AMD driver.

**Comment by robotboy655** [comment]
This is not a place to get help. You can get help either on our official Discord server (https://discord.gg/gmod), or on the official Support website: https://support.facepunchstudios.com/

It's a problem with your drivers, not the game, and you know it since it also happens in other games for you. Update or rollback your drivers. There's physically nothing we can do here.
