### ISSUE TITLE
Crash server DarkRP

### ISSUE THREAD

**Issue by FunnyCraft** [Facepunch/garrysmod-issues#4122]
https://pastebin.com/b46Aypc4  , https://pastebin.com/yZBmWTGL - idk what happened

**Comment by thegrb93** [comment]
physics crashes

**Comment by FunnyCraft** [comment]
what actions can this happen?

**Comment by Kefta** [comment]
The first is from vehicles, the second is from normal physics simulation. It's unknown why they occur as vphysics is not public.

**Comment by FunnyCraft** [comment]
> The first is from vehicles, the second is from normal physics simulation. It's unknown why they occur as vphysics is not public.

https://github.com/Kefta/gs_crazyphysics maybe its help?

**Comment by Kefta** [comment]
They're not crazy physics crashes.

**Comment by Verideth** [comment]
`ecx` is likely a `nullptr` which is why it's causing a segmentation fault. So whatever the first argument to that function is it's what's jacking it up. Seems to do something with 

https://github.com/UAVXP/LeakNet/blob/master/ivp/ivp_collision/ivp_compact_ledge_solver.cxx#L274

It's calling convention is `__fastcall`, so first argument is `nullptr` (aka `ecx`). Don't know much besides that, but it'll give a good start on what's directly causing the issue.

Are you potentially missing libraries on your server?

**Comment by thegrb93** [comment]
You're assuming that the hl2 beta leak of IVP source is a reliable representation of what's in gmod.

**Comment by Verideth** [comment]
> You're assuming that the hl2 beta leak of IVP source is a reliable representation of what's in gmod.

It definitely is.... it's a library for collision. Not to mention Garry's Mod is built upon the engine HL2 uses. Source engine has underwent changes, but most of the time it's additions. 

Also your point is irrelevant. If you actually read through the error and the disassembly of the function, and rebuilt it in C++, you'll practically notice it's near identical to the function itself...

**Comment by thegrb93** [comment]
I spared you a lot more fallacies than that in your observation. I'm just pointing out weaknesses in your theories so that you can grow and stop being such a noob.

a) Source2013 is miles ahead of beta hl2
b) It's not just a library for collision
c) You speculated that 'its likely a null pointer' via the segfault when it could be any invalid pointer
d) You are assuming the bug is in that function when fuck who knows where in the engine could have triggered such error state.
e) missing libraries would not cause this, you #(*$&#*$

>EDIT: Yeah, it seems to be apart of a different library than what is given inside of that repository. Are there any leads on it?

That repository is beta hl2

**Comment by Verideth** [comment]
@thegrb93 

1) Go read the source to each, not really. Major additions, yes. Worlds different? Not really.

2) Uh? No shit. I never specifically said that.

3) Uh, didn't I say possibly? Get off your high horse and go read the assembly, you "noob." Of course it could be many other reasons.

4) Bumping number 3, if you had any idea how any of it works you wouldn't make such a clueless statement. The error is in the dump for christs sake.

5) No, it definitely can if OP doesn't have the valid function the 'ECX' register gets pushed on then called using. As said, if you open your eyes and go through the dump its pretty damn obvious.

You have proven you have absolutely zero idea what you are talking about, incredibly low self-control, an ego that depletes your learning abilities, and on top of it all, a failure to actually accept an answer that isn't your one line responses, by the way, more correct than yours. Stop spreading misinformation. Go read up on what I mentioned.

Okay, I made my point and proved you wrong.... again. I'm done having a kiddie argument of whos right. Now I'm seriously done conversating. Have a nice day. I only wish you the best.

**Comment by Kefta** [comment]
Vphysics probably hasn't changed that much since 2003.

**Comment by thegrb93** [comment]
That could be true, but it doesn't change the fact this guy thinks he's the only one who can read a stack trace and signal and think he can solve the bug with his assembly skills.

@Verideth
You're just oozing pretentiousness. Really, it was very impressive how you read that stack trace and where the signal was caught; very low level bug diagnosis. Oh and if anyone discredits any part of your theory, they just need to read the link you googled and they'll understand what they did wrong. I honestly don't know what's more annoying: you thinking you proved me wrong, or you thinking >The assembler clearly shows it's near, if not 1:1 identical to the function I provided.

**Comment by thegrb93** [comment]
I get that crashes are probably what you're interested in, but this is not something you can solve. Unless you know the reliable way to reproduce the crash, then don't reply.

**Comment by Kefta** [comment]
Though Verideth posted Acecool amounts of unnecessary detail, nothing he said was wrong. Quit arguing on issue reports and take it to DMs on whatever platform.

**Comment by thegrb93** [comment]
He was wrong on several accounts, and this is the third time he's tried brushing off my criticism as if I'm some kiddie that doesn't know what I'm talking about.

**Comment by Kefta** [comment]
Ok, let's go through your criticisms.

``a) Source2013 is miles ahead of beta hl2`` - Some game-specific parts are, vphysics is mostly unchanged.
``b) It's not just a library for collision`` - Sure but it's primarily for collisions and collision-related utilities.
``c) You speculated that 'its likely a null pointer' via the segfault when it could be any invalid pointer`` - Crashes happen from dereferencing null pointers. Treating garbage pointers as valid data can lead to this indirectly, however, it looks like that isn't the case in ``IVP_Compact_Ledge_Solver::calc_unscaled_s_val_K_space``. I'm guessing ``give_object_coords`` or the ``IVP_U_Point`` member functions are inlined which are causing the crash dereferencing a nullptr as the only other thing that could crash directly inside ``calc_unscaled_s_val_K_space`` is the ``result`` dereference which looks like is always valid from the use cases.
``d) You are assuming the bug is in that function/stack-frame when fuck who knows where in the engine could have triggered such error state.`` - This is correct but Verideth wasn't implying that. Analysing the stack frame that crashed still requires it to use invalid data, which is a necessary step in identifying what the actual cause is.
``e) missing libraries would not cause this, you #($&#$`` - Yeah you're right, that is definitely not the problem.

In truth, the missing libraries statement is incorrect, but this argument is moot anyway:  there is almost certainly nothing to be done from Lua. It is most likely a crash that is rare and unavoidable like most vphysics crashes (aside from crazy physics).

**Comment by Verideth** [comment]
@thegrb93 You are not giving criticism. You are completely throwing off my response as bullshit then proceeding to blatantly insult me or make a paragraph saying I'm wrong.

Now to respond to your most recent post of what you call "criticism." As @Kefta has repeatedly stated what I said isn't wrong, and is in reality a rational and appropriate thought for the error. I never said I was right. I do know you are incorrect with your statements, however.

**Comment by thegrb93** [comment]
@Kefta There's more invalid pointers than just null. Yeah, i left off the nitpicky criticism initially before he started brushing me off again. The whole point I'm making is he's not contributing anything useful to the conversation and at times is making wrong observations, and when you point it out he just tells you to fuck off.

**Comment by Verideth** [comment]
@thegrb93 Just stop. You have absolutely no idea what you are talking about and now have two people telling you otherwise, yet you fail to just listen.

**Comment by robotboy655** [comment]
Closing as stale since there's no info let in the original report. If the issue persists, open a new report.
