### ISSUE TITLE
gmad.exe corrupts some files

### ISSUE THREAD

**Issue by danx91** [Facepunch/garrysmod-issues#4392]
### Details
I'm using latest version of gmad (x32, normal branch of gmod) and some files(sounds and models) are corrupted. After extracting .gma by gmad.exe several .mdl files are empty. The most interesting part is about sounds - most of the sounds don't work at all, few sounds are fine, and some files appear like some kind of mix of other sounds. All these sounds are .ogg (before: 500Kbps, 44.1KHz, after: mediainfo shows only file format) and .mp3 (before: 44.1KHz, after: mediainfo says that the format is ogg). Also windows explorer struggles with opening folders containing corrupted files (folder with 5 sounds takes 10s to load)
Edit: .wav files are also affected

This error initially happened to my friend and he sent me his files asking me to create .gma file. Btw. my friend tried using both x32 and x64 Garry's Mod.

### Steps to reproduce
1. Create addon from folder by gmad.exe
2. Extract this addon by gmad.exe

**Comment by azuspl** [comment]
With .wav there's too problem with corrupted files after unpack
Before compile, all sounds works properly, but after compile and upload on workshop and download content, sounds not work and there's just errors like:
```

Couldn't create BASS audio stream (unsupported file format)
Failed to load sound "warhead\explosion.ogg", file probably missing from disk/repository
```

**Comment by robotboy655** [comment]
Try the "Dev" beta branch and see what you get when making a .gma file.

**Comment by azuspl** [comment]
Okay in dev version after compile ogg, wav files, they works after decompile them
But now if i upload this content on workshop and download it then still have error

```
Couldn't create BASS audio stream (unsupported file format)
Failed to load sound "warhead\siren.ogg", file probably missing from disk/repository

```

**Comment by robotboy655** [comment]
Maybe link the addon at least?

**Comment by azuspl** [comment]
`https://steamcommunity.com/sharedfiles/filedetails/?id=2006590330`

**Comment by danx91** [comment]
Switching to dev branch fixed this problem, but I can't say anything about workshop problem bacause I haven't tested it.

**Comment by robotboy655** [comment]
So yeah that addon works for me.

Ff it doesn't work for you, maybe the problem is with your codecs on your system (try playing that file directly though GMod, not from workshop addon for example), or the files is on more than 1 addon for you (use `whereis sound/warhead/siren.ogg` to see where a file is) or you simply didn't download the update when you were testing.

To be clear, dev branch is not supposed to fix anything, it will only tell you that there was a problem creating the `.gma` file in the log. `gmad.exe` was not changed in any way that would cause issues or fix anything. It will only tell you about errors now instead of just silently continuing writing bad `.gma` file.
