### ISSUE TITLE
80% Players Time Out after joining my DarkRP Server

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#4519]
Server IP: PLAY.TEAMFRENCH.NET:27044
Hello @robotboy655 
I have a lot of players that Time out after joining my server.
They can't join it,

I removed 3D2D textscreens addons ,but still the same problem, Changed the map, but nothing works.

They just timeout when they join my server for no reason.

**Comment by anyome** [comment]
But a lot of others players can join my server just Fine!

I told them to put: cl_timeout 100000 but they still timeout !

**Comment by GitSparTV** [comment]
you need sv_timeout

**Comment by robotboy655** [comment]
Please stop posting about your issues with your server here. If players time out for you, maybe there's a big problem with your server(s). Again you provide no info such as console logs from both client and server. The timeout could happen due to many things such as - amount of addons your server forces people to download, hardware of the player joining, their network connection, etc.

Increasing `sv_timeout` and `sv_timeout_signon` on the server is a bandaid solution.

I have no reason to believe there is a problem with the game - you are the only one having issues.

Also please stop with the 80% bullshit in every issue you open. We both know it's not true.

**Comment by anyome** [comment]
sv_timeout_signon doesn't exists but i increased the sv_timeout to 1000

**Comment by GitSparTV** [comment]
it exists try again
type `sv_timeout_signon` and see the current value

**Comment by anyome** [comment]
https://i.imgur.com/HEx1sfk.png

**Comment by robotboy655** [comment]
![image](https://user-images.githubusercontent.com/3299036/83271809-0575d080-a1d3-11ea-96b1-2c438505efc6.png)

Your server must be very out of date.

**Comment by anyome** [comment]
Well i tough that we only need to update our servers when Clients can't connect due to the : "Server is using an older version of the game"

**Comment by robotboy655** [comment]
You should update with every update, how is that not obvious? They are all announced in advance, both on Steam and on our Discord server.

**Comment by viral32111** [comment]
It's kind of best practice to check for updates before the server starts, if you're using SteamCMD then it's just a case of adding something like `steamcmd +login anonymous +force_install_dir "/whatever/path/" +app_update 4020` before you run srcds.

If that's not possible though, at the very least setup some sort of crontab/schedule to run an update check every week or so.

**Comment by anyome** [comment]
Alright i'll start doing that. thanks a lot,
Can you see my second issue please: https://github.com/Facepunch/garrysmod-issues/issues/4520
