### ISSUE TITLE
Infinite spam to the console

### ISSUE THREAD

**Issue by Omni92** [Facepunch/garrysmod-issues#4538]
If you shoot from a crossbow outside the map, endless spam will start in the console.
[position and map](https://imgur.com/NhkjfBj.png)

Spam can be stopped only by deleting all "crossbow_bolt" from the map.
[console spam](https://imgur.com/S6oolXx.png)

I also noticed that the same thing can happen to the player, but I'm not sure how.
[console.log](https://imgur.com/lZDgq7n.png)

### Steps to reproduce
1. Take weapon crossbow.
2. Fly outside map.
3. Start shooting. (I got spam after 5 - 7 shots)

**Comment by viral32111** [comment]
Because the entity is outside the map bounds? I've seen this more or less happen with any entity outside of the map's bounds. This isn't a bug with gmod, it's just how source 1 works. That console output is informing you that there is an entity outside of the map, where it shouldn't be.

If I recall correctly, the limit is 16,384 in every direction from 0, 0, 0. So the maximum possible map size is 32,768 x 32,768 x 32,768.

**Comment by robotboy655** [comment]
Yeah, its not a bug, it's a notication that something is going wrong on your server.

If you re-enable crazy physics on your server (its enabled by default), the entities that go outside of map bounds will be deleted and there will be no spam. Don't worry, it won't delete players.
