### ISSUE TITLE
gmpublish_linux (dev): libsteam_api.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Volantarius** [Facepunch/garrysmod-issues#4542]
Using linux recently and when I run gmpublish_linux I get this error:

`error while loading shared libraries: libsteam_api.so: cannot open shared object file: No such file or directory`

I am running from a shell script, no sudo.

**Comment by robotboy655** [comment]
Either validate your game to make sure the file is actually there, or run the script from the correct path, i.e. from where `gmpublish_linux` is stored, which is `steamapps\common\GarrysMod\bin`. If you move `gmpublish_linux ` anywhere, you need to also copy over its dependencies.

**Comment by Volantarius** [comment]
I tried running it from the absolute path, with and without a script. I tried validating the integrity, and even deleted the file and running validate again to re-download it, and same issue. Gmad on the other hand works fine.

**Comment by viral32111** [comment]
>  Gmad on the other hand works fine.

Gmad probably works fine because it doesn't interact with Steam, it just creates or extracts addons. Gmpublish on the other hand needs the Steam API to upload workshop content.

My suggestions are try the following (in no particular order):
* Try copying `libsteam_api.so` in your system's library folders (`/lib/`, `/usr/lib/`, `/usr/local/lib/` - depending on lib architecture, it may go in the `lib32` and `lib64` folders respectively). 
* Ensure the file has the correct permissions, the default for libraries is probably `rw-r--r--`.
* Make sure the library is actually for the same architecture you're running Garry's Mod as (use `file` on both the lib and the gmod executable to verify this.)

**Comment by Volantarius** [comment]
Heres my script, I am running it without sudo and stuff.
```
#!/bin/sh

~/.local/share/Steam/steamapps/common/GarrysMod/bin/gmad_linux create -folder ~/.local/share/Steam/steamapps/common/GarrysMod/garrysmod/addons/mymod -out ~/gmodworking/mymod.gma;

~/.local/share/Steam/steamapps/common/GarrysMod/bin/gmpublish_linux update -addon ~/gmodworking/mymod.gma -id "numbersgohere" -changes "Linux Test";
```

**Comment by Volantarius** [comment]
libsteam_api.so has `-rwxrwxr-x`, should I still try putting it in `/lib/` ?

**Comment by viral32111** [comment]
> should I still try putting it in `/lib/` ?

If you want, also try `/usr/lib/` (usually package installed libraries go here) and `/usr/local/lib/` (usually self-compiled libraries go here).

Make sure you keep the name to `libsteam_api.so`, it's very important as when most linux applications look for libraries in code or compilers, they only search for the `steam_api` and linux inserts the `lib` suffix and `.so` prefix itself.

Thanks for the script aswell, I'll have a go at reproducing this on my machine now. Will get back to you once I've got some results.

**Comment by viral32111** [comment]
I managed to get this issue too, turns out just bundling `libsteam_api.so` in the GMod `bin/` folder isn't enough.

A stock Garry's Mod installation on my machine (XUbuntu 20.04 LTS, default gmod branch) resulted in this when `ldd`'ing the `gmpublish_linux` executable (I was `cd`'d into the `GarrysMod/bin/` folder at the time, so if it was trying to find the lib in the same working directory as the executable then it should have done so). As you can see it fails to find `libsteam_api.so`:

```
linux-gate.so.1 (0xf7f9c000)
libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf7f59000)
libsteam_api.so => not found
libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xf7d7b000)
libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf7c76000)
libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf7c57000)
libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7a69000)
/lib/ld-linux.so.2 (0xf7f9d000)
```

Upon copying `libsteam_api.so` into `/usr/lib/`, `ldd` managed to find it successfully:

```
linux-gate.so.1 (0xf7f19000)
libpthread.so.0 => /lib/i386-linux-gnu/libpthread.so.0 (0xf7ed6000)
libsteam_api.so => /usr/lib/libsteam_api.so (0xf7e76000)
libstdc++.so.6 => /usr/lib/i386-linux-gnu/libstdc++.so.6 (0xf7c98000)
libm.so.6 => /lib/i386-linux-gnu/libm.so.6 (0xf7b93000)
libgcc_s.so.1 => /lib/i386-linux-gnu/libgcc_s.so.1 (0xf7b74000)
libc.so.6 => /lib/i386-linux-gnu/libc.so.6 (0xf7986000)
/lib/ld-linux.so.2 (0xf7f1a000)
libdl.so.2 => /lib/i386-linux-gnu/libdl.so.2 (0xf7980000)
```

After this copy, running `./gmpublish_linux` no longer gave the error.

**Comment by Volantarius** [comment]
Awesome thank you!

**Comment by viral32111** [comment]
Sure thing, glad I could help 😄 

Also, according to the [`lib.so(8)`](https://linux.die.net/man/8/ld.so) man pages, instead of copying it to one of the standard system library directories, you can also just set the env var `LD_LIBRARY_PATH`, it works alot like the normal path env var (colon seperated list of directories).

> **LD_LIBRARY_PATH**
> A colon-separated list of directories in which to search for ELF libraries at execution-time. Similar to the PATH environment variable. Ignored in set-user-ID and set-group-ID programs.

**Comment by Volantarius** [comment]
Thanks alot! That make its alot easier to make sure everything is up to date!
