### ISSUE TITLE
NEXTBOT:BodyMoveXY also affects on gestures

### ISSUE THREAD

**Issue by ShadowBonnieRUS** [Facepunch/garrysmod-issues#4585]
### Details
Like wiki says about NextBot:BodyMoveXY():

`This sets the move_x and move_y pose parameters of the bot to fit how they're currently moving, sets the animation speed to suit the ground speed, and calls FrameAdvance.`

It also sets active gestures playback rate, because of which all gestures can play very fast and, for example, reload animation will play very fast.

### Steps to reproduce
1. Sets bot's locomotion desired speed to **300**.
2. Use **function ENT:BodyUpdate() self:BodyMoveXY() end**.
3. When bot moving, run **self:AddGesture(_ACT_HL2MP_GESTURE_RELOAD_SMG1 or other gesture_)**.
4. Look at gesture playback speed.

**Comment by robotboy655** [comment]
It doesn't, I have tested it with just completely removing SetPlaybackRate from BodyMoveXY(), as well as setting really low movement speeds, etc.

You have the power to change the gesture playback rate:
https://wiki.facepunch.com/gmod/Entity:SetLayerPlaybackRate

The issue of them playing too fast is due to this:
https://github.com/Facepunch/garrysmod/blob/650cc62738094c1641b46f426cb3b360d241aca2/garrysmod/gamemodes/base/entities/entities/base_nextbot/sv_nextbot.lua#L76

It makes layered sequences play 2x as fast as they should be, because BodyMoveXY already calls FrameAdvance(). I will get this fixed.
