### ISSUE TITLE
WEAPON:OwnerChanged() is not called Clientside for the first spawn and first drop.

### ISSUE THREAD

**Issue by MeteorTheLizard** [Facepunch/garrysmod-issues#4639]
As the title states, when a weapon is spawned through the spawnmenu only the SERVER registers the owner change and upon dropping the weapon for the first time only the SERVER registers it as well. If the weapon was dropped once everything works as intended, both realms register the owner change on pickup and drop afterwards.

Pseudo code to replicate issue:
```lua
if CLIENT then
	function SWEP:Holster()
		-- CODE TO FIX VIEWMODEL HERE
	end
end

-- CLIENT and SERVER
function SWEP:OwnerChanged()
	if CLIENT then self:Holster() end

	print("OWNER CHANGED: " .. tostring(self.Owner))
end
```

Video presentation of the issue: https://streamable.com/9rnkpc

```
] version
Protocol version 24
Exe version 2020.03.17 (garrysmod)
Exe build: 19:51:57 Aug  7 2020 (7891) (4000)
GMod version 2020.08.18, branch: unknown, multicore: 1
Windows 32bit
```
This happened on a Local Server (Ingame LAN). Untested for dedicated servers.

**Comment by robotboy655** [comment]
Let's see if anything breaks.

**Comment by robotboy655** [comment]
Had to undo one the fixes because it does indeed cause problems. We will need to figure out a better way to call to Lua on entity creation clientside. Kinda don't want to queue the callbacks, but it does seem to be the only option. Not reopening because the issue is identical to https://github.com/Facepunch/garrysmod-requests/issues/324 in nature, which is still open.
