### ISSUE TITLE
SRCDS Crash with 64bit due to lua_shared.dll

### ISSUE THREAD

**Issue by G-Force007** [Facepunch/garrysmod-issues#4716]
### Details
We are experiencing crashing with srcds and lua_shared.dll due to usage of 64bit version of Garry's Mod. This issue was temporarily resolved in a previous update (rough date ~July 10th), however updating to the latest version via the steamcmd tool has brought the crashes back.  This usually occurs during start up/initialization/map change and loops over a few times until the server successfully starts.

Server specs:
i7-7700k, 64GB ram, Windows Server 2016 64bit edition.
GMOD version: 201023
Start up parameters: `-condebug -console -game garrysmod -tickrate 33 -maxplayers 100 +map rp_newexton2_v4h +gamemode darkrp +r_hunkalloclightmaps 0 +log on +sv_logfile 1 +host_workshop_collection 774079751 +sv_setsteamaccount XXX`

Original issue was thought to be related to MySQLOO extension, report can be found here: https://github.com/FredyH/MySQLOO/issues/45 (Willox originally read the DUMP file and confirmed it's related to lua_shared GC: https://github.com/FredyH/MySQLOO/issues/45#issuecomment-612629494) Not sure if it's exactly the same issue...

Issue goes away with 32bit version, but we experience other issues relating to memory usage and can no longer make use of MySQL 8.0. I will email robotboy the crash dumps over the previous days to his email address.

Screenshot: https://dl.dropboxusercontent.com/s/chi9ho4y2vt301m/mstsc_7l4zt9MkXt.png

### Steps to reproduce
The issue is quite difficult to reproduce. It occurs spontaneously and as mentioned, occurs usually during server start/map change.

**Comment by robotboy655** [comment]
There's like 3 different crashes here, very likely the one you are talking about is due to the binary module for whatever reason. Have you tried running without it? Nothing about Lua(JIT) has changed in the past months.

Knowing when **exactly** this has started happening again would also be helpful, if it was indeed resolved before which I doubt. Was it working fine just after the October update? Also there were no changes around 10th of July 2020, the 2 closest commits on x64 beta are 26th of June and 17 of July, latter of which added a bunch of changes.

Also x64 was just updated, you may want to update.

**Comment by G-Force007** [comment]
Before June was unstable. The 26th of June update was stable, 17th of July update brought back the crashes. Looks like we updated in September which was the 17th of July release.

I have tried the latest update but we are still facing the same crashes, I will forward these dump files to your email again.

**Comment by robotboy655** [comment]
Does your server use Nextbots? It really doesn't help that you waited this long to report this, its nearly impossible to figure out what caused it now, with hundreds of changes during and since those dates.

**Comment by G-Force007** [comment]
Nope, we do not use nextbots.

**Comment by robotboy655** [comment]
Closing as stale.
