### ISSUE TITLE
Garry's Mod for linux doesn't include fgd files.

### ISSUE THREAD

**Issue by EntityinArray** [Facepunch/garrysmod-issues#4742]
### Details
I had an idea of making Garry's Mod maps under linux. So i downloaded Source SDK, ran hammer from wine and made a hammer configuration for Garry's Mod, but i noticed that Garry's Mod for linux didn't had fgd files in the bin folder.
Is it possible to ship all fgd (and other source engine related files) with Linux versions of the source games too?

### Steps to reproduce
1. Open bin folder of any source engine game for linux
2. Notice that .fgd files and all other files that are usually shipped with Windows version of the game are missing

**Comment by EntityinArray** [comment]
This shoudn't be intentional. Having to download windows version of the game and extracting files form it each update is annoying.

**Comment by MARK2580** [comment]
> This shoudn't be intentional. Having to download windows version of the game and extract files form it each update is annoying.

Just install windows and stop messing with emulators.

**Comment by robotboy655** [comment]
It is intentional because Linux version of the game does not ship Hammer, so it would be pointless to ship `.fgd` files. Not to mention SourceSDK's Hammer/compilers are inferior to Garry's Mods.

Use whatever method people are using to install windows versions of Steam games on Linux if you want to use the mapping tools on Linux. Install a VM if you have to,
