### ISSUE TITLE
Player:IsSprinting function doesn't check proprely is a player runs really

### ISSUE THREAD

**Issue by FlorianLeChat** [Facepunch/garrysmod-issues#4754]
### Description ℹ️ 

I don't really know how this function was designed but it seems to return `true` if the player presses the **SHIFT** key (to run) and if not, `false`. This can be annoying because it doesn't check if the player is actually running.
For example, in a stamina system, using this function without checking the player's velocity is totally useless and gives bad results (the stamina could drop even if the player doesn't move and just presses his **SHIFT** key).
So for now, I use [this function](https://github.com/NebulousCloud/helix/blob/e399f227cf38f4ed04aaccdd8278122cb81f46b7/gamemode/core/sh_util.lua#L1062-L1067) created by the HELIX gamemode and it works perfectly well.

### Game info 💻 

```
Protocol version 24
Exe version 2020.10.14 (garrysmod)
Exe build: 20:52:32 Oct 12 2020 (7891) (4000)
GMod version 2020.10.23, branch: unknown, multicore: 1
Windows 32bit
```

### Tests 🧪 
✔️ Tested in a singleplayer/dedicated server.
✔️ Tested in the dev/default branches.
✔️ Tested with `-noaddons -noworkshop` launch parameters.

### Steps to reproduce
Use this code and hold SHIFT key:

```lua
hook.Add("Think", "Github_Test", function()
    print(Entity(1):IsSprinting())
end)
```

**Thank you in advance.**

**Comment by LeQuackers** [comment]
You're pretty close. ```Player:IsSprinting``` returns whether ```m_fIsSprinting``` is true or not. ```m_fIsSprinting``` is only supposed to be set if shift is down and you're allowed to sprint. If you want to check if a player is actually sprinting yeah, you have to check their velocity and ground entity.

GMod probably uses a variant of [```CHL2_Player::HandleSpeedChanges```](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/hl2/hl2_player.cpp#L481-L539). GMod seems to use ```CHL2_Player::StartSprinting/Walking``` and ```CHL2_Player::StopSprinting/Walking``` because ```m_fIsSprinting``` and ```m_fIsWalking``` change, but the only thing sprinting reacts to is whether you're crouching or not and you can slow walk while crouching, so [```CHL2_Player::CanSprint```](https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/game/server/hl2/hl2_player.cpp#L1167-L1174) probably isn't used and the walk logic is modified.

Also, it's a bit off topic but why is there no ```Player:IsWalking``` method?

**Comment by FlorianLeChat** [comment]
It may also be interesting to bind a new method to detect if a player is walking.

Thanks also for your explanation, so it's not a bug as it looks pretty intentional. I leave this issue open if it can be improved by Rubat or Kefta, or close it if nothing is going to be changed.

**Comment by robotboy655** [comment]
Yeah, its intentional to be this way, I have no plains on changing behavior of this function.
