### ISSUE TITLE
Why is 0b (binary notation) only available on x64 branch?

### ISSUE THREAD

**Issue by Cheatoid** [Facepunch/garrysmod-issues#4835]
As the title says; A question out of curiosity. Not an issue.

A little extra story:
I found this little trick sometime ago... I actually rely on this trick in [starfall scripting](https://github.com/thegrb93/StarfallEx) in order to check whether a client is running x64 branch or not, it does the job much more reliably`*` 😄

`*` "more reliable" as compared to glua scripting, where someone could simply override their global `BRANCH="rekt"`

**Comment by thegrb93** [comment]
jit.version will tell you why

**Comment by Vurv78** [comment]
why are they on different luajit versions anyways?

**Comment by thegrb93** [comment]
One of them supports x64 and the other does not I think

**Comment by Kefta** [comment]
> One of them supports x64 and the other does not I think

I thought this comment was wrong but I asked Willox and it's correct - it's specifically because gc64 is only available after LuaJIT 2.1. It's necessary because LJ requires allocs under 4gb (max 32 bit address range) for them to be cleared properly, "and things such as the steam overlay were allocating huge buffers there which was exausting luajit of memory before it even got close to 1GB".
