### ISSUE TITLE
Entity:GetMaterials() performance issue

### ISSUE THREAD

**Issue by FredyH** [Facepunch/garrysmod-issues#4853]
### Details

Running Entity:GetMaterials() on _some_ entities/models takes an unreasonably long time. I have been unable to figure out exactly which types of models seems to cause this, but it seems to be only more "complex" models that cause this issue (although not all complex models do).
The main issue arises from the fact that the performance is consistently bad for models that are affected (i.e. every call). Precaching the model does also not seem to help in any way.

For example, almost all the HL2 citizen models have this issue, but Alyx does not. Neither do CS ragdolls.
It is not just ragdolls either, some cars are affected too (for example seemingly all tdmcars) and some regular models are too (for example models/props_lab/monitor02.mdl).

The time it takes for the function to complete seems to scale with the amount of sub materials, but not all models with a lot of submaterials cause the issue.

This should be fixed because when replacing sub materials, you first need to call Entity:GetMaterials() to know the index at which materials have to be replaced using SetSubMaterial.

I think this is issue the same as the (now closed) issue #1637

### Steps to reproduce

I wrote a small piece of code that you can use to benchmark this behaviour by just looking at any model and running the lua file.
```LUA
local ent = LocalPlayer():GetEyeTrace().Entity
if (!ent) then
    print("Look at an entity to run this")
    return
end
print("Running script for model: ", ent:GetModel())
local start = SysTime()
local count = 1000
for i = 1, count do
    ent:GetMaterials()
end

local duration = SysTime() - start
local msDuration = duration * 1000 / count
print("All calls took ", duration .. " seconds")
print("One call of ENT:GetMaterials() took ", math.Round(msDuration, 2) .. " ms")
```

**Comment by Kefta** [comment]
It is almost certainly due to CStudioRenderContext::GetMaterialList: https://github.com/VSES/SourceEngine2007/blob/master/src_main/studiorender/studiorendercontext.cpp#L1690

It's an O(count * numcdtextures) worst case (count = 256 max for the Entity:GetMaterials binding) with blocking paths (checking the filesystem) and some potentially huge stackallocs, though GMod does specifically prevent that in some places. I'm not going to investigate this too much further without taking care of https://github.com/Facepunch/garrysmod-issues/issues/3216 alongside it with a pretty hefty rewrite of this part of the model library since it's full of weird legacy behaviour and poor design (ex. https://github.com/VSES/SourceEngine2007/blob/master/src_main/engine/modelloader.cpp#L3907-L3913).

**Comment by FredyH** [comment]
It is really odd that this is not caching the results. You'd expect precaching/loading the model to do exactly that. It has to know the materials in order to draw the model and it certainly does not cause this long every frame to lookup the materials. Am I missing something here?

In the meantime wrote an easy lua caching implementation that seems to work and does not cause stutters (after the first execution).
```LUA
_OldGetMaterials = _OldGetMaterials or ENTITY.GetMaterials -- ENTITY metatable

_CachedMaterialTable = _CachedMaterialTable or {}

function ENTITY:GetMaterials()
	local model = self:GetModel()
	if (!model) then
		return _OldGetMaterials(self)
	end
	if (!_CachedMaterialTable[model]) then
		_CachedMaterialTable[model] = _OldGetMaterials(self)
	end
	return _CachedMaterialTable[model]
end

```

**Comment by robotboy655** [comment]
> You'd expect precaching/loading the model to do exactly that. It has to know the materials in order to draw the model and it certainly does not cause this long every frame to lookup the materials. Am I missing something here?

Models use the same code as Entity:GetMaterials(), but only once, the data is then cached for rendering per LOD.

The actual issue here is that it is trying to load missing materials, over and over again. This basically affects all models with more than 1 `$cdmaterials` command. This should now be fixed on the `dev` beta.
