### ISSUE TITLE
Minidumps are not generated

### ISSUE THREAD

**Issue by Flapchik** [Facepunch/garrysmod-issues#4871]
Hello. I am using Linux. My TTT server crashes very often. This happens most often when the round is changed, but it also happens during the round. I want to analyze minidumps but they are not being generated. I added the "-dumplongticks" variable to the startup line specifically to create a minidump. In the console, I get a message about a generated minidump, but no minidump is actually being generated.
I won't be able to fix the crash issue while minidumps are missing. Please suggest a solution.

Console...
```
Long tick after tick 40100. Writing minidump #1 (5 total).
Long tick after tick 40100. Writing minidump #2 (6 total).
Compressing fragments (11036 -> 5936 bytes)
Long tick lasted about 0.2 seconds.
```

debug.log

```
CRASH: Ср мар 17 18:42:39 MSK 2021
Start Line: ./srcds_linux -game garrysmod -strictportbind -ip 192.168.0.104 -port 27017 -tickrate 66 +host_workshop_collection *** -authkey *** +clientport 27007 -steamport 28017 +tv_port 27022 +gamemode terrortown +map ttt_tinytown +sv_setsteamaccount ***+servercfgfile server.cfg -maxplayers 28 -allowdebug -debug -condebug -dumplongticks -pidfile srcds2.pid
End of Source crash report
----------------------------------------------
```

By this time, 270 minidumps should have been generated.

**Comment by robotboy655** [comment]
If it can't write the file (it will have `longtick` in its name), it's probably due to file permissions on your end.

**Comment by robotboy655** [comment]
Oh yeah looking at the code it will never write a minidump because that was never implemented for non linux operating systems.

`-dumplongticks` is not meant to enable minidumps, it's a debugging tool for well, long ticks. It's not related to generic crashes you might get.

A generic crash on linux (segfault) should create a core dump (depending on your OS settings) which you should be able to plug into `gdb` to get a stack trace.

https://developer.valvesoftware.com/wiki/Debugging_under_Linux

You can also switch your server to the `x86-64` beta branch which WILL generate `.dmp` files in the crashes/ folder which I can use to generate the core dump and see the stack trace at crash time.

**Comment by thegrb93** [comment]
`sudo ulimit -c unlimited` to enable cores in linux

**Comment by Flapchik** [comment]
> `sudo ulimit -c unlimited` 

and

> 'x86-64' 

Did not work. Minidumps are not generated. I will try further.
