### ISSUE TITLE
Unblacklist Our Server

### ISSUE THREAD

**Issue by anyome** [Facepunch/garrysmod-issues#4949]
@robotboy655 
Hey, i'm reaching to  you here since you didn't get my Message

Can we get unblacklisted ? Please from Gmod Browser 

It's have been 1 Week now

Here is our IP :149.202.65.116

**Comment by YouLoseLordSaw** [comment]
I'll take the liberty of answering you Lord Saw, your blacklist is entirely justified? 

You stole servers for more than 7 years, you had fun to DDoS many servers to make them sink so that you you function except that the air 2016 is finished my small.

You stole from the INFINITY community who reported you to Facepunch which caused your blacklisting.

It's over for you, you don't have many options left except to close TeamFrench.

**Comment by FlorianLeChat** [comment]
As Rubat has already said on the Discord: https://wiki.facepunch.com/gmod/Server_Operator_Rules#myserverwasblacklistedwhatdoido
