### ISSUE TITLE
util.JSONToTable crash

### ISSUE THREAD

**Issue by thegrb93** [Facepunch/garrysmod-issues#4976]
`util.JSONToTable("{\"\":":rep(50000) .. "{}" .. "}":rep(50000))` seems to stack overflow or something

**Comment by FlorianLeChat** [comment]
This isn't related to the 15000 keys limit mentioned on the wiki?

**Comment by robotboy655** [comment]
Nah, it is just stack overflows. I kinda fixed it, but it will throw double Lua errors when hitting a hard limit of depth, I couldn't fix it properly because there are other apparent stack overflows somewhere in LuaJIT and Steam.dll somehow gets in the stack trace, so I can't really debug it unfortunately.

**Comment by robotboy655** [comment]
Oh, and I have not tested JSON expot (TableToJSON), although I suspect you'd hit Lua's stack limit before being able to crash the game.

**Comment by thegrb93** [comment]
I've got to test that when I get time. I suppose the code would be:

```lua
local a = {}
for i=1, 50000 do
    a = {a}
end
util.TableToJSON(a)
```

**Comment by thegrb93** [comment]
@robotboy655 it does crash

**Comment by robotboy655** [comment]
Should be also fixed.
