### ISSUE TITLE
Entity:SetKeyValue bug

### ISSUE THREAD

**Issue by wolfestridershooter** [Facepunch/garrysmod-issues#5020]
### Details:
Entity:SetKeyValue doesn't work on the material_modify_control entity.

### Steps to reproduce:
Make init.lua in the autorun folder in a new addon and write:
```lua
function ModelTickFix()
	for _, ent in ipairs( ents.FindByClass( "material_modify_control" ) ) do
		if ( ent:GetInternalVariable( "materialName" ) == "models/vortigaunt/vortigaunt_blue.vmt" ) then
			ent:SetKeyValue( "materialName", "models/vortigaunt/vortigaunt_blu1.vmt" )
		end
	end
end
hook.Add( "Tick", "ModelTickFix", ModelTickFix )

hook.Add( "EntityKeyValue", "FindEntMat", function( ent, key, value )
	if ( key=="materialName" && value=="models/vortigaunt/vortigaunt_blu1.vmt" ) then
		print(ent)
		print(key)
		print(value)
	end
end)
```

Then start ep1_citadel_00 and wait until the vortigaunts start spawning in, then look in the console. If Entity:SetKeyValue worked on material_modify_control it should print "models/vortigaunt/vortigaunt_blu1.vmt" in the key section but instead nothing gets printed showing that the KeyValue was not changed.

### Version:
Protocol version 24
Exe version 2021.06.09 (garrysmod)
Exe build: 10:34:03 Jul  6 2021 (8277) (4000)
GMod version 2021.07.19, branch: x86-64, multicore: 1
Windows 64bit

**Comment by robotboy655** [comment]
There's nothing wrong with Entity.SetKeyValue, only with your code.

First of all, that entity has no internal variable named `materialName`. It.s `m_szMaterialName` as seen in `Entity.GetSaveTable`'s output. Key value names are NOT the internal variable names. Secondly, for some weird reason you are using `Tick` instead of `EntityKeyValue` to check when the value changes. Just use `EntityKeyValue` in the same way you already use it to test if the change worked.
