### ISSUE TITLE
NEXTBOT:IsAbleToSee bug

### ISSUE THREAD

**Issue by FirstDeltaa** [Facepunch/garrysmod-issues#5051]
### Details
I recently found a issue with the NEXTBOT: IsAbleToSee (https://wiki.facepunch.com/gmod/NextBot:IsAbleToSee) function. On some maps, with Navmesh and regardless of range and FOV settings, false is almost always returned. The only exception is when you stand right in front of the NPC. The same issue occurs with the NEXTBOT: OnEntitySight (https://wiki.facepunch.com/gmod/NEXTBOT:OnEntitySight) function.

### Steps to reproduce
Here are 2 maps on which to reproduce the bug:
- https://steamcommunity.com/sharedfiles/filedetails/?id=2507630538
- https://steamcommunity.com/sharedfiles/filedetails/?id=2407272308

I used this code (modified template from gmodwiki):
- https://pastebin.com/dnbDzUTM

A short video:
- https://www.youtube.com/watch?v=YT8qwL93eVw

Thank you for your attention

**Comment by T-Rizzle12** [comment]
I know what is happening here. IsAbleToSee uses CNavArea:IsPotentiallyVisible( CNavArea ) before doing the trace check. This is done since it uses the precomputed visibility data before doing the expense trace check. The reason why it breaks on some maps is because the map or navmesh creator choose not to compute the visibility data or they completed too short of a distance and as a result causes the error you are experiencing. The reason why the bot can still see you when you stand right in front of it is because you are usually standing in the same CNavArea as the bot and IsPotentiallyVisible will always return true of both CNavAreas are the same.

An easy fix is recomputing the visibility data of the map.
1. Make sure nav_max_visiblity_distance = 6000
2. Make sure nav_quicksave != 2
3. Run nav_analyze
