### ISSUE TITLE
Add Vulkan (DXVK) support

### ISSUE THREAD

**Issue by ghost** [Facepunch/garrysmod-issues#5131]
Vulkan (DXVK) support [was added](https://www.gamingonlinux.com/2021/06/left-4-dead-2-updated-with-vulkan-support-thanks-to-dxvk/) in the Left 4 Dead 2 update for the GNU/Linux native port. I also suggest doing it in Garry's Mod. Why is this needed in Garry's Mod? Because ToGL reduces the DirectX version to 9, which causes the graphics to be lowered and some graphic effects disappear (also, ToGL itself does not render some effects). It can also get rid of some graphical glitches (or, on the contrary, add them).

**Comment by Unicod3r** [comment]
So empty here...

**Comment by razorzinho** [comment]
+1 on this. Please add it, Linux Port is a big joke currently to be honest, and to play 64bit version, we need to do a lot of tinkering outside the game because Chromium stuff is not downloaded automatically. That's also a good opportunity to fix this and wipe out the need of using https://github.com/solsticegamestudios/GModCEFCodecFix
