### ISSUE TITLE
Error in spawnmenu

### ISSUE THREAD

**Issue by mark27205** [Facepunch/garrysmod-issues#5235]
### Details
Error is thrown.
[ERROR] RunConsoleCommand: Command is too short, bailing! ()
  1. ActivateTool - lua/includes/modules/spawnmenu.lua:111
   2. DoClick - gamemodes/sandbox/gamemode/spawnmenu/toolpanel.lua:131
    3. unknown - lua/vgui/dlabel.lua:237

### Steps to reproduce
Go to Physic gun settings in the Spawnmenu.
Occured in Chromium x64

**Comment by BullyHunter32** [comment]
Went to go fix this myself, fixed it, was about to make a PR but then realised the issue was already fixed by Rubat himself.

Not entirely sure how the gmod repo works exactly in relation to the actual game itself, but try validating game files, if that doesn't work then wait for the next update I guess.
