### ISSUE TITLE
Player movement on ladder entities is not predicted

### ISSUE THREAD

**Issue by its-jaek** [Facepunch/garrysmod-issues#5267]
Players moving on the entities func_ladder and func_useableladder have prediction errors. Tested in Sandbox with the maps cs_office and gm_construct on a listen server.

Used net_fakelag 300 and cl_showerror 1.

The first video provided is func_ladder on cs_office and the second video provided is func_useableladder on gm_construct. Also provided are examples of player movement on func_ladder entities being predicted on Counter-Strike: Source and Counter-Strike: Global Offensive, both on cs_office.

https://user-images.githubusercontent.com/15711300/177094374-e922f8b0-f29d-4efd-9255-ec3cf6e23bc2.mp4

https://user-images.githubusercontent.com/15711300/177094353-f397e545-8977-4522-9b68-f592f76b83e5.mp4

https://user-images.githubusercontent.com/15711300/177095470-f6951b06-8300-407e-bd0d-c2b448dcbfea.mp4

https://user-images.githubusercontent.com/15711300/177094271-5e9d303e-d736-449e-b3c0-cbeb94a20ed3.mp4

**Comment by Headshotz** [comment]
I've tested, so seem CGameMovement::FullLadderMove isnt called in clientside because of HL2 GameMovement override that function and only run serverside code because of single player? could make them to use the default CGameMovement functions, if server and client are in multiplayer not single player?

I'm not sure why is that line is it cause to break the predict?

https://github.com/VSES/SourceEngine2007/blob/43a5c90a5ada1e69ca044595383be67f40b33c61/se2007/game/shared/hl2/hl_gamemovement.cpp#L525

**Comment by robotboy655** [comment]
That does seemingly improve prediction on ladders.
