### ISSUE TITLE
GMod crashing when launching some maps [x86-64 | Linux]

### ISSUE THREAD

**Issue by Ohio2** [Facepunch/garrysmod-issues#5271]
### Details
Game freezes at loading resources or loading world (3/4 way done), expected behaivour is to just complete map loading
Branch: x86-64
Logs are attached in the post.
[adaa38b3-8461-4b4b-dd72a89a-964c0ea1.txt](https://github.com/Facepunch/garrysmod-issues/files/9066674/adaa38b3-8461-4b4b-dd72a89a-964c0ea1.txt)
OS: Arch
### Steps to reproduce
Join some map (e.g. de_dust2)
### NOTE
The game is CEF patched

**Comment by WhatAreThose** [comment]
> Game freezes at loading resources or loading world
This happened to me one time on a map called `BSmod KillMove Testing Map`. When I first subscribed to it, and launched it, it got stuck on "Loading World" and froze. After I restarted GMod, however, it seemed to work just fine.

I think it's because some bits of the map have not been installed properly (like a post-install of the map) so when you restart, that post-install is called on startup and it fixes it.

**Comment by Ohio2** [comment]
Not really, it has nothing to do with the post-install.

**Comment by Ohio2** [comment]
UPDATE: All maps now crash.

**Comment by Ohio2** [comment]
My autoexec broke things, huh, well, some option was not supported, i will add the ignore tag in the title
@robotboy655 hopefully you did not start hunting down the issue at hand. Thank you for your cooperation
