### ISSUE TITLE
lua_error_url persists on clients after leaving the server

### ISSUE THREAD

**Issue by Earu** [Facepunch/garrysmod-issues#5348]
In our community we've been experimenting with the `lua_error_url` convar to get an error reporting system. However we were getting errors (only clientside) from addons and scripts that we just don't have on any of our servers. So as it is, it seems that `lua_error_url` persists on other after disconnecting and then that the clients send us the clientside errors of other servers they join... Which is well junk to us and to anyone trying to make practical use of that system.

**Comment by robotboy655** [comment]
It ***IS*** being reset when starting a new singleplayer/local multiplayer game.

It will also be reset when leaving the server in the next update due to changes to how replicated convars work.
![image](https://user-images.githubusercontent.com/3299036/211901754-264b5905-5c73-47dc-9c36-0bc9fe8b06ae.png)
