### ISSUE TITLE
string.lower weird behaviour

### ISSUE THREAD

**Issue by Askastaa** [Facepunch/garrysmod-issues#5395]
### Details
i made my own admin command and i made a function to find players on my server with couple if statements. To make it easier to find them i force string.lower on the given name. However if a user joins and lets say his name is "Test²" string.lower just returns a error because of the "²" in his name.

It also is a given note on the gmod wiki page, However could you just make it skip the non english UTF-8 characters? so it returns "test" if you string.lower("Test²")

### Steps to reproduce
just have non english UTF-8 characters in your name.

**Comment by FlorianLeChat** [comment]
This function is not designed to be used on non-English characters and using a UTF-8 character set, a note on Wiki already explains that: https://wiki.facepunch.com/gmod/string.lower. Some gamemodes like [Helix](https://github.com/NebulousCloud/helix/blob/de44cf9a6d536148a2b6fa3bb0f53c49dabcb343/gamemode/core/libs/thirdparty/sh_utf8.lua) use third party libraries (not included with Garry's Mod) to resolve this issue.

**Comment by CornerPin** [comment]
This function can't corrupt the string because valid non-ASCII UTF-8 characters never contain bytes in the range of 0x00-0x7F.
![image](https://user-images.githubusercontent.com/7669876/214430470-c3b43db0-ca36-4a36-9f74-64546531d8c7.png)
Are you printing the string to the terminal? The font being used might not have this character.
