### ISSUE TITLE
Mounted files using `game.MountGMA` are not visible in `LUA` game path

### ISSUE THREAD

**Issue by PrikolMen** [Facepunch/garrysmod-issues#5481]
### Details
After mounting GMA from `data/` the game can see the file in the game path `GAME` but any attempt to check the existence of the same file in `LUA` is guaranteed to fail.

### Steps to reproduce
```lua
-- in this example i will try to mount gma with this files: https://github.com/Pika-Software/http-content
local ok, files = game.MountGMA( "data/path/to/any/gma/with/lua/file.gma.dat" )
print( "gma mounted status: ", ok, "files count: ", #files )
-- gma mounted status: 	true	files count: 	2

PrintTable( files )
--[[
1	=	lua/packages/http-content/init.lua
2	=	lua/packages/http-content/package.lua
--]]

print( SERVER and "server" or "client", file.Exists( "packages/http-content/init.lua", "LUA" ) )
--[[
server	true
client	false
--]]

print( SERVER and "server" or "client", file.Exists( "lua/packages/http-content/init.lua", "GAME" ) )
--[[
server	true
client	true
--]]

local files, _ = file.Find("packages/http-content/*", "LUA" )
print( "files:" )
PrintTable( files )

--[[
files:
1	=	init.lua
2	=	package.lua
files:
--]]

local files, _ = file.Find( "lua/packages/http-content/*", "GAME" )
print( "files:" )
PrintTable( files )

--[[
files:
1	=	init.lua
2	=	package.lua
files:
1	=	init.lua
2	=	package.lua
--]]
```

**Comment by robotboy655** [comment]
If I understood this correctly, they are only missing clientside which makes perfect sense. Clientside, the `LUA` path will only include files that are `AddCSLuaFile()`.

**Comment by PrikolMen** [comment]
Yes, but mounted to the client file is important to check for existing, using `GAME` is not safe, because the player can trivially swap files in his game directory and run any code with my addon...

**Comment by robotboy655** [comment]
There is no way for the game to know which files should be exposed clientside unless you mark them specifically with `AddCSLuaFile()`. Otherwise issues like [this](https://github.com/Facepunch/garrysmod-issues/issues/5471) will happen.

In multiplayer clientside Lua files are only loaded from the string table which is populated by `AddCSLuaFile`. Adding hacks for this does not seem like a good idea, and will just cause more issues that it solves.

Addon content should take precedence over local loose files in mounting order, see https://wiki.facepunch.com/gmod/File_Search_Paths

**Comment by PrikolMen** [comment]
Okay, I'll have to think of something else, but thanks for the answer anyway.
