### ISSUE TITLE
PrecacheParticleSystem() causing a print to console despite the Precache attempt being successful.

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#5491]
**Game Version is 64 Bit Beta, the recent June update, however this issue happens in all versions of the game from what I tested.**

Using PrecacheParticleSystem right after a map is loaded via an "InitPostEntity" hook causes the text to be printed to the console for some reason, despite how In-Game the particles work perfectly fine when creating them in the client realm.

**NOTE: Placing the PrecacheParticleSystem calls outside of the InitPostEntity function and just below game.AddParticles(X) does NOTHING to fix this.**

An example being that it details certain weapon effects apparently failing to load, despite being able to use those weapons (and the particles are created client side might I add) with no issues at all.

This problem isn't exactly a big issue, it doesn't break the game or cause any real problems it's just a nit pick since it fills out the console with a bunch of useless information.

**Image of the errors:**
![image](https://github.com/Facepunch/garrysmod-issues/assets/4176672/86fc2f61-7c1b-429e-acf4-cbfbc462ea8d)

**Image of the effects clearly working:**
![image](https://github.com/Facepunch/garrysmod-issues/assets/4176672/3fc0cc9e-3f84-47da-8d4a-3c337f3f9218)

**Goals to replicate I think?:**
> Inside of a gamemodes Shared.lua file, slap an include in there for a file located in the same folder or a sub folder.
> 
> Lets just call it ParticleIncludes.lua
> 
> Inside that file add the game.AddParticles(X)
> 
> Below this add a function hooked to InitPostEntity that contains the PrecacheParticleSystem(X)'s you want to run, obviously with VALID particles to load and include.

If this issue is something that can't be fixed, or if you need anything else from me to help solve this then please let me know.

**Comment by robotboy655** [comment]
This is happening because of the particle precache stringtable. Basically when you "precache" a particle system on the server, it updates the string table which gets networked to clients, but at that point your client did not yet call `game.AddParticles()` so it cannot find the particles to precache. THEN your clientside code runs and precaches them for real.

I do not see a way to fix this from the game's side besides just not precaching particles when the string table changes, which would probably break shit. You'd just have to be mindful of this when precaching particles on the server.
