### ISSUE TITLE
Fix crash from reading flexes after 96

### ISSUE THREAD

**Issue by Wiimeiser** [Facepunch/garrysmod-issues#5633]
Since 2022 models with more than 96 flexes crash the game when trying to generate a preview model. Examples of such models include, but are not limited to: 
https://ponysfm.com/the-barrel-twins
https://steamcommunity.com/sharedfiles/filedetails/?id=3020232826&searchtext=crash
The model then renders with broken faces when the game is reloaded, assuming any attempts to render them actually succeeded.

Proper error handling should be used here. Though I'm not sure what the fallback would be in this case.

(Also, the flex limit being lowered needs to be made more well known in the community. Barely anyone seems to be aware that it happened. It _was_ mentioned in the changelog, but half of the comments there are talking about the _Yes I am the Real Garry_ achievement and none mention the Faceposer)

**Comment by robotboy655** [comment]
Cannot reproduce crashes with that GMod addon on `dev` beta. Here's every single spawnicon generated, and every single model spawned:
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/4a08de1f-124b-42a9-97bf-3885af08bfeb)
No holes in faces either.

The pony models also work correctly in my testing:
![image](https://github.com/Facepunch/garrysmod-issues/assets/3299036/8a496760-be7b-4f6c-afd6-8f6e2d0f2ff7)

You can use this article (https://wiki.facepunch.com/gmod/Crash_Reporting) to try to troubleshoot simple issues as well as read information on where to find a crash dump and send one or two from the crashes you are having with these models my way. Emails is in my profile if you want to use that.

The flex limit was not lowered. What was lowered is the amount of convars in the faceposer, because the ones after 96 do nothing. You can test this yourself by editing the value of 96 back to 128 and see that those extra sliders still do nothing. I will look into making it more clear in the faceposer UI when this limit is reached by the model.
