### ISSUE TITLE
GMAs with txt files don't mount

### ISSUE THREAD

**Issue by DarthTealc** [Facepunch/garrysmod-issues#5648]
### Issue
Recently in beta branches, Gmod has stopped mounting workshop addons containing .txt files. Apparently this is due to a security exploit being patched. The problem is some addons are never going to get updated, and some use .txt files for legitimate purposes such as TTT rearm scripts. Right now this prevents the addons from being used at all. See #next-update on the discord for more discussion about this issue.

### Suggested solution
Mount the GMA but drop the .txt file. This will allow some addons to keep working, they just won't be able to access the .txt file as it hasn't been mounted. For example TTT maps will be mounted but will not have their rearm scripts, servers can still use the maps. Any addons that explicitly require a .txt file to function will still need to be updated.

**Comment by FlorianLeChat** [comment]
I totally agree. There are so many old and still popular gamemodes which are no longer maintained and will probably not be updated for a long time (if ever).

**Comment by robotboy655** [comment]
I have made some changes to alleviate this issue, but do **NOT** rely on this broken behavior. It will be removed in the future.

Use `data_static` inside `.gma` files for generic data storage.

**Comment by Kefta** [comment]
What is TTT supposed to do since txt inside maps/ is an explicit feature?

**Comment by robotboy655** [comment]
The maps could embed the `_ttt.txt` file into the BSP itself, or TTT should be updated to also check `data_static/`

**Comment by mgetJane** [comment]
ttt is a very old gamemode and i don't think it's reasonable at all to expect all of the decade+ of content for it to be updated

what is the actual nature of the security exploit and does it really need an all-or-nothing solution?

if so, can't the game have a sort of exemption for addons created before a few months ago?

can't gma files just be loaded while ignoring the non-whitelisted txt paths instead of preventing the addon from loading altogether?
(if it just ignored the txt files, then ppl can potentially create addons that patch old content to work with the new restrictions)

**Comment by Kefta** [comment]
I think txt files in maps/ should at least be whitelisted. There are no exploits there and is in line with both CS:S and TTT tradition.
