### ISSUE TITLE
Script file isn't loaded up from .bsp file

### ISSUE THREAD

**Issue by skate6788** [Facepunch/garrysmod-issues#5668]
Players reports me that on my maps custom vehicle doesn't work and it crashes the game. One of the newest update broke the mechanic with the loading .txt from script files packed into .bsp.

**Comment by Vinzuerio** [comment]
#5672 but also this crashes the game and **server**

Also to extend that files that currently effected:
```
detail.vbsp
scripts/vehicles/*.txt <- can cause server/game crash
materials/*.raw  (color correction)
```

**Comment by robotboy655** [comment]
I will allow vehicle scripts and color correction files.

`detail.vbsp` is never used by the game, only during map compile, so there's no reason to allow it as far as I can tell.
Correct me if I am wrong, but with examples versus TF2 or HL2 or something.

**Comment by Vinzuerio** [comment]
Tested on main 64-bit branch (as well as server, windows & linux) vehicle scripts & color correction seems working correctly now and no crashes (32-bit should be working anyway)

Im not sure why those `detail.vbsp` were inside my maps but this probably due to my automatic bsp packer, i'll exclude them in the future

Anyway thanks for the update!
