### ISSUE TITLE
The latest update broke the entity limit

### ISSUE THREAD

**Issue by Soldier-Leader** [Facepunch/garrysmod-issues#5776]
The situation: ColdSaturNight had created the ai_sevastopol_station map (https://steamcommunity.com/sharedfiles/filedetails/?id=3129319860), which, despite its considerable size, managed to fit within the GMod limits and worked seamlessly in the Alien: Isolation gamemode it was intended for. However, starting from January 18th, GMod began deleting entities upon launching the map in its mode, indicating in the console that the limit of 8196 objects had been reached - a problem that hadn't existed before the update. The number of deleted entities in the console was counted to be 1103, and upon calculating the remaining entities on the map using ents:GetAll, there were found to be 1748 entities remaining. This amounted to a total of 2851 entities, or 34% of the maximum limit, contrary to the console's display of (8176 current, 8192 max). Please fix this in the new March update.

**Comment by robotboy655** [comment]
No, GMod didn't begin "deleting entities upon launching". The gamemode does, and always did. As for the perceived changes to the limit, there was no change, you can find more details here:

https://github.com/Facepunch/garrysmod-issues/issues/5702#issuecomment-1917563220

Long story short, changes will be necessary to the gamemode, due to security fixes.
