### ISSUE TITLE
Env_blood doesnt function as intended

### ISSUE THREAD

**Issue by Battlefieldkille** [Facepunch/garrysmod-issues#5848]
I began using this entity in a map that im making and certain functions dont seem to work.
Here are the issues:

- [ ] Yellow (Alien) Blood Color - This just displays the default red blood.
- [ ] Amount of blood - Setting this keyvalue to 1 or 1000 doesnt change anything.
- [ ] Blood Stream flag - This produces missing textures.

Other branches behave the same way.
Map for ease of review:
[envblood.zip](https://github.com/Facepunch/garrysmod-issues/files/15128476/envblood.zip)

**Comment by robotboy655** [comment]
The "amount of blood" value is kind of obsolete because of the new particle blood effects. It still has an effect on traces for the decals and for the Blood Stream (up to 256 for the latter). This behavior is consistent with Half-Life 2 itself I imagine, after it was updated to Episode 2 features.

I will fix the missing texture and blood color being reset though. I will also add some of the new blood colors that came with EP2.
