### ISSUE TITLE
R_JeepFOV doesn't seem to work at all.

### ISSUE THREAD

**Issue by burntfrenchfries** [Facepunch/garrysmod-issues#5872]
I am using the x86-64 version.

No matter what I set r_JeepFOV to, it doesn't change, pretty simple explanation.

I've also noticed missing convars in comparison to HL2. Such as "r_JeepViewDampenDamp, r_JeepViewDampenFreq and r_JeepViewZHeight.", all this comes together to make the POV of riding in the jeep completely different then in HL2.

**Comment by robotboy655** [comment]
`r_JeepFOV` requires `sv_cheats 1` and must be set before a vehicle is spawned in. This behavior is consistent with Half-Life 2 games.

The convar defaults to different values in Half-Life 2 and Episode 2, so there isn't one magical value that makes it be consistent with every HL2 game, so in GMod we default to players' chosen FOV.

In GMod, the first person view height is also consistent with the 3rd person head/eye height, so there's that.

`r_VehicleViewDampen` is set to `0` by default in GMod and which is why the jeep view position is lower in GMod than it is in HL2, where the cvar is set to `1` by default. For Jalopy there is a hack that makes the game think the convar is enabled for that specific vehicle model.

`r_VehicleViewDampen` is disabled by default because it negatively impacts vehicle mods.
