### ISSUE TITLE
Blocking fov_desired creates a million problems when it comes to Particle Use.

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#5886]
fov_desired being anything but the default 75 makes View Model Particle Effects render incorrectly on view models.

If i cannot set a players fov_desired to 75, then compensate for their change via an in-game custom FOV modifier via Calc View (Which correctly makes view models particles appear) then everything is fucked sideways.

Either please do not block this command, or do everyone and favour and fix fov_desired causing View Model Particle Effects to disjoint and become placed incorrectly.

**Comment by robotboy655** [comment]
Do you have a test case for the particle issue you are describing?

It is not acceptable to force player's desired FOV (which persists across sessions/servers/gamemdoes) as a workaround for issues you may have. There are plenty of methods to change FOV of a player, including CalcView and Player:SetFOV.

**Comment by MagentaIris** [comment]
> Do you have a test case for the particle issue you are describing?
> 
> It is not acceptable to force player's desired FOV (which persists across sessions/servers/gamemdoes) as a workaround for issues you may have. There are plenty of methods to change FOV of a player, including CalcView and Player:SetFOV.

Head into Temporal Assassin and set your fov_desired to 100.

Pull out the Phone in-game with P or whatever bind you want and type gimmegimme in the chat for all the weapons.

You can see the Roaring Wolf has some particle mis matching due to FOV_Desired.

Here's some images anyway.

FOV Desired set to 100: 
![image](https://github.com/Facepunch/garrysmod-issues/assets/4176672/977c14e3-e5b2-4d75-861f-bcb98f9175f4)

FOV Desired set to 75, as it should be: 
![image](https://github.com/Facepunch/garrysmod-issues/assets/4176672/1ea78e80-0654-4eb9-b87e-e3062e8dc705)

ply:SetFOV() does absolutely nothing to fix this issue either (Although SetFOV does not mess up the particles). Calcview cannot overwrite the players fov_desired either.

So, thus my case of either, Unblock it or, for the love of god, fix fov_desired shitting all over view model particles.

**Comment by robotboy655** [comment]
Hmm, so from what I can see, the issue is that you are specifically NOT attaching view model particles to a view model, but rather to a clientside model. I think simply not having the particle effect being set as "viewmodel effect" in the editor would fix the issue for you.

I don't know why you say "CalcView cannot overwrite the players fov_desired either", it has an FOV parameter that works very well, including the viewmodel-attached particles.

From what I can see you are doing a lot of weird stuff in your gamemode to put it mildly, including completely breaking Weapon:CalcView and any other CalcView hook, I am not going to mess around with your obfuscated code more, but it could be an issue on your end.

There's also `SWEP:TranslateFOV` which is what Sandbox's Camera SWEP uses.

I didn't find the weapon in your pictures, but the crossbow weapon seems to have the same issue and here it is working as expected on a simple SWEP with no extra shenanigans from your code.

[](https://github.com/Facepunch/garrysmod-issues/assets/3299036/1df64e30-f1f8-4578-a9ce-358ab214673e)

On a sidenote, why is your gamemode changing convars like `sbox_noclip` and all the limits (which save across sessions) instead of using proper hooks such as https://wiki.facepunch.com/gmod/GM:PlayerNoClip? This creates a poor user experience, and may warrant blocking any `FCVAR_ARCHIVE` convar from being modified by Lua.

**Comment by MagentaIris** [comment]
Yes this is because normal View Models in source engine are jank.

Creating my own was the only way to get past the trashy animation interpolation issue in the Multiplayer Realm.

Removing the "View Model Effect" bool from the particle effect just makes it draw Infront of the client side model all the time so it looks like trash.

So that also, is not a fix.

The gamemode does utilize PlayerNoClip, There's so many CVars left over that I honestly completely forgot existed.

**Comment by MagentaIris** [comment]
If anything, just give us a hook that lets us return a value that fov_desired should copy if it exists. This way we can modify it via gamemodes and not have to force change the clients value.

So many people are reporting bugs of "Mis-aligned particles" because i can't change their fov_desired, and any other work around DOES NOT WORK.

**Comment by robotboy655** [comment]
How exactly are you rendering your viewmodels? Manually (SetNoDraw) or letting the clientside models render themselves? If manually, which hook exactly? I am testing this and it seems that the issue does not appear if you parent the clientside models to the view model, but the viewmodel FOV is not applied in this case.

**Comment by MagentaIris** [comment]
> How exactly are you rendering your viewmodels? Manually (SetNoDraw) or letting the clientside models render themselves? If manually, which hook exactly? I am testing this and it seems that the issue does not appear if you parent the clientside models to the view model, but the viewmodel FOV is not applied in this case.

Parenting the models to the view model just makes it even worse for how I work. Like i said before the View Model entity is dog shit and inconsistent in MULTIPLAYER, which is why I made my own view model system to get around its stupid limitations.

I create my Client Model, No draw it, then manually draw it via calling a function inside of SWEP:PostDrawViewModel()

The exact call is
```if ViewModel_DrawViewModels then
		
		DO_DRAW_DRAWS = true
			
		ViewModel_DrawViewModels()
		
		DO_DRAW_DRAWS = false
			
	end```

**Comment by robotboy655** [comment]
Ok, I think I understand what is happening here now.

So your "view model" is completely detached from the actual view model.
The particles are rendered by the game separately from the model they are attached to. To account for the viewmodel FOV the game has a method on the viewmodel entity to transform the attachment positions from the normal FOV to the viewmodel FOV.
Since your entity is obviously not a view model, this code does not run. Furthermore, since your entity is not parented to the viewmodel there is no direct link to the view model entity, so there can't really be a hack added for this, not that I'd want to do that tbh.

it makes sense that it "doesn't work" for you, because it's not supposed to.

There are 2 options that I see to solve your issue:
1) You render your viewmodel particles manually, just like you render the model manually. You can achieve this with https://wiki.facepunch.com/gmod/CNewParticleEffect:Render and https://wiki.facepunch.com/gmod/Global.CreateParticleSystem
2) I could maybe add some sort of hook/callback to the `anim` type entity to transform the attachment positions in anyway you wish to. You could then apply the same code the normal viewmodels use there and use an `anim` type entity for your viewmodels, you should be able to create them clientside only. It is worth mentioning that `anim` type entities are not `CBaseFlex`, like `ClientsideModel` entities are, so access to flexes may be limited. I am not sure I entirely like this idea, as it adds yet another frequently called hook to all entities, raising performance concerns, even when it is not used.

**Comment by MagentaIris** [comment]
> Ok, I think I understand what is happening here now.
> 
> So your "view model" is completely detached from the actual view model. The particles are rendered by the game separately from the model they are attached to. To account for the viewmodel FOV the game has a method on the viewmodel entity to transform the attachment positions from the normal FOV to the viewmodel FOV. Since your entity is obviously not a view model, this code does not run. Furthermore, since your entity is not parented to the viewmodel there is no direct link to the view model entity, so there can't really be a hack added for this, not that I'd want to do that tbh.
> 
> it makes sense that it "doesn't work" for you, because it's not supposed to.
> 
> There are 2 options that I see to solve your issue:
> 
> 1. You render your viewmodel particles manually, just like you render the model manually. You can achieve this with https://wiki.facepunch.com/gmod/CNewParticleEffect:Render and https://wiki.facepunch.com/gmod/Global.CreateParticleSystem
> 2. I could maybe add some sort of hook/callback to the `anim` type entity to transform the attachment positions in anyway you wish to. You could then apply the same code the normal viewmodels use there and use an `anim` type entity for your viewmodels, you should be able to create them clientside only. It is worth mentioning that `anim` type entities are not `CBaseFlex`, like `ClientsideModel` entities are, so access to flexes may be limited. I am not sure I entirely like this idea, as it adds yet another frequently called hook to all entities, raising performance concerns, even when it is not used.

CNewParticleEffect has it's own issues from what i've used and tested.

I don't see why adding a hook to modify fov_desired temporarily is such a **"BAD"** thing. It's only active during the gamemode, There's already options in the gamemode to modify your fov in ways that don't fuck my methods over and its only temporary.

**Comment by MagentaIris** [comment]
I'm going to assume that this is just a **"Deal with it"** then?

**Comment by robotboy655** [comment]
I have provided you with a solution, that being `CNewParticleEffect`. Forcing player FOV **that saves across sessions** is not a good solution to anything.

If "CNewParticleEffect has it's own issues", you can open separate reports about those.

**Comment by MagentaIris** [comment]
I just said why not just give me a hook that **DOES NOT SAVE IT ACROSS SESSIONS.**

Holy shit.

**Comment by robotboy655** [comment]
Because it makes no sense to add yet another hacky workaround for an issue for which you already have a proper solution. (as well as yet another method to change player FOV)

**Comment by MagentaIris** [comment]
I do NOT have a proper solution, Did you not read a damn thing of what I said?

It also is not a "Hacky Workaround", being able to change the players fov_desired via a hook would have ACTUAL purpose outside of fixing what issues I'm having.

I wouldn't have to work outside of the box and do all of this crazy shit if the default entities and game where not so ass backwards and finnicky in the first place.

If you're seriously going to tell me that the better option of this is for me to literally print in the players chat **"Hey friend, Because of things completely out of my control if you see particles being rendered strangely in your view, you need to change fov_desired to 75."**

The reason i use CL Models for all of my shit is because sources default entity for animation and networking sucks absolute ass, I've used this system for a long time too and this is one of the ONLY issues it has because I have no work around for it. Asking me to use CNewParticleEffect, Which i have already mentioned has its own set of bullshit and really bad issues like Attachment position lag-behind on frame 1 calls, is asanine.

If you tell me "Oh just use timer.Simple(0 to delay the CNewParticleEffect so it doesnt get frame 1 lag behinded" that's also a "Hacky Workaround" and we're just gonna go in circles until you either.

Tell me to fuck off, or do something about it which would take you about 5 minutes and minimal effort.

I'm sorry that my language is harsh, and I'm sorry that i keep bitching. But this engine is part of my life and to see such simple things brushed away with hardly a reason really pisses me off because it's out of my control.

**Comment by robotboy655** [comment]
I cannot comprehend how you can look at forcing player FOV to fix particle rendering as a good/proper solution.

You are rendering the model(s) manually in a hook that modifies model rendering (the FOV), so you have to render the particle(s) manually as well, in the same place, so they render consistently. There's no other proper solution here.

Setting the player's FOV to fix this is just as "ass backwards" workaround as you claim the engine entities to be, on the topic of which, that is not a very good way to provide feedback if you are looking for change.

**Comment by MagentaIris** [comment]
> I cannot comprehend how you can look at forcing player FOV to fix particle rendering as a good/proper solution.
> 
> You are rendering the model(s) manually in a hook that modifies model rendering (the FOV), so you have to render the particle(s) manually as well, in the same place, so they render consistently. There's no other proper solution here.
> 
> Setting the player's FOV to fix this is just as "ass backwards" workaround as you claim the engine entities to be, on the topic of which, that is not a very good way to provide feedback if you are looking for change.

Well it's not like doing anything else has done much of anything now has it.

**Comment by garryspins** [comment]
Whats the harm of allowing the "desired" fov to be changed from calcview. Since fov_desired is actually used internally for things, you should be able to change it. Then again, I'm not 100% clear on what fov_desired even exists for.

**Comment by MagentaIris** [comment]
> Whats the harm of allowing the "desired" fov to be changed from calcview. Since fov_desired is actually used internally for things, you should be able to change it. Then again, I'm not 100% clear on what fov_desired even exists for.

fov_desired has existed in source for ages, It's just the default "Change your FOV" for accessibility reasons.

It would indeed, be extremely nice to be able to change it in a hook because FOV_Desired is called and calculated before ANY fov modifications in LUA are.

This means being able to change it allows all kinds of neat little things that avoid really annoying shit that you have to deal with later down the line.

It's the same feeling as a 7 year old function being nuked or changed just because someone was a dickhead with it a SINGLE TIME.
