### ISSUE TITLE
sw.vtx Files are blacklisted by gmad.exe in 64bit branch.

### ISSUE THREAD

**Issue by hl2jeep** [Facepunch/garrysmod-issues#5903]
when trying to upload to workshop i noticed i was getting sw.vtx files from my models "not allowed by whitelist" 

to reproduce.
1. switch GMOD branch to chromium +64bit binary
2. attempt a normal upload procedure.

**Comment by robotboy655** [comment]
It is intentional. Those files are useless, and should not be included in workshop addons, It's just a waste of space.

**Comment by WolfKann** [comment]
Those files are compiled however by default whenever models are compiled, whitelisting them is going to break so many addons from being able to update.

**Comment by robotboy655** [comment]
It will not break anything, deleting them is trivial.

**Comment by neico** [comment]
Removing those files from StudioMDL generation would be a good thing to do then, pull it out by the source.

One could even go the way of L4D(2)/Portal2 and only let it generate `.vtx` files, which are synonymous with `.dx90.vtx` files.
I don't think that any other variant is needed, especially if we look towards the x64 branch. (if you are capable of running x64 applications, surely your computer is modern enough to handle DX9+ easily)

**Comment by Vuthakral** [comment]
> It will not break anything, deleting them is trivial.

I hope commenting in a closed issue doesn't re-open it inherently, but I just wanted to throw out there that deleting the `.sw.vtx` files from a model compiled with them *will* actually break the model in all rendering related contexts. I have a friend working on a weapon pack who brought this to my attention, and here's what happens when you simply delete the files rather than compile them using gmod's studiomdl:

(This is my game after downloading his weapons off the Steam Workshop, x86-64 branch 2024.09.09)
![image](https://github.com/user-attachments/assets/e18baa12-2a1f-4de5-982c-bfdf8cbd15e1)

The model has accessible bones & attachments, and even animates, but anything about drawing the model entirely fails:

https://github.com/user-attachments/assets/285aa06d-f9f9-4d1f-bfea-851e4901e24e

I understand that the `.sw.vtx` files are by all means useless nowadays since there's likely zero players left playing any Source game in compatibility dx7, but that doesn't really solve the issue that almost all existing Source games still compiled models with this, and removing the file does not appear to be harmless when it was compiled with one. This will mean that *every* model ever made prior to this which was not compiled with specific versions of studiomdl (which is almost all of them let's be real) would need to be manually recompiled.

**Comment by Screampuff** [comment]
Why are we required to remove .sw.vtx files if we're also not changing to just model.vtx standards like all updated source engine games?
