### ISSUE TITLE
Game crashes when trying to spawn entities

### ISSUE THREAD

**Issue by Mavid274** [Facepunch/garrysmod-issues#5959]
[9519578d-2f51-45df-98dc-eb63f1853d6e.dmp](https://github.com/user-attachments/files/16447642/9519578d-2f51-45df-98dc-eb63f1853d6e.dmp)

### Details
I had spawned SENTs and monitored ram usage.
Game crashes when RAM load hits ~1.5 gb (no chromium), ~2.05gb (chromium, 64bit)
Tried to allocate more memory in autoexec.cfg also in launch options.
It happens after July 2024 update

**Comment by robotboy655** [comment]
There's no such thing as "allocate more memory".

What entities are you spawning exatly?

**Comment by Joooorek** [comment]
We using entities from "Trolleybus System" addon, on our dedicated server we spawn about 20 entities and before July update everything was fine. Right  after the update we load to the server, and when we get near the entities we created, the game just crashes.

**Comment by robotboy655** [comment]
I have found a sound-related crash with steps from the linked issue above, simply by spawning in `trolleybus_ent_trolza5265` but it doesn't appear to be the crash you are experiencing.

I have tried spawning every single vehicle from the addon linked in the other issue, and there's no crash nor does the memory usage go above 1GB.

I will put the fix for the crash I found to `dev` and `x86-64` betas, please let me know if that fixes the issues you are having.

**Comment by robotboy655** [comment]
I am assuming the issue is solved due to the silence.
