### ISSUE TITLE
3D particles not using ParticleEffect angles

### ISSUE THREAD

**Issue by ImpulseTM** [Facepunch/garrysmod-issues#5965]
Protocol version 24
Exe version 2023.06.28 (garrysmod)
Exe build: 17:28:13 Jul 24 2024 (9391) (4000)
GMod version 2024.08.02, branch: unknown, multicore: 0
Windows 32bit
Launch options: -tools -nop4

--- Steps to reproduce
Create 3D particle, attach to bullet callback to align angles with Attachment/HitNormal

PCF included
ParticleEffect( "wep_proj_impact_exmp", tr.HitPos, tr.HitNormal:Angle() )

---Notes
3D particles support random rotation but they can't be altered through lua data to set their angles, position works of course but you cant rotate the effect with luaeffects.
I've tried every way possible to try to make the particle align, no dice.

.rar includes the example PCF and a video of a weapon trying to use the example in question.
I had another 3d effect that spawned a 3d particle when reloading but the particle never aligned to the attachment, the rest did but the 3d particle would always orient west

**Comment by ImpulseTM** [comment]
I didn't notice until posting that the zip didn't embed, so I renamed the pcf to txt just to upload it
[3d_particle_exmp.txt](https://github.com/user-attachments/files/16488891/3d_particle_exmp.txt)

https://github.com/user-attachments/assets/cafc8049-e21d-4dcd-a85b-a5849e9071ae

**Comment by robotboy655** [comment]
In order for the angles argument to work in that function, you must provide an entity (game.GetWorld() is sufficient) I have updated the wiki page to reflect this info.

That being said, due to a mistake on my end, there isn't a way to set the particle's normal via many of the operators, I will fix that.

Furthermore, I don't even see any default operators that read the Control Point orientation, so that may be an issue as well.

You may need to switch to using https://wiki.facepunch.com/gmod/CNewParticleEffect to access other Control Points.

I have added a bunch of new particle operators and initializers from CS:GO to the `dev` beta of the game, some of them have to do with particle Control Points and particle normals, so give it a try maybe.
