### ISSUE TITLE
Problem with the last update merged animations, possibly Linux/DS specific.

### ISSUE THREAD

**Issue by ZehMatt** [Facepunch/garrysmod-issues#5977]
### Details
Hosting a server on linux in our case Ubuntu 20 it appears the NPCs that have animation merged models don't work correctly. We tested this with a fresh install on client and server with no addons installed and both were on the main branch. When using P2P it seems to be fine, however only Windows clients have been tested.

This is what we get when we join that server:
https://www.youtube.com/watch?v=3TZzb28wQzM

### Steps to reproduce
1. Setup a dedicated server on Linux on any branch with the Sandbox game mode.
3. Set the map to d1_trainstation_05.

Also when the original models are copied and used as an addon/workshop then the animations will be fine again, so it appears there is a mismatch to what model is loaded.

**Comment by robotboy655** [comment]
I can confirm this happening with dedicated server on main and pre-release client, both on Windows.

**Comment by robotboy655** [comment]
I think I see what the issue is, your dedicated server must not be on a matching beta branch to the clients, or is not up to date. You can easily check if your server is on the `dev` beta by checking for presence of `models/dog.mdl` in the `garrysmod_dir.vpk`

I have just been trying to get SteamCMD to downgrade by `dev` server install to a NONE beta one, and many obvious things I tried did not work:
* Simply removing the `-beta dev` parameter from my SteamCMD script
* Deleting `depotcache`, `userdata`, `appcache` and `config` folders of SteamCMD itself
* I suspect wiping the gmod srcds files will not work either

What has worked is deleting `steamapps/appmanifest_4020.acf`. This successfully allowed SteamCMD to download the `NONE` beta, which solved the issues with model mismatches on my end.

**Comment by Grocel** [comment]
> I think I see what the issue is, your dedicated server must not be on a matching beta branch to the clients, or is not up to date. You can easily check if your server is on the `dev` beta by checking for presence of `models/dog.mdl` in the `garrysmod_dir.vpk`
> 
> I have just been trying to get SteamCMD to downgrade by `dev` server install to a NONE beta one, and many obvious things I tried did not work:

Just use:
```sh
steamcmd +login anonymous +app_update 4020 -beta public +quit
steamcmd +login anonymous +app_update 4020 -beta public validate +quit
```

The update run sets it to the non-beta version and updates the files.
The validation run ensures it has been properly switched.

Removing `-beta dev` or using `-beta NONE` does not do anything.
