### ISSUE TITLE
Critical Issue with m_rawinput 1

### ISSUE THREAD

**Issue by FiBzYDev** [Facepunch/garrysmod-issues#5978]
Details
I've encountered a critical issue with the raw input implementation (m_rawinput 1) in Garry's Mod (GMod), affecting both the 32-bit and 64-bit versions of the game. The issue seems to be related to how raw input is handled, resulting in degraded input performance and inconsistent behavior.

Key Points:
Inconsistent Input Behavior: When enabling raw input, there's a noticeable inconsistency in how mouse movement is accumulated, which deviates from the expected behavior seen in other Source engine games like CS
or CS
.

Choppy Accumulation: Particularly in the 32-bit version of GMod, the input accumulation is choppy, making precise movements difficult. The 64-bit version, although slightly better, still suffers from similar issues, indicating a fundamental problem with input accumulation on both versions.

Input Lag and Choppiness: Users, including myself, have experienced significant input lag and choppiness when using m_rawinput 1. Instead of smoothing out input, this setting degrades performance, which is the opposite of its intended function.

Console Spam in 32-bit Version: During my testing, I observed that in the 32-bit version of GMod, the functions GetAccumulatedMouseDeltasAndResetAccumulators and GetRawMouseAccumulators spam the console with output, even when no input is being processed. This contrasts sharply with other Source engine games, where these functions only update when actual input is detected.

Missing or Altered Functions: It appears that key functions like GetAccumulatedMouseDeltasAndResetAccumulators may have been altered or are missing, particularly in the 64-bit port of GMod. This has a direct impact on how raw input is processed.

This issue significantly impacts gameplay, particularly in scenarios that require precise input, such as competitive play. I recommend that the development team review the implementation of raw input in GMod, comparing it with how it's handled in other Source engine games to identify and fix the discrepancies.

To provide a reference, here is a link to the base in_mouse.cpp file from another Source engine project that does not exhibit these issues: [in_mouse.cpp on GitHub](https://github.com/Zantier/css-base/blob/79a07e53833192aba91ceb026c687385998ffa04/mp/src/game/client/in_mouse.cpp#L5). This file could serve as a useful comparison to help identify what might be going wrong in GMod's raw input handling.

https://github.com/Zantier/css-base/blob/79a07e53833192aba91ceb026c687385998ffa04/mp/src/public/inputsystem/iinputsystem.h#L118

Steps to Reproduce
Enable m_rawinput 1 in GMod on either 32-bit or 64-bit versions.
Play the game, particularly focusing on scenarios that require precise mouse input.
Observe the choppiness and inconsistency in mouse movement.
Debug the 32-bit version and note the console spam from GetAccumulatedMouseDeltasAndResetAccumulators and GetRawMouseAccumulators, even when no input is being detected.
(Optional) Compare the behavior with another Source engine game, such as CS
, to note the differences in input handling.
Additional Notes:

Testing without any addons or workshop content may help isolate the issue to the base game.
It would be helpful to collect data and logs to support these observations.
This issue is crucial for maintaining a consistent and enjoyable gameplay experience, and addressing it would greatly improve the performance and feel of mouse input in GMod. If other players have experienced similar issues or have more insights, their contributions would be valuable for resolving this problem.

**Comment by robotboy655** [comment]
Can you be more specific about what the actual issue is? I have been using raw input in GMod and other Source Engine games (Notably CS:GO, and CS2) for over 10 years, and have not ever noticed either "Choppy movement" and "input lag" while using different mouse devices.

Is there something you can actually measure and show that would demonstrate the issue is present?
Are you sure the issue is not with your hardware or settings in or outside of the game, such as your DPI setting and mouse sensitivity settings?

I am also not sure what console spam you are referring to, both of the functions you have mentioned do not output anything to the console.
Perhaps you are running some pirated or otherwise modified or out of date version of the game, or some of its components? Have some 3rd party software interfering with the game somehow?
Furthermore, after briefly comparing the linked file, there's basically no changes in GMod regarding mouse input, save for one, which is handing of `m_filter`, which is force-enabled at all times. (Been this way since before 2014)

**Comment by FiBzYY** [comment]
GMod's Raw Input is Broken --Analysis --
I have been playing GMod since 2014 and have accumulated thousands of hours in movement-based gamemodes across both GMod and CS:S. I also have extensive experience with other Source Engine games, including CS:GO, TF2, and Momentum Mod, where raw input behaves correctly.

Hardware:
Processor: Intel i9-12900K (16 Cores, 24 Threads)
Motherboard: Z690 AORUS ELITE AX DDR4
GPU: NVIDIA RTX 2060 Super
Monitor: ASUS 280Hz G-Sync Monitor
Game Version: Latest GMod (32-bit & 64-bit tested)
Mouse: G502 hero polling rate: 1000

Mouse Tester Data:
Events: 10,508
Sum X: -339 counts
Sum Y: 453 counts
Path: 30,585 counts

confirms hardware is working correctly.
confirms polling is stable.

Proof That GMod’s Raw Input is Broken
After extensive testing, I can confirm that raw input (m_rawinput 1) in GMod is flawed on both 32-bit and 64-bit versions.

Issue #1: GMod Handles Raw Input Differently Than Other Source Games
In CS:S, CS:GO, and other Source games, raw input behaves consistently and correctly.
In GMod, raw input is flawed, causing choppy movement, inconsistent tracking, and input lag.

Issue #2: GetAccumulatedMouseDeltasAndResetAccumulators is Missing in GMod 64-bit
This function is critical for proper raw input accumulation.

In 32-bit GMod, this function still exists, but it does not behave correctly.
In 64-bit GMod, this function has been removed completely or stopped working entirely.

Expected Behavior (CS:S, TF2, Momentum Mod):
Mouse deltas are accumulated properly and evenly spread over ticks.
Actual Behavior (GMod 32-bit & 64-bit):
Mouse deltas accumulate incorrectly, causing stuttery movement when FPS ≠ Tickrate.

Technical Proof
Proof #1: Mouse Tester Confirms No Hardware Issues
Mouse polling is stable at 1000Hz.
GMod has erratic mouse movement, but the same test in CS:S is perfectly smooth.
This confirms the issue is inside GMod, not the hardware.

Proof #2: Disassembly Confirms Function is Missing
Disassembling client.dll in IDA/Ghidra shows that GetAccumulatedMouseDeltasAndResetAccumulators() is:
Present in CS:S.
Still exists in GMod 32-bit, but does not function correctly.
Completely missing from GMod 64-bit.
This function is essential because it prevents input accumulation errors.
In GMod 64-bit, the removal of this function makes input smoother, but this is not a proper fix.
32-bit GMod should have proper raw input accumulation, and 64-bit GMod should not need this function removed to feel smooth.

Proof #3: Debugging GMod’s Input System
Printing inside GetAccumulatedMouseDeltasAndResetAccumulators() should only trigger when the mouse is moved.
In GMod, this function spams messages even when in the menu.
This means accumulation logic is wrong, confirming that input handling is flawed.

GMod is one of the only Source Engine games where raw input behaves incorrectly.
This directly impacts movement gamemodes like bhop, surf, and parkour, causing:

Inconsistent movement behavior across different framerates.
Erratic sensitivity changes when FPS ≠ Tickrate.
Increased input lag compared to CS:S or CS:GO.

 Why RawInput2 Can’t Fully Fix GMod
I successfully ported RawInput2 to GMod 32-bit, but it doesn’t fully work because GMod’s raw input system is flawed.
Even without RawInput2, GMod’s m_rawinput 1 is already broken.
This is an engine-level problem that Facepunch must address.

“There’s no noticeable input lag or choppy movement.”
“Maybe it’s your hardware.”
“There are no significant changes to raw input.”

MouseTester confirms there is no hardware issue.
Side-by-side comparisons with CS:S show clear input inconsistencies.
Raw input handling in GMod is not the same as other Source Engine games.
Disassembly confirms GetAccumulatedMouseDeltasAndResetAccumulators() is missing.
The function is spamming console messages, proving it is malfunctioning.
Removing this function in 64-bit makes input smoother, but this is not a proper fix.
If Facepunch actually tested GetAccumulatedMouseDeltasAndResetAccumulators(), they would see the issue themselves.

Final Conclusion: GMod’s Input System Needs Fixing
GMod’s input handling is broken, and it has been for years.

This is not a user-side issue—it’s an engine flaw.
must address this by properly implementing raw input, like in CS:S and other Source games.
Simply removing GetAccumulatedMouseDeltasAndResetAccumulators() is not the right fix.
Without a proper fix, GMod will always have flawed mouse movement.

**Comment by robotboy655** [comment]
We are not getting anywhere useful here. You keep repeating the same points over and over and making claims, but can never actually show any issues.

Can you record a video that clearly shows the "stuttery/choppy movement" in GMod and whatever other game? You claim that "Side-by-side comparisons with CS:S show clear input inconsistencies.", even though I myself, and the entire GMod playerbase can not perceive any issues. Record the comparison and post it here.

**Comment by FiBzYY** [comment]
https://drive.google.com/file/d/1TWY0oHwyeTFuG9m9avlLpMRXkkbe7oTP/view?usp=sharing

Run 280 hz you can see that GMods one as this 1 tick lag feeling tested on all gmod servers to make sure its not just one server, its fine if it doesn't get fixed im just bring attention to the issuse and it really does exist.

**Comment by robotboy655** [comment]
I am not really sure what I am supposed to look at with these videos, they look equally smooth to me. it's also quite hard to understand your half-typed words sometimes.
I don't think you could perceive a "1 tick lag" or really show it in a video like that, neither does the video really show any "stuttery/choppy movement" that you so adamantly claim is obvious. 

As I have said before, the code that handles this in Garry's Mod is identical to all other Source Engine games, with the exception for `m_filter` being forced to `1` for whatever reason. Would enabling `m_filter` to `1` in CS:S make it feel the same as it does in GMod for you? I am noticing that in CS:GO the convar is removed and its effectiveness is forced to `0`.

Or could it be another `m_*` convar that you have set differently between the 2 games?

Keep in mind that in Garry's Mod gamemodes/addons can affect mouse input as well, such as via the `InputMouseApply` hook.

`x86-64` also appears to disable raw input when not playing on any map, I don't know why this is.
