### ISSUE TITLE
ambient_generic/func_smokevolume limits on the map

### ISSUE THREAD

**Issue by Mayorov0001** [Facepunch/garrysmod-issues#5987]
I want to report an extremely unpleasant bug.

When creating my map, I noticed that at one point some ambient_generic simply stopped working for me. 
After several hours of torture, I realized that if you remove 50% of the existing and installed ones on the map, everything will work. Limits on ambient_generic - seriously?

There is also a problem with the func_smokevolume. If there is a large number on the map (I will not be able to give exact numbers, about 20 will already be above my head), half will stop working. This is a long-standing problem that my mapper friends have also faced.

I just don't get it. Due to ambient_generic errors - I have to limit myself in the sound accompaniment of the map, thanks to func_smokevolume - I cannot implement more than 10 rooms with a beautiful smoke effect. WTF.
Please fix it!

**Comment by robotboy655** [comment]
Since you have not provided any map files or anything, I can only speculate on the issues you are having. Yes, there are limits on amount of simultaneous particles and sounds in this 2004 game engine.

Are you sure you are using `ambient_generic` correctly? I think using the soundscape system should solve your issues, so you do not try to play every sound on your map at the same time at all times.

As for `func_smokevolume`, I am not sure if the issue you are having is too many particles at the same time, but perhaps some optimization from your end can be done, to disable the particles that cannot be seen. Alternative solution might be to create your own particle system using the newer particle system (info_particle_system)

**Comment by Mayorov0001** [comment]
https://drive.google.com/file/d/1E-P2PBBn7EVdu_wRTRyKiTqKJ-Bi8O2-/view?usp=sharing

I apologize for not providing any .vmf files.
This time, I reinforced it.
The limit is read even at the moment when smoke_volume is being drawn at the other end of the map. How to put it more correctly, the engine as a whole considers all the resources on the map - and not at a certain rendering level.

The situation is similar with ambient_generic. I use both areaportal and areaportal_window.. In general, I share the entire map as soon as possible - and nevertheless, the problem remains a problem. The reading is based on the quantity, not at the time of rendering to the user.

**Comment by robotboy655** [comment]
Alright, yeah, you are hitting the simultaneous particle limit, which is set to 8k.

I will update `func_smokevolume` to remove its particles when it goes outside of players' PVS, which should help with the map-wide limit.

**Comment by Mayorov0001** [comment]
Thanks so much for the feedback!
Please take similar actions against ambient_generic
