### ISSUE TITLE
Alien Controller damage is inconsistent.

### ISSUE THREAD

**Issue by darkpikmin99** [Facepunch/garrysmod-issues#5999]
Saw this while messing with npcs awhile ago, but kinda forgot about it until now. This was tested with no mods enabled.
### Details
The smaller Alien Controller projectiles currently cannot damage anything. The big homing one it occasionally uses still can, but the damage can range from not much to more than half of your health.

### Steps to reproduce

1. Load any map.
2. Spawn an Alien Controller and let it attack.
3. If it fired the small ones from its hands, it won't do damage, if it fired the big one from its head, the damage will vary wildly.

**Comment by robotboy655** [comment]
I have fixed the small balls not doing damage, as for the inconsistent damage of the head balls, it's due to the body part that the ball hits the player. By default in Sandbox, the damage to arms and legs is reduced.

This behavior can be seen here:
https://github.com/Facepunch/garrysmod/blob/80862f4d5ee27df7827e77388e477056fdf295fc/garrysmod/gamemodes/base/gamemode/player.lua#L494-L514

Default damage is 25, if it hits legs/arms it is reduced 75%, so it becomes 25 * 0.25 = 6.25
