### ISSUE TITLE
point_spotlight cleanup

### ISSUE THREAD

**Issue by Combine900** [Facepunch/garrysmod-issues#6011]
Is there a reason why the entity "point_spotlight" had keyvalues for "gmod_allowphysgun" & "gmod_allowtools"?

You cant move or edit the entity, or is it supposed to be? Than its a bug.

**Comment by robotboy655** [comment]
The reason is that these settings are not individually added to each entity, they are added to "base classes" in Hammer, which affect many entities at the same time.

There a lot of properties that simply do nothing on certain entities, yet technically exist on them.

That being said, should be fixed on `dev` beta, hopefully without downgrades.
