### ISSUE TITLE
CNavArea::UpdateBlocked update timer no longer seems to work

### ISSUE THREAD

**Issue by Necrossin** [Facepunch/garrysmod-issues#6034]
### Details

If I'm not mistaken, NavArea is supposed to call a self-update 5 ticks timer in the UpdateBlocked function. That, however, no longer works now after a certain update (can't pinpoint which one, but it was working as intended around a half a year ago or so).
Tested on dev branch (2024.10.16).

### Expected behaviour

After removing an obstacle from a blocked NavArea (usually a breakable wall or a sliding door) - it is supposed to mark itself as unblocked shortly after.

### Steps to reproduce

1. Load the zm_redqueen_b6_rc.bsp map as an example (in Sandbox)
2. Go to the sliding door shown in the video
3. Run "nav_update_blocked", the area under the sliding door will properly show as blocked
4. Move the door away with physgun (or remove it)
5. That area will stay as blocked, until you force the "nav_update_blocked" command again

Map and navmesh:
[zm_redqueen_b6_rc.zip](https://github.com/user-attachments/files/17400562/zm_redqueen_b6_rc.zip)

<video src="https://github.com/user-attachments/assets/e3101805-02f1-4eb2-8a7c-4965d620864d" width="360" />

**Comment by robotboy655** [comment]
I doubt this has ever worked. The `UpdateBlocked` function only ever runs for areas that are already blocked. I'd grant you the fact that it no longer self unblocks, because that by itself is incompatible with having a Lua binding to block the area. I will have to change how that works.

But the self-blocking timer never fires in GMod because it is started from a function called "CNavMesh::OnRoundRestart" which is never called in GMod, since it's not a round based game.

**Comment by Necrossin** [comment]
I do recall self-blocking not working at all (hence why I had to call "nav_update_blocked" whenever I had to do a gamemode round start/restart). 
Guess I'll have to handle unblocking areas manually, for now :/

**Comment by robotboy655** [comment]
Both should now be fixed on `dev` beta. If there are any issues, let me know.

**Comment by Necrossin** [comment]
Auto unblocking seems to work nicely now, thanks!
