### ISSUE TITLE
render.RedownloadAllLightmaps not working for Static Props.

### ISSUE THREAD

**Issue by MagentaIris** [Facepunch/garrysmod-issues#6095]
In ep2_outland_06a, using engine.LightStyle( 0, "a" ) and then doing render.RedownloadAllLightmaps(true,true) doesnt cause static props to update their lighting.

![Image](https://github.com/user-attachments/assets/ccd33cd0-b963-44d2-a4c5-3ae2a18dd169)

**Comment by robotboy655** [comment]
This is due to static prop lightmaps (which can be disabled via `r_proplightingfromdisk 0` before map load), and likely will need to be changed in shaders, although I am not sure how feasible it is to have both shading techniques being used at once. There's probably going to be regressions no matter what I try.

**Comment by MagentaIris** [comment]
> This is due to static prop lightmaps (which can be disabled via `r_proplightingfromdisk 0` before map load), and likely will need to be changed in shaders, although I am not sure how feasible it is to have both shading techniques being used at once. There's probably going to be regressions no matter what I try.

That's understandable. Sorry for my late response.
