### ISSUE TITLE
cannot download and install legacy.bin addons on linux mint

### ISSUE THREAD

**Issue by teamkill3d** [Facepunch/garrysmod-issues#6098]
### Details
when downloading addons on gmod through the workshop, specifically addons packaged through legacy.bin, the download always results in an input/output failure, no matter what

for some reason, even on the flatpak version of steam, this always happens, and only on linux mint too, as i've tried it out on a laptop running alpine, where it worked perfectly fine there

### Steps to reproduce
1. create a virtual machine/real computer running linux mint
2. download steam and gmod
3. install any legacy.bin addons (i.e gm_bigcity or gm_construct_in_flatgrass)

**Comment by robotboy655** [comment]
Do you have the `steamapps/GarrysMod/garrysmod/cache/workshop` folder at all on your Mint system? I wonder if it's a case of it not being automatically created

**Comment by robotboy655** [comment]
"workshop folder on my pc" is kinda vague. I am talking about specifically `steamapps/GarrysMod/garrysmod/cache/workshop`, not `steamapps/workshop`.

If the `.bin` files are not appearing in `steamapps/workshop/4000`, then the issue is with Steam specifically and you should contact Steam Support about it, not here.

**Comment by teamkill3d** [comment]
they aren't appearing in either folder, thank you for telling me who to go to
