### ISSUE TITLE
Failed to lock vertex buffer

### ISSUE THREAD

**Issue by skynet1** [Facepunch/garrysmod-issues#732]
Garry's mod will often randomly crash with an error message saying: "failed to lock vertex buffer in CMeshDX8::LockVertexBuffer:nVertexCount=336" in linux mint maya.

**Comment by s0r00t** [comment]
So. 3 months after. The bug is still present.
I'd like to know if it will be fixed one day.
I know a lot of users report issues, but this one is pretty important as I can't play GMod anymore.
I can't do anything to fix it. It's the only Source game to crash for me. I can't run the game on swap memory.
And no it's not asking for support. Just a fix for a recurring crash.

Thanks for the help.

**Comment by heil-stalin** [comment]
Nah. No bug fixes for you or me.

**Comment by s0r00t** [comment]
I have a dream that one day Facepunch will fix their games to be playable. HL3 will release before GMod supports Linux correctly.

All Linux crashes.

**Comment by ask-compu** [comment]
is this still a thing? im having this issue on ubuntu 14.04.4

**Comment by dangranos** [comment]
Intel intergrated GPU - instant crash and then closing of window on joining and starting to load a server with random (As in, one of "faled to lock" or something like that) message about vertex buffers. Haven't tried testing more than one server though.

**Comment by robotboy655** [comment]
The error means you run out of video memory. Integrated GPUs are in most cases not enough to play the game, especially not on RP servers.

**Comment by dangranos** [comment]
Ah, thanks for the tip! That really really should be written somewhere in exactly that wording, instead of vague "Just update everything and pray it works".

**Comment by Kefta** [comment]
It is -- check the Steam store minimum requirements page.
