### ISSUE TITLE
Sound scripts are extremely intensive to play

### ISSUE THREAD

**Issue by JetBoom** [Facepunch/garrysmod-issues#869]
If you play a sound script (ex: Weapon_SMG1.Single) then it takes a ridiculous amount of time compared to a straight file.

At first glance it might seem like parsing the scripts or whatever is what takes so long. But it takes the SAME amount of time to attempt to play a missing .wav file. This suggests that every time a sound script plays, the game tries finding a file that doesn't exist before it attempts to see if a sound script exists.

This chops off a LOT of perf if you have a gamemode with lots of gunfire going on or, god help you, you play sound scripts for player footsteps.

**Comment by BoXiousNet** [comment]
Why was this closed? I'm certain the issue wasn't fixed.

Using "+showbudget", and "fs_tellmeyoursecrets 1", you can see that in the console, soundscripts search all directories for the sound to play.
The issue is that, it doesn't remember where it found the correct sound to play, so it performs a search on the filesystem in every possible directory over and over every time the soundscript is played, and thus the client loses fps due to this.

On sandbox, if you had weapon quickswitch enabled, spam the scrollwheel, due to the fact I have addons and gamemodes and other mounted games, the console log is way too big.
player.weaponselectionclose causes this http://pastebin.com/dLVHUkPR

It would be really great if this issue could be fixed, as a lot of custom gmod content does use soundscripts
